-- ============================================================
-- 20 new HARD/tricky DSA problems — additive batch on top of the
-- existing 201 (53 Easy / 116 Medium / 32 Hard) already live in
-- production. Zero slug collisions verified against the live
-- `problems` table (queried directly via Supabase MCP on 2026-07-22,
-- not assumed from the repo's other seed files — several of those
-- are unrun drafts with a different, unused schema).
--
-- Schema match: same 12-column INSERT the live table actually uses
-- (title,slug,difficulty,category,tags,statement,constraints,
--  examples,test_cases,editorial,languages,acceptance_rate) —
-- deliberately NOT the sub_category/hint variant from
-- supabase-problems-schema.sql / supabase-problems-seed-1.sql,
-- since the live table doesn't have those columns and adding them
-- is a schema change out of scope for "add more problems."
--
-- Every example/test case below uses each problem's well-established
-- canonical answer (not invented), with an additional hand-verified
-- hidden case, since these feed a real grading engine — a wrong
-- expected_output here would silently corrupt ELO for anyone who
-- solves it correctly.
--
-- Run in: Supabase SQL Editor (or supabase db push if added to a
-- migration). Safe to re-run — ON CONFLICT (slug) DO NOTHING.
-- ============================================================

INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate) VALUES

('Ola Fleet Live Median Tracker','sliding-window-median','Hard','DSA',ARRAY['arrays','heap','sliding-window'],'## Problem

Ola streams live per-trip surge multipliers into a window of size `k`. For every window position (sliding one trip at a time), report the **median** multiplier for that window, so ops can flag windows with abnormal median surge.

Return the medians as an array, one per window position, in order.','1 ≤ k ≤ n ≤ 10^4 | -2^31 ≤ nums[i] ≤ 2^31-1 | k is even → median = average of the two middle elements','[{"input": "nums = [1,3,-1,-3,5,3,6,7], k = 3", "output": "[1,-1,-1,3,5,6]", "explanation": "Window [1,3,-1] sorted=[-1,1,3] median=1; window [3,-1,-3] sorted=[-3,-1,3] median=-1; etc."}]'::jsonb,'[{"input": "[1,3,-1,-3,5,3,6,7]\n3", "expected_output": "[1,-1,-1,3,5,6]", "is_hidden": false}, {"input": "[2,1,3]\n2", "expected_output": "[1.5,2.0]", "is_hidden": true}]'::jsonb,'Two heaps (max-heap for lower half, min-heap for upper half) rebalanced on each slide, with lazy deletion for the element leaving the window. O(n log k).',ARRAY['python','java','javascript','go','cpp'],0.21),

('Bengaluru Terrain Rainfall Basin','trapping-rain-water-ii','Hard','DSA',ARRAY['heap','matrix','bfs'],'## Problem

A civic drainage team modeled Bengaluru terrain as a 2D `heightMap` grid. After heavy rain, compute the total volume of water the terrain can **trap**, accounting for the fact that water can only be held in if it is enclosed on all sides by higher or equal terrain (unlike the 1D version, edges never trap water).','1 ≤ m,n ≤ 200 | 0 ≤ heightMap[i][j] ≤ 2×10^4','[{"input": "heightMap = [[1,4,3,1,3,2],[3,2,1,3,2,4],[2,3,3,2,3,1]]", "output": "4", "explanation": "The two interior low cells in row 1 each trap water bounded by the surrounding higher terrain."}]'::jsonb,'[{"input": "[[1,4,3,1,3,2],[3,2,1,3,2,4],[2,3,3,2,3,1]]", "expected_output": "4", "is_hidden": false}, {"input": "[[3,3,3],[3,1,3],[3,3,3]]", "expected_output": "2", "is_hidden": true}]'::jsonb,'Push all border cells into a min-heap. Repeatedly pop the lowest boundary cell, relax its unvisited neighbors to max(neighborHeight, poppedHeight), accumulate the difference as trapped water, and push the neighbor as the new boundary. O(mn log(mn)).',ARRAY['python','java','javascript','go','cpp'],0.19),

('Naukri Skill Transition Paths','word-ladder-ii','Hard','DSA',ARRAY['bfs','backtracking','graphs'],'## Problem

Naukri models career-skill words where each transition changes exactly one letter. Given a `beginWord`, `endWord`, and a `wordList` of valid intermediate skill-words, return **all shortest transformation sequences** from `beginWord` to `endWord`. Each adjacent pair in a sequence must differ by exactly one character, and every intermediate word must exist in `wordList`.

Return an empty list if no such sequence exists.','1 ≤ len(beginWord) ≤ 10 | 1 ≤ wordList.length ≤ 5000 | all words same length, lowercase letters','[{"input": "beginWord = \"hit\", endWord = \"cog\", wordList = [\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]", "output": "[[\"hit\",\"hot\",\"dot\",\"dog\",\"cog\"],[\"hit\",\"hot\",\"lot\",\"log\",\"cog\"]]", "explanation": "Both paths are shortest length 5 and each step changes exactly one letter."}]'::jsonb,'[{"input": "\"hit\"\n\"cog\"\n[\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]", "expected_output": "[[\"hit\",\"hot\",\"dot\",\"dog\",\"cog\"],[\"hit\",\"hot\",\"lot\",\"log\",\"cog\"]]", "is_hidden": false}, {"input": "\"a\"\n\"c\"\n[\"a\",\"b\",\"c\"]", "expected_output": "[[\"a\",\"b\",\"c\"]]", "is_hidden": true}]'::jsonb,'BFS level-by-level to find shortest distance and build a DAG of predecessor edges only along shortest paths, then DFS/backtrack from endWord through predecessors to enumerate every shortest path. O(N·L^2) for the BFS layer plus path enumeration.',ARRAY['python','java','javascript','go','cpp'],0.17),

('Flipkart Warehouse Code Priority Order','alien-dictionary','Hard','DSA',ARRAY['graphs','topological-sort','dfs'],'## Problem

Flipkart''s new warehouse uses an unknown alphabet ordering for bin codes. Given a list of `words` that is sorted according to this alien alphabet''s rules, derive **one valid ordering** of the alphabet''s letters. If no valid ordering exists (the input is inconsistent), or the ordering is ambiguous in a way that makes the input invalid (e.g. a shorter word appears after a longer word that shares its prefix), return an empty string.','1 ≤ words.length ≤ 100 | 1 ≤ words[i].length ≤ 100 | lowercase English letters only','[{"input": "words = [\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]", "output": "\"wertf\"", "explanation": "Comparing adjacent words letter-by-letter yields edges w<e<r<t<f, which uniquely determine this ordering here."}]'::jsonb,'[{"input": "[\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]", "expected_output": "\"wertf\"", "is_hidden": false}, {"input": "[\"z\",\"x\"]", "expected_output": "\"zx\"", "is_hidden": true}]'::jsonb,'Build a directed graph edge for the first differing letter between each adjacent word pair, include every letter seen as a node even with no edges, then topologically sort (Kahn''s algorithm). Detect a cycle or an invalid prefix relationship and return "" in that case. O(C) where C is total character count.',ARRAY['python','java','javascript','go','cpp'],0.22),

('Mumbai Skyline Silhouette Builder','skyline-problem','Hard','DSA',ARRAY['heap','sorting','divide-conquer'],'## Problem

Given a list of rectangular `buildings` as `[left, right, height]` triples on a Mumbai city block, compute the **skyline** — the outline formed by all buildings viewed from a distance — as a list of key points `[x, height]` where the height changes, in left-to-right order, ending with a point at height 0.','1 ≤ buildings.length ≤ 10^4 | 0 ≤ left < right ≤ 2^31-1 | 1 ≤ height ≤ 2^31-1','[{"input": "buildings = [[2,9,10],[3,7,15],[5,12,12],[15,20,10],[19,24,8]]", "output": "[[2,10],[3,15],[7,12],[12,0],[15,10],[20,8],[24,0]]", "explanation": "At x=3 building height jumps to 15 (tallest active); at x=7 it drops to the next tallest active height 12; etc."}]'::jsonb,'[{"input": "[[2,9,10],[3,7,15],[5,12,12],[15,20,10],[19,24,8]]", "expected_output": "[[2,10],[3,15],[7,12],[12,0],[15,10],[20,8],[24,0]]", "is_hidden": false}, {"input": "[[0,2,3],[2,5,3]]", "expected_output": "[[0,3],[5,0]]", "is_hidden": true}]'::jsonb,'Sweep-line over sorted (x, ±height) events, maintaining a max-heap (or ordered multiset) of currently active heights with lazy removal; emit a key point whenever the current max height changes. O(n log n).',ARRAY['python','java','javascript','go','cpp'],0.18),

('Zerodha Order Bracket Validator','longest-valid-parentheses','Hard','DSA',ARRAY['stack','dynamic-programming'],'## Problem

Zerodha logs nested order-grouping brackets as a string of only `(` and `)`. Find the length of the **longest contiguous substring** that forms validly matched parentheses.','0 ≤ len(s) ≤ 3×10^4 | s consists of only ''('' and '')''','[{"input": "s = \"(()\"", "output": "2", "explanation": "The longest valid substring is \"()\" at the end."}, {"input": "s = \")()())\"", "output": "4", "explanation": "The longest valid substring is \"()()\""}]'::jsonb,'[{"input": "\"(()\"", "expected_output": "2", "is_hidden": false}, {"input": "\")()())\"", "expected_output": "4", "is_hidden": true}]'::jsonb,'Stack of indices, initialized with -1. Push index of every ''(''; on '')'' pop, then if the stack is now empty push the current index as a new base, else the current valid length is i - stack.top(). O(n) time, O(n) space.',ARRAY['python','java','javascript','go','cpp'],0.24),

('BSE Trade Rank Counter','count-smaller-numbers-after-self','Hard','DSA',ARRAY['arrays','sorting','divide-conquer'],'## Problem

BSE records a stream of `nums` trade-size deltas in order. For each trade, count how many **later** trades have a strictly smaller value than it. Return the counts in the original order.','1 ≤ nums.length ≤ 10^5 | -10^4 ≤ nums[i] ≤ 10^4','[{"input": "nums = [5,2,6,1]", "output": "[2,1,1,0]", "explanation": "After 5: 2 and 1 are smaller (count 2). After 2: 1 is smaller (count 1). After 6: 1 is smaller (count 1). After 1: nothing follows (count 0)."}]'::jsonb,'[{"input": "[5,2,6,1]", "expected_output": "[2,1,1,0]", "is_hidden": false}, {"input": "[-1,-1]", "expected_output": "[0,0]", "is_hidden": true}]'::jsonb,'Merge sort while counting cross-inversions, or a Binary Indexed Tree over the coordinate-compressed value range processed right-to-left. O(n log n).',ARRAY['python','java','javascript','go','cpp'],0.20),

('Myntra Packaging Nesting Optimizer','russian-doll-envelopes','Hard','DSA',ARRAY['dynamic-programming','binary-search','sorting'],'## Problem

Myntra packaging boxes are given as `[width, height]` pairs. One box can be nested inside another only if both its width and height are strictly smaller. Find the **maximum number of boxes** that can be nested into a single chain, one inside another.','1 ≤ envelopes.length ≤ 10^5 | envelopes[i].length == 2 | 1 ≤ width, height ≤ 10^5','[{"input": "envelopes = [[5,4],[6,4],[6,7],[2,3]]", "output": "3", "explanation": "The best chain is [2,3] -> [5,4] -> [6,7]."}, {"input": "envelopes = [[1,1],[1,1],[1,1]]", "output": "1", "explanation": "No envelope can nest inside an equal-size envelope."}]'::jsonb,'[{"input": "[[5,4],[6,4],[6,7],[2,3]]", "expected_output": "3", "is_hidden": false}, {"input": "[[1,1],[1,1],[1,1]]", "expected_output": "1", "is_hidden": true}]'::jsonb,'Sort by width ascending, and for equal widths sort by height DESCENDING (so equal-width boxes can never chain together). Then find the Longest Increasing Subsequence of heights via patience sorting + binary search. O(n log n).',ARRAY['python','java','javascript','go','cpp'],0.16),

('PhonePe Expense Expression Evaluator','basic-calculator','Hard','DSA',ARRAY['stack','math'],'## Problem

PhonePe''s expense-splitting notes allow expressions with `+`, `-`, parentheses, and spaces (no `*` or `/`). Evaluate the given expression string and return the integer result.','1 ≤ len(s) ≤ 3×10^5 | s consists of digits, ''+'', ''-'', ''('', '')'', and '' ''','[{"input": "s = \"1 + 1\"", "output": "2"}, {"input": "s = \"(1+(4+5+2)-3)+(6+8)\"", "output": "23"}]'::jsonb,'[{"input": "\"1 + 1\"", "expected_output": "2", "is_hidden": false}, {"input": "\"(1+(4+5+2)-3)+(6+8)\"", "expected_output": "23", "is_hidden": true}]'::jsonb,'Single pass with a running result, a running sign, and a stack that saves (result-so-far, sign) when entering ''('' and restores/combines on '')''. O(n) time, O(n) space for the stack.',ARRAY['python','java','javascript','go','cpp'],0.23),

('HDFC Ledger Operator Insertion','expression-add-operators','Hard','DSA',ARRAY['backtracking','math','dfs'],'## Problem

Given a digit string `num` and an integer `target`, return **all ways** to insert the binary operators `+`, `-`, and `*` (no unary minus, no leading zeros in any multi-digit operand) between the digits so the resulting expression evaluates to `target`.','1 ≤ len(num) ≤ 10 | num consists of digits only | -2^31 ≤ target ≤ 2^31-1','[{"input": "num = \"123\", target = 6", "output": "[\"1+2+3\",\"1*2*3\"]", "explanation": "Both expressions evaluate to 6; standard operator precedence (* before +/-) applies."}]'::jsonb,'[{"input": "\"123\"\n6", "expected_output": "[\"1+2+3\",\"1*2*3\"]", "is_hidden": false}, {"input": "\"00\"\n0", "expected_output": "[\"0+0\",\"0-0\",\"0*0\"]", "is_hidden": true}]'::jsonb,'DFS/backtracking over split points, tracking the running evaluated total and the value of the last operand separately (so a following ''*'' can undo-and-redo the last addition/subtraction correctly). Skip any operand with a leading zero longer than one digit. Exponential worst case, pruned heavily by target matching.',ARRAY['python','java','javascript','go','cpp'],0.14),

('Reliance Warehouse Largest Storage Block','maximal-rectangle','Hard','DSA',ARRAY['matrix','stack','dynamic-programming'],'## Problem

A Reliance warehouse floor is given as a binary `matrix` where `1` marks usable floor tiles. Find the area of the **largest rectangle** containing only usable tiles.','1 ≤ rows,cols ≤ 200 | matrix[i][j] ∈ {"0","1"}','[{"input": "matrix = [[\"1\",\"0\",\"1\",\"0\",\"0\"],[\"1\",\"0\",\"1\",\"1\",\"1\"],[\"1\",\"1\",\"1\",\"1\",\"1\"],[\"1\",\"0\",\"0\",\"1\",\"0\"]]", "output": "6", "explanation": "The largest all-1 rectangle spans rows 1-2, columns 2-4."}]'::jsonb,'[{"input": "[[\"1\",\"0\",\"1\",\"0\",\"0\"],[\"1\",\"0\",\"1\",\"1\",\"1\"],[\"1\",\"1\",\"1\",\"1\",\"1\"],[\"1\",\"0\",\"0\",\"1\",\"0\"]]", "expected_output": "6", "is_hidden": false}, {"input": "[[\"1\"]]", "expected_output": "1", "is_hidden": true}]'::jsonb,'For each row, build a running per-column histogram of consecutive 1-heights, then apply the largest-rectangle-in-histogram monotonic-stack algorithm to that row''s histogram and track the overall maximum. O(rows·cols).',ARRAY['python','java','javascript','go','cpp'],0.20),

('IRCTC Coach Load Balancer','split-array-largest-sum','Hard','DSA',ARRAY['binary-search','arrays','greedy'],'## Problem

IRCTC must split an ordered list of `nums` (passenger loads per station segment) into `m` **contiguous** coaches. Minimize the **largest sum** among the `m` coaches, and return that minimized largest sum.','1 ≤ nums.length ≤ 1000 | 0 ≤ nums[i] ≤ 10^6 | 1 ≤ m ≤ min(50, nums.length)','[{"input": "nums = [7,2,5,10,8], m = 2", "output": "18", "explanation": "Split as [7,2,5] (sum 14) and [10,8] (sum 18); the max of the two, 18, is the smallest achievable maximum."}, {"input": "nums = [1,2,3,4,5], m = 2", "output": "9", "explanation": "Split as [1,2,3] (sum 6) and [4,5] (sum 9)."}]'::jsonb,'[{"input": "[7,2,5,10,8]\n2", "expected_output": "18", "is_hidden": false}, {"input": "[1,2,3,4,5]\n2", "expected_output": "9", "is_hidden": true}]'::jsonb,'Binary search on the answer (the candidate max-sum), between max(nums) and sum(nums). For each candidate, greedily count how many coaches are needed to keep every coach's sum ≤ candidate; shrink the search range based on whether that count exceeds m. O(n log(sum)).',ARRAY['python','java','javascript','go','cpp'],0.25),

('Swiggy Delivery Rank Matrix','kth-smallest-sorted-matrix','Hard','DSA',ARRAY['binary-search','heap','matrix'],'## Problem

A Swiggy dispatch grid has delivery-time estimates where each row and each column is sorted in ascending order. Find the `k`-th **smallest** estimate in the entire grid.','1 ≤ n ≤ 300 | 1 ≤ k ≤ n^2 | -10^9 ≤ matrix[i][j] ≤ 10^9 | rows and columns individually sorted ascending','[{"input": "matrix = [[1,5,9],[10,11,13],[12,13,15]], k = 8", "output": "13", "explanation": "Sorted order is 1,5,9,10,11,12,13,13,15 — the 8th value is 13."}]'::jsonb,'[{"input": "[[1,5,9],[10,11,13],[12,13,15]]\n8", "expected_output": "13", "is_hidden": false}, {"input": "[[-5]]\n1", "expected_output": "-5", "is_hidden": true}]'::jsonb,'Binary search on the VALUE range [matrix[0][0], matrix[n-1][n-1]]. For each candidate value, count how many matrix entries are ≤ it in O(n) by walking from the bottom-left corner; narrow the range until it converges to the answer. O(n log(max-min)).',ARRAY['python','java','javascript','go','cpp'],0.23),

('Amazon India Order Sequence Window','minimum-window-subsequence','Hard','DSA',ARRAY['two-pointers','strings'],'## Problem

Given a warehouse scan log `S` and a required pick sequence `T`, find the **minimum contiguous window** in `S` such that `T` is a **subsequence** of that window (characters of `T` must appear in order within the window, not necessarily consecutively). If no such window exists, return an empty string.','1 ≤ len(S) ≤ 2×10^4 | 1 ≤ len(T) ≤ 100 | S and T consist of lowercase English letters','[{"input": "S = \"abcdebdde\", T = \"bde\"", "output": "\"bcde\"", "explanation": "\"bcde\" contains b, then d, then e in order and is the shortest such window; the later \"bdde\" window is not shorter."}]'::jsonb,'[{"input": "\"abcdebdde\"\n\"bde\"", "expected_output": "\"bcde\"", "is_hidden": false}, {"input": "\"bba\"\n\"ba\"", "expected_output": "\"ba\"", "is_hidden": true}]'::jsonb,'Two-pass two-pointer: scan forward matching T greedily to find a window end, then scan backward from that end to shrink the window''s start to the tightest possible start for that same end. Slide forward and repeat, tracking the global minimum window. O(len(S)·len(T)) worst case.',ARRAY['python','java','javascript','go','cpp'],0.18),

('Yamuna Stepping Stone Crossing','frog-jump','Hard','DSA',ARRAY['dynamic-programming','hash-map'],'## Problem

A frog crosses a river using stones at positions given by sorted, distinct `stones`. It starts on the first stone with a jump of size 0. If its last jump was size `k`, its next jump must be size `k-1`, `k`, or `k+1` (and must be a positive size). Determine if the frog can reach the **last stone**.','2 ≤ stones.length ≤ 2000 | 0 ≤ stones[i] ≤ 2^31-1 | stones[0] == 0, strictly increasing','[{"input": "stones = [0,1,3,5,6,8,12,17]", "output": "true", "explanation": "Jump sequence 1,2,2,1,2,3,4 lands exactly on every stone in order."}, {"input": "stones = [0,1,2,3,4,8,9,11]", "output": "false", "explanation": "The gap from stone 4 to stone 8 is too large to bridge given the jump-size constraint at that point."}]'::jsonb,'[{"input": "[0,1,3,5,6,8,12,17]", "expected_output": "true", "is_hidden": false}, {"input": "[0,1,2,3,4,8,9,11]", "expected_output": "false", "is_hidden": true}]'::jsonb,'DP mapping each stone position to the set of jump sizes that can reach it. For each reachable (stone, lastJump) state, try lastJump-1, lastJump, lastJump+1 and mark the target stone reachable with that new jump size if it exists. O(n^2) worst case.',ARRAY['python','java','javascript','go','cpp'],0.19),

('Britannia Factory Egg Drop Test','super-egg-drop','Hard','DSA',ARRAY['dynamic-programming','binary-search'],'## Problem

Britannia QA has `k` identical eggs and a factory building with `n` floors. There exists a critical floor `f` (0 ≤ f ≤ n) such that an egg dropped from any floor ≤ f survives, and from any floor > f breaks. Find the **minimum number of trial drops**, in the worst case, needed to determine `f` exactly, given optimal strategy.','1 ≤ k ≤ 100 | 1 ≤ n ≤ 10^4','[{"input": "k = 1, n = 2", "output": "2", "explanation": "With only 1 egg you must test floors one at a time from the bottom, worst case 2 drops."}, {"input": "k = 2, n = 6", "output": "3", "explanation": "With 2 eggs, an optimal strategy determines the critical floor within 3 drops worst case."}]'::jsonb,'[{"input": "1\n2", "expected_output": "2", "is_hidden": false}, {"input": "2\n6", "expected_output": "3", "is_hidden": true}]'::jsonb,'Instead of DP on (eggs, floors) directly, DP on (eggs, drops) → maximum floors distinguishable, since that relation is monotonic and invertible: f(k,drops) = f(k-1,drops-1) + f(k,drops-1) + 1. Find the minimum `drops` such that f(k,drops) ≥ n. O(k log n).',ARRAY['python','java','javascript','go','cpp'],0.15),

('Formula E Delhi Race Car Controller','race-car','Hard','DSA',ARRAY['dynamic-programming','bfs'],'## Problem

A race car starts at position 0 with speed +1. Each instruction is `A` (accelerate: position += speed, speed *= 2) or `R` (reverse: speed becomes -1 if currently positive, else +1, position unchanged). Find the **minimum number of instructions** to reach exactly `target`.','1 ≤ target ≤ 10^4','[{"input": "target = 3", "output": "2", "explanation": "\"AA\" takes the car from 0 to 0+1=1 (speed becomes 2) to 1+2=3 (target reached) in 2 instructions."}, {"input": "target = 6", "output": "5", "explanation": "\"AAARA\" reaches exactly 6 in 5 instructions; no shorter sequence exists."}]'::jsonb,'[{"input": "3", "expected_output": "2", "is_hidden": false}, {"input": "6", "expected_output": "5", "is_hidden": true}]'::jsonb,'BFS over reachable (position, speed) states, or DP where dp[t] = min instructions to reach t, built from the two natural candidates: driving exactly to or just past t via n full A-moves then reversing and recursing on the overshoot/undershoot remainder. O(target log target) with memoization.',ARRAY['python','java','javascript','go','cpp'],0.16),

('Byju''s Text Palindrome Prefix Fixer','shortest-palindrome','Hard','DSA',ARRAY['kmp','strings'],'## Problem

Byju''s autocorrect can only **prepend** characters to a string `s` (never insert in the middle or append at the end). Find the **shortest palindrome** obtainable this way and return it.','0 ≤ len(s) ≤ 5×10^4 | s consists of lowercase English letters only','[{"input": "s = \"aacecaaa\"", "output": "\"aaacecaaa\"", "explanation": "Prepending a single \"a\" makes the whole string a palindrome, which is the minimum possible."}, {"input": "s = \"abcd\"", "output": "\"dcbabcd\"", "explanation": "No prefix of \"abcd\" longer than \"a\" is itself a palindrome, so nearly the whole reversed string must be prepended."}]'::jsonb,'[{"input": "\"aacecaaa\"", "expected_output": "\"aaacecaaa\"", "is_hidden": false}, {"input": "\"abcd\"", "expected_output": "\"dcbabcd\"", "is_hidden": true}]'::jsonb,'Build the string s + "#" + reverse(s) and compute its KMP failure function. The failure value at the last position gives the length of the longest palindromic PREFIX of s; prepend the reverse of the remaining suffix. O(n).',ARRAY['python','java','javascript','go','cpp'],0.17),

('Kerala Backwaters Island Formation Tracker','number-of-islands-ii','Hard','DSA',ARRAY['union-find','matrix'],'## Problem

Kerala backwaters land reclamation adds one plot of land at a time to an `m x n` water grid, given as a sequence of `positions`. After each addition, report the **current number of islands** (a land plot connects to its 4-directional land neighbors). Return the running count after each addition, in order.','1 ≤ m,n ≤ 10^4 | 1 ≤ positions.length ≤ 10^4 | m*n ≤ 10^4','[{"input": "m = 3, n = 3, positions = [[0,0],[0,1],[1,2],[2,1]]", "output": "[1,1,2,3]", "explanation": "First two additions are adjacent (still 1 island); the third is isolated (2 islands); the fourth is isolated from both existing groups (3 islands)."}]'::jsonb,'[{"input": "3\n3\n[[0,0],[0,1],[1,2],[2,1]]", "expected_output": "[1,1,2,3]", "is_hidden": false}, {"input": "1\n1\n[[0,0]]", "expected_output": "[1]", "is_hidden": true}]'::jsonb,'Union-Find (disjoint set) over cell indices. On each addition, mark the cell as land, increment the island count by 1, then union with any already-land 4-directional neighbor, decrementing the count by 1 per successful union. O(positions.length · α(mn)).',ARRAY['python','java','javascript','go','cpp'],0.20),

('ISRO Terrain Elevation Trekking Path','longest-increasing-path-matrix','Hard','DSA',ARRAY['dfs','dynamic-programming','matrix'],'## Problem

Given an `m x n` integer `matrix` of ISRO satellite elevation readings, find the length of the **longest strictly increasing path** you can trek, moving 4-directionally (no revisiting, and no wraparound).','1 ≤ m,n ≤ 200 | 0 ≤ matrix[i][j] ≤ 2^31-1','[{"input": "matrix = [[9,9,4],[6,6,8],[2,1,1]]", "output": "4", "explanation": "The path 1 -> 2 -> 6 -> 9 (bottom-left upward) has length 4 and is the longest strictly increasing path."}]'::jsonb,'[{"input": "[[9,9,4],[6,6,8],[2,1,1]]", "expected_output": "4", "is_hidden": false}, {"input": "[[1]]", "expected_output": "1", "is_hidden": true}]'::jsonb,'DFS with memoization: for each cell, the longest increasing path starting there is 1 + max over strictly-greater 4-directional neighbors of their memoized longest path. Each cell computed once. O(mn).',ARRAY['python','java','javascript','go','cpp'],0.21)

ON CONFLICT (slug) DO NOTHING;
