-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║   CAPABILIO — arena_missions table (run if missing)             ║
-- ║   Paste into Supabase Dashboard → SQL Editor → Run              ║
-- ╚═══════════════════════════════════════════════════════════════════╝

-- arena_missions: stores per-user daily mission slots (generated by AI)
CREATE TABLE IF NOT EXISTS arena_missions (
  id          TEXT PRIMARY KEY,          -- "{uid}_slot_{index}"
  user_id     UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  slot_index  INT NOT NULL,
  slot_data   JSONB NOT NULL DEFAULT '{}',
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_arena_missions_user ON arena_missions(user_id, slot_index);

-- RLS: each user owns their own slots
ALTER TABLE arena_missions ENABLE ROW LEVEL SECURITY;
-- DROP first so re-running the script is safe
DROP POLICY IF EXISTS "arena_missions_own" ON arena_missions;
CREATE POLICY "arena_missions_own"
  ON arena_missions FOR ALL TO authenticated
  USING (user_id = auth.uid());

-- ── arena_submissions: ensure required columns exist ─────────────────────────
-- Run this to add any missing columns to the submissions table
ALTER TABLE arena_submissions
  ADD COLUMN IF NOT EXISTS domain_key     TEXT,
  ADD COLUMN IF NOT EXISTS task_id        TEXT,
  ADD COLUMN IF NOT EXISTS title          TEXT,
  ADD COLUMN IF NOT EXISTS difficulty     TEXT DEFAULT 'Medium',
  ADD COLUMN IF NOT EXISTS domain         TEXT,
  ADD COLUMN IF NOT EXISTS elo_delta      INT  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS grade          TEXT,
  ADD COLUMN IF NOT EXISTS summary        TEXT,
  ADD COLUMN IF NOT EXISTS strengths      TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS improvements   TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS scenario       TEXT,
  ADD COLUMN IF NOT EXISTS submitted_answer TEXT;

-- ── arena_leaderboard: ensure snake_case columns ─────────────────────────────
ALTER TABLE arena_leaderboard
  ADD COLUMN IF NOT EXISTS display_name TEXT,
  ADD COLUMN IF NOT EXISTS tasks_done   INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS elo_delta    INT DEFAULT 0;

-- ── profiles: add arena tracking columns if missing ──────────────────────────
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS last_arena_task_at  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS arena_last_active   TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS skill_coverage      JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS recent_skills       TEXT[] DEFAULT '{}';

DO $$ BEGIN
  RAISE NOTICE '✅ Arena missing-tables migration complete.';
END $$;
