-- Capabilio profiles table migration
-- Run this in Supabase SQL Editor → New query → Run

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS "displayName"       text,
  ADD COLUMN IF NOT EXISTS "username"          text,
  ADD COLUMN IF NOT EXISTS "name"              text,
  ADD COLUMN IF NOT EXISTS "eloRating"         integer     DEFAULT 400,
  ADD COLUMN IF NOT EXISTS "baseElo"           integer     DEFAULT 400,
  ADD COLUMN IF NOT EXISTS "initialElo"        integer     DEFAULT 400,
  ADD COLUMN IF NOT EXISTS "keyword"           text,
  ADD COLUMN IF NOT EXISTS "path"              text,
  ADD COLUMN IF NOT EXISTS "onboardingComplete" boolean    DEFAULT false,
  ADD COLUMN IF NOT EXISTS "assessmentType"    text,
  ADD COLUMN IF NOT EXISTS "assessmentScore"   integer,
  ADD COLUMN IF NOT EXISTS "assessmentTotal"   integer,
  ADD COLUMN IF NOT EXISTS "score"             text,
  ADD COLUMN IF NOT EXISTS "jobReadiness"      integer     DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "skillGraph"        jsonb       DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "strengths"         jsonb       DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "weakAreas"         jsonb       DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "profileSummary"    text,
  ADD COLUMN IF NOT EXISTS "experiences"       jsonb       DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "resumeProjects"    jsonb       DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "vaultFiles"        jsonb       DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "resumeFileName"    text,
  ADD COLUMN IF NOT EXISTS "resumeUploadedAt"  text,
  ADD COLUMN IF NOT EXISTS "eloHistory"        jsonb       DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "arenaHistory"      jsonb       DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "arenaCompleted"    integer     DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "arenaStreak"       integer     DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "arenaLastActive"   text,
  ADD COLUMN IF NOT EXISTS "eloDecayDate"      text,
  ADD COLUMN IF NOT EXISTS "eloDecayToday"     integer     DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "arenaSubmissions"  jsonb       DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "coverPosition"     text,
  ADD COLUMN IF NOT EXISTS "avatarUrl"         text,
  ADD COLUMN IF NOT EXISTS "githubUsername"    text,
  ADD COLUMN IF NOT EXISTS "subscription"      text        DEFAULT 'free';
