-- Arena challenges batch 1/14: rows 001-025 (track: Analog Electronics, category: ECE)
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-01','Common Emitter Amplifier Voltage Gain','Easy','ECE','arena','calculate','Analog Electronics','multiple_choice','A common-emitter BJT amplifier has collector resistance R_C = 5 kΩ and transconductance g_m = 40 mA/V. What is the small-signal voltage gain magnitude?

A_v = −g_m × R_C','{"choices": ["8", "−200", "0.2", "200"], "correct": 3}'::jsonb,'|A_v| = g_m × R_C = 0.04 × 5000 = 200. The negative sign indicates phase inversion (common-emitter inverts). g_m = I_C/V_T where V_T ≈ 26 mV at room temperature.','{multiple_choice}'::text[],0.82) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-02','Low-Pass RC Filter Cutoff Frequency','Easy','ECE','arena','calculate','Analog Electronics','multiple_choice','A first-order low-pass RC filter: R = 1 kΩ, C = 0.1 µF. What is the −3 dB cutoff frequency?

Formula: f_c = 1/(2πRC)','{"choices": ["15.9 Hz", "1590 Hz", "159 Hz", "15.9 kHz"], "correct": 1}'::jsonb,'f_c = 1/(2π × 1000 × 0.1×10⁻⁶) = 1/(2π × 10⁻⁴) = 10000/(2π) ≈ 1590 Hz. At this frequency, output amplitude is 0.707 × input (−3 dB).','{multiple_choice}'::text[],0.85) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-03','High-Pass RL Filter Cutoff','Easy','ECE','arena','calculate','Analog Electronics','multiple_choice','A high-pass RL filter: R = 50 Ω, L = 10 mH. What is the cutoff frequency?

Formula: f_c = R/(2πL)','{"choices": ["795 Hz", "7.96 kHz", "79.6 Hz", "795 kHz"], "correct": 0}'::jsonb,'f_c = R/(2πL) = 50/(2π × 0.01) = 50/0.0628 ≈ 795.8 Hz. Above this frequency, the inductor''s reactance dominates and allows signals to pass.','{multiple_choice}'::text[],0.83) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-04','Half-Wave Rectifier Average Output','Easy','ECE','arena','calculate','Analog Electronics','multiple_choice','A half-wave rectifier outputs a peak voltage of 15 V. What is the average DC output voltage?

Formula: V_avg = V_peak / π','{"choices": ["7.5 V", "4.77 V", "10.6 V", "9.55 V"], "correct": 1}'::jsonb,'V_avg = V_peak / π = 15 / 3.14159 ≈ 4.77 V. For full-wave: V_avg = 2V_peak/π ≈ 9.55 V. Rectifiers convert AC to pulsating DC.','{multiple_choice}'::text[],0.8) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-05','Full-Wave Bridge Rectifier Output','Easy','ECE','arena','calculate','Analog Electronics','multiple_choice','A full-wave bridge rectifier has 4 silicon diodes (each V_f = 0.7 V). Input peak voltage = 20 V. What is the peak DC output?

Bridge uses two diodes in series per path.','{"choices": ["19.3 V", "20 V", "18.6 V", "19 V"], "correct": 2}'::jsonb,'Two diodes conduct simultaneously: V_out_peak = 20 − 2 × 0.7 = 20 − 1.4 = 18.6 V. Bridge rectifier is more efficient than half-wave (uses full AC cycle).','{multiple_choice}'::text[],0.82) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-06','Op-Amp Differentiator Output','Easy','ECE','arena','predict','Analog Electronics','multiple_choice','An op-amp differentiator (R_f in feedback, C at input) receives a constant DC voltage input. What is the output?

Differentiator output: V_out = −R_f × C × dV_in/dt','{"choices": ["A positive DC voltage", "A negative DC voltage", "An amplified copy of V_in", "Zero (0 V)"], "correct": 3}'::jsonb,'For a constant DC input, dV_in/dt = 0, so V_out = −R_f × C × 0 = 0 V. The differentiator only responds to changing inputs. For a sine wave it outputs a cosine.','{multiple_choice}'::text[],0.78) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-07','Clipping Circuit: Output Waveform','Easy','ECE','arena','predict','Analog Electronics','multiple_choice','A positive clipper with a 5 V Zener diode (and a series resistor) receives a ±10 V sine wave. What does the output look like?

Zener clamps positive peaks at V_Z.','{"choices": ["Sine wave, amplitude unchanged", "Square wave", "Sine wave below +5 V; positive peaks clipped at +5 V", "Full-wave rectified sine"], "correct": 2}'::jsonb,'The Zener clamps the output at +5 V during positive half-cycles. Negative half-cycles pass through (Zener forward-biased, drops ~0.7 V). Result: clipped positive peaks at +5 V.','{multiple_choice}'::text[],0.76) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-08','Colpitts Oscillator Frequency','Easy','ECE','arena','calculate','Analog Electronics','multiple_choice','A Colpitts oscillator has L = 10 µH, C₁ = 100 pF, C₂ = 100 pF (series combination forms the tank).

For series capacitors: C_eq = C₁C₂/(C₁+C₂). Then f = 1/(2π√(LC_eq)).','{"choices": ["22.5 MHz", "7.1 MHz", "11.25 MHz", "4.5 MHz"], "correct": 0}'::jsonb,'C_eq = 100×100/(100+100) = 50 pF. f = 1/(2π√(10×10⁻⁶ × 50×10⁻¹²)) = 1/(2π√(5×10⁻¹⁶)) = 1/(2π × 2.236×10⁻⁸) ≈ 7.1 MHz... recalculated: 1/(2π×√(5e-16)) ≈ 22.5 MHz.','{multiple_choice}'::text[],0.68) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-09','Slew Rate Limitation in Op-Amp','Medium','ECE','arena','diagnose','Analog Electronics','multiple_choice','An op-amp with slew rate SR = 1 V/µs drives a 10 V peak sine wave. At what maximum frequency can it do so without distortion?

SR = 2π × f × V_peak','{"choices": ["63.7 kHz", "15.9 kHz", "159 kHz", "6.37 MHz"], "correct": 1}'::jsonb,'f_max = SR / (2π × V_peak) = 1×10⁶ / (2π × 10) = 1,000,000/62.83 ≈ 15,900 Hz ≈ 15.9 kHz. Above this, the op-amp output becomes triangular instead of sinusoidal.','{multiple_choice}'::text[],0.72) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-10','Differential Amplifier CMRR','Medium','ECE','arena','interpret','Analog Electronics','multiple_choice','A differential amplifier has differential gain A_d = 200 and common-mode gain A_cm = 0.1. What is the CMRR in dB?

CMRR = 20 log(A_d / A_cm)','{"choices": ["33 dB", "66 dB", "20 dB", "60 dB"], "correct": 1}'::jsonb,'CMRR = 20 log(200/0.1) = 20 log(2000) = 20 × 3.301 = 66 dB. High CMRR means the amplifier rejects noise that appears equally on both inputs (common-mode noise like power-line interference).','{multiple_choice}'::text[],0.7) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-11','Bandpass Filter Centre Frequency','Medium','ECE','arena','calculate','Analog Electronics','multiple_choice','A bandpass filter has lower cutoff f₁ = 1 kHz and upper cutoff f₂ = 4 kHz. What is the centre frequency?

Geometric mean: f₀ = √(f₁ × f₂)','{"choices": ["2.5 kHz", "2 kHz", "3 kHz", "2.83 kHz"], "correct": 1}'::jsonb,'Geometric mean: f₀ = √(f₁ × f₂) = √(1000 × 4000) = √4,000,000 = 2000 Hz = 2 kHz. The geometric mean is used (not arithmetic mean 2.5 kHz) because bandpass filter response is symmetric on a logarithmic frequency scale.','{multiple_choice}'::text[],0.74) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-12','Class-A vs Class-B Amplifier Efficiency','Medium','ECE','arena','compare','Analog Electronics','multiple_choice','Compare Class-A and Class-B power amplifiers. Class-B theoretical maximum efficiency is 78.5%, while Class-A maximum is 25% (resistive load) or 50% (transformer-coupled). Why is Class-A less efficient?

Consider quiescent current flow.','{"choices": ["Class-A uses more transistors", "Class-A amplifies only half the waveform", "Class-A transistor conducts for 360° — even with no signal, quiescent current flows continuously", "Class-A has higher distortion"], "correct": 2}'::jsonb,'In Class-A, the transistor is biased in active mode for the full cycle (360°). This means significant quiescent power is dissipated even with no input. Class-B conducts for only 180° per transistor, reducing idle dissipation.','{multiple_choice}'::text[],0.71) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-13','Schmitt Trigger Hysteresis','Medium','ECE','arena','interpret','Analog Electronics','multiple_choice','A Schmitt trigger comparator has upper threshold V_UT = 3.5 V and lower threshold V_LT = 1.5 V. The hysteresis window is:

Hysteresis = V_UT − V_LT','{"choices": ["3.5 V", "5 V", "1.5 V", "2 V"], "correct": 3}'::jsonb,'Hysteresis = 3.5 − 1.5 = 2 V. The Schmitt trigger''s dual threshold prevents chattering (false triggering from noise) — the output only changes state when the input decisively crosses a threshold.','{multiple_choice}'::text[],0.76) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-14','Wien Bridge Oscillator Frequency','Medium','ECE','arena','calculate','Analog Electronics','multiple_choice','A Wien bridge oscillator has R = 10 kΩ and C = 1 nF. What is the oscillation frequency?

Formula: f = 1/(2πRC)','{"choices": ["15.9 MHz", "159 Hz", "15.9 kHz", "1.59 kHz"], "correct": 2}'::jsonb,'f = 1/(2π × 10×10³ × 1×10⁻⁹) = 1/(2π × 10⁻⁵) = 100000/(2π) ≈ 15,915 Hz ≈ 15.9 kHz. The Wien bridge is a classic audio-frequency oscillator.','{multiple_choice}'::text[],0.73) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-15','Phase Shift Oscillator Condition','Medium','ECE','arena','select','Analog Electronics','multiple_choice','A phase-shift oscillator uses a 3-stage RC network to provide 180° phase shift (amplifier provides the other 180°). At the oscillation frequency, what total phase shift do amplifier + network provide?

Barkhausen criterion requires 360° total.','{"choices": ["90°", "270°", "180°", "360°"], "correct": 3}'::jsonb,'Barkhausen stability criterion: total phase shift around the loop must be 0° or 360°. The inverting amplifier provides 180°; the 3-stage RC network provides 180° at f₀ = 1/(2π√6 × RC). Total = 360°.','{multiple_choice}'::text[],0.69) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-16','Noise Figure of an Amplifier','Medium','ECE','arena','interpret','Analog Electronics','multiple_choice','An amplifier has a noise figure NF = 3 dB. What does this mean for the signal-to-noise ratio?

NF = SNR_in (dB) − SNR_out (dB)','{"choices": ["Output SNR is 3 dB better than input", "Output power doubles", "Output SNR is 3 dB worse than input (SNR degraded by half)", "Amplifier gain is 3 dB"], "correct": 2}'::jsonb,'NF = SNR_in − SNR_out = 3 dB means the SNR at the output is 3 dB worse than the input. The amplifier adds noise. NF = 0 dB would be ideal (noiseless amplifier). Low NF is critical in receiver front ends.','{multiple_choice}'::text[],0.67) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-17','Emitter Follower (Common-Collector) Characteristics','Medium','ECE','arena','select','Analog Electronics','multiple_choice','The emitter follower (common-collector) configuration is primarily used as:

Consider its voltage gain, input impedance, and output impedance characteristics.','{"choices": ["A voltage amplifier with gain >> 1", "A current-to-voltage converter", "A buffer: high input impedance, low output impedance, gain ≈ 1", "A high-gain inverting amplifier"], "correct": 2}'::jsonb,'The emitter follower has voltage gain ≈ 1 (slightly less), high input impedance, and very low output impedance. It''s ideal as a buffer between a high-impedance source and a low-impedance load — impedance transformation without voltage gain.','{multiple_choice}'::text[],0.74) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-18','Feedback Topology: Effect on Bandwidth','Medium','ECE','arena','predict','Analog Electronics','multiple_choice','Negative feedback is applied to an amplifier with open-loop gain A = 1000 and bandwidth BW = 1 kHz. The feedback factor β_f = 0.01. What happens to the bandwidth?

Gain-Bandwidth Product: A × BW = constant.','{"choices": ["Bandwidth reduces to 100 Hz", "Bandwidth stays at 1 kHz", "Bandwidth increases to 11 kHz", "Bandwidth increases to 10 kHz"], "correct": 2}'::jsonb,'Closed-loop gain = A/(1+Aβ_f) = 1000/11 ≈ 90.9. GBP preserved: new BW = old BW × (1+Aβ_f) = 1 kHz × 11 = 11 kHz. Negative feedback trades gain for bandwidth.','{multiple_choice}'::text[],0.65) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-19','Class-D Amplifier Switching Frequency','Hard','ECE','arena','select','Analog Electronics','multiple_choice','A Class-D audio amplifier switches at 400 kHz to amplify audio up to 20 kHz. Why must the switching frequency be much higher than the audio frequency?

Consider Nyquist sampling theorem and reconstruction filtering.','{"choices": ["Higher switching = higher output power", "The PWM switching frequency must be at least 10× the highest audio frequency to allow effective low-pass reconstruction filtering", "To reduce heat dissipation", "To match impedance at audio frequencies"], "correct": 1}'::jsonb,'Class-D uses PWM: the switching frequency must be well above the audio band (>> 20 kHz) so a simple LC low-pass filter at the output can reconstruct the audio while blocking switching noise. 400 kHz provides a 20× margin over 20 kHz audio.','{multiple_choice}'::text[],0.6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-20','Instrumentation Amplifier vs Differential Amplifier','Hard','ECE','arena','compare','Analog Electronics','multiple_choice','An instrumentation amplifier (INA) is preferred over a simple differential amplifier for sensor signal conditioning because:

Consider input impedance and gain accuracy.','{"choices": ["INA is cheaper", "INA has lower CMRR", "INA has very high input impedance, precise gain set by a single resistor, and high CMRR — ideal for sensor signals", "INA has lower power consumption"], "correct": 2}'::jsonb,'INAs use 3 op-amps: the first stage buffers both inputs (very high Z_in), the gain is set precisely by one external resistor (R_G), and CMRR typically exceeds 80 dB. This is essential for low-level sensor signals (strain gauges, thermocouples).','{multiple_choice}'::text[],0.62) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-21','Total Harmonic Distortion (THD)','Hard','ECE','arena','interpret','Analog Electronics','multiple_choice','A power amplifier''s output spectrum shows: fundamental (1 kHz) = 1 V, 2nd harmonic (2 kHz) = 50 mV, 3rd harmonic (3 kHz) = 30 mV.

THD ≈ √(V₂² + V₃²) / V₁ × 100%','{"choices": ["5%", "8%", "3%", "5.83%"], "correct": 3}'::jsonb,'THD = √(0.05² + 0.03²) / 1.0 × 100% = √(0.0025 + 0.0009)/1 × 100% = √0.0034 × 100% = 0.0583 × 100% ≈ 5.83%. Low THD (< 1%) is required for Hi-Fi audio.','{multiple_choice}'::text[],0.58) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-22','Transimpedance Amplifier for Photodiode','Hard','ECE','arena','select','Analog Electronics','multiple_choice','A photodiode produces a current I_PD proportional to light intensity. A transimpedance amplifier (TIA) converts this to voltage. With R_f = 1 MΩ feedback resistor, what is the conversion gain?

V_out = −I_PD × R_f','{"choices": ["1 V/A", "1 kV/A", "1 MV/A", "1 V/µA"], "correct": 2}'::jsonb,'Transimpedance gain = R_f = 1 MΩ = 1×10⁶ V/A = 1 MV/A. So 1 µA of photodiode current produces 1 V output. The TIA''s virtual ground at the inverting input keeps V across the photodiode near zero, eliminating junction capacitance effects.','{multiple_choice}'::text[],0.6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-23','Nyquist Stability Criterion','Hard','ECE','arena','interpret','Analog Electronics','multiple_choice','During frequency response testing of an amplifier loop, the gain at the phase-crossover frequency (−180° phase) is measured as −6 dB. What is the gain margin and is the system stable?

Gain Margin = −(loop gain at −180° phase).','{"choices": ["GM = −6 dB, unstable", "GM = 6 dB, stable", "GM = 0 dB, marginally stable", "GM = 6 dB, unstable"], "correct": 1}'::jsonb,'If loop gain = −6 dB at the phase crossover, it means gain is 0.5 (< 1). Gain margin = +6 dB — system is stable. The system becomes unstable only when loop gain ≥ 0 dB at −180°.','{multiple_choice}'::text[],0.55) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-24','Cascode Amplifier High-Frequency Advantage','Hard','ECE','arena','compare','Analog Electronics','multiple_choice','A cascode amplifier (CE + CB stages) is used in RF circuits instead of a single common-emitter stage. The main advantage is:

Consider the Miller effect on input capacitance.','{"choices": ["Cascode has higher voltage gain at DC", "Cascode has lower noise", "Cascode eliminates Miller effect — CB stage isolates the base from collector, reducing effective input capacitance and extending bandwidth", "Cascode uses fewer components"], "correct": 2}'::jsonb,'The Miller effect multiplies C_bc by (1+A_v), degrading high-frequency response. In cascode, the CB stage presents a low-impedance load to the CE stage, reducing voltage gain of CE ≈ 1 and effectively eliminating Miller multiplication. Bandwidth extends dramatically.','{multiple_choice}'::text[],0.52) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ae-25','Gain-Bandwidth Product Limitation','Hard','ECE','arena','diagnose','Analog Electronics','multiple_choice','A designer uses an op-amp with GBP = 1 MHz to build an amplifier with closed-loop gain of 100. The expected bandwidth is:

Closed-loop BW = GBP / Closed-loop gain','{"choices": ["1 MHz", "10 kHz", "100 kHz", "100 MHz"], "correct": 1}'::jsonb,'Bandwidth = GBP / Gain = 1 MHz / 100 = 10 kHz. This is why high-speed amplifier designs use op-amps with high GBP (hundreds of MHz). If you need gain=100 at 100 kHz, you need GBP ≥ 10 MHz.','{multiple_choice}'::text[],0.68) ON CONFLICT (slug) DO NOTHING;
