-- Arena challenges batch 2/14: rows 026-050 (track: Circuit Analysis, category: ECE)
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-01','Ohm''s Law: Voltage Across a Resistor','Easy','ECE','arena','calculate','Circuit Analysis','multiple_choice','A 100 Ω resistor has 0.5 A flowing through it. What is the voltage across it?

Apply Ohm''s Law: V = I × R','{"choices": ["50 V", "200 V", "0.005 V", "5 V"], "correct": 0}'::jsonb,'V = I × R = 0.5 A × 100 Ω = 50 V. Ohm''s Law directly relates voltage, current, and resistance.','{multiple_choice}'::text[],0.88) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-02','Series Circuit: Total Resistance','Easy','ECE','arena','calculate','Circuit Analysis','multiple_choice','Three resistors — 10 Ω, 20 Ω, and 30 Ω — are connected in series. What is the total resistance?

Hint: Series resistors add directly.','{"choices": ["5.45 Ω", "10 Ω", "60 Ω", "6 Ω"], "correct": 2}'::jsonb,'For series resistors: R_total = R₁ + R₂ + R₃ = 10 + 20 + 30 = 60 Ω. Current is the same through all; voltage divides.','{multiple_choice}'::text[],0.9) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-03','Parallel Circuit: Equivalent Resistance','Easy','ECE','arena','calculate','Circuit Analysis','multiple_choice','Two resistors — 6 Ω and 3 Ω — are connected in parallel. What is the equivalent resistance?

Hint: 1/R_eq = 1/R₁ + 1/R₂','{"choices": ["9 Ω", "4.5 Ω", "0.5 Ω", "2 Ω"], "correct": 3}'::jsonb,'1/R_eq = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 → R_eq = 2 Ω. Parallel resistance is always less than the smallest resistor.','{multiple_choice}'::text[],0.88) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-04','Power Dissipation in a Resistor','Easy','ECE','arena','calculate','Circuit Analysis','multiple_choice','A 470 Ω resistor carries 20 mA. How much power does it dissipate?

Use: P = I²R','{"choices": ["9.4 W", "0.188 mW", "0.188 W", "23.5 W"], "correct": 2}'::jsonb,'P = I²R = (0.02)² × 470 = 0.0004 × 470 = 0.188 W. Always convert mA to A before applying the formula.','{multiple_choice}'::text[],0.85) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-05','KVL: Voltage Across One Resistor','Easy','ECE','arena','select','Circuit Analysis','multiple_choice','A 12 V source drives a series circuit with a 2 Ω and 4 Ω resistor. Using Kirchhoff''s Voltage Law, what is the voltage across the 4 Ω resistor?

KVL: the sum of voltages around a loop equals zero.','{"choices": ["4 V", "3 V", "6 V", "8 V"], "correct": 3}'::jsonb,'Total current: I = 12 / (2+4) = 2 A. Voltage across 4 Ω: V = 2 × 4 = 8 V. KVL confirms: 12 = 4 + 8 ✓.','{multiple_choice}'::text[],0.87) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-06','KCL at a Node','Easy','ECE','arena','select','Circuit Analysis','multiple_choice','At a node, two currents enter: 3 A and 5 A. Two currents leave: 4 A and I₂. Find I₂.

KCL: Sum of currents entering = Sum of currents leaving.','{"choices": ["2 A", "6 A", "12 A", "4 A"], "correct": 3}'::jsonb,'KCL: 3 + 5 = 4 + I₂ → 8 = 4 + I₂ → I₂ = 4 A. Kirchhoff''s Current Law is conservation of charge at a node.','{multiple_choice}'::text[],0.89) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-07','Voltage Divider Rule','Easy','ECE','arena','calculate','Circuit Analysis','multiple_choice','A voltage divider: R₁ = 10 kΩ, R₂ = 40 kΩ, supply = 25 V. What is the voltage across R₂?

Formula: V_R2 = V_s × R₂ / (R₁ + R₂)','{"choices": ["5 V", "12.5 V", "6.25 V", "20 V"], "correct": 3}'::jsonb,'V_R2 = 25 × 40k / (10k + 40k) = 25 × 0.8 = 20 V. The larger resistor takes the larger fraction of voltage in a divider.','{multiple_choice}'::text[],0.86) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-08','Current Divider Rule','Easy','ECE','arena','predict','Circuit Analysis','multiple_choice','Two parallel resistors: R₁ = 4 Ω, R₂ = 12 Ω. Total entering current = 8 A. How much flows through R₁?

Formula: I₁ = I_total × R₂ / (R₁ + R₂)','{"choices": ["2 A", "4 A", "6 A", "8 A"], "correct": 2}'::jsonb,'I₁ = 8 × 12 / (4 + 12) = 96 / 16 = 6 A. In a current divider, more current flows through the smaller resistor.','{multiple_choice}'::text[],0.84) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-09','Thevenin Resistance from Measurements','Medium','ECE','arena','diagnose','Circuit Analysis','multiple_choice','A circuit''s open-circuit terminal voltage is 8 V. When a 4 Ω load is connected, terminal voltage drops to 6 V.

Determine the Thevenin resistance (R_th).','{"choices": ["4 Ω", "2 Ω", "0.75 Ω", "1.33 Ω"], "correct": 3}'::jsonb,'Load current: I_L = 6/4 = 1.5 A. Voltage drop across R_th = 8 − 6 = 2 V. R_th = 2/1.5 = 1.33 Ω. This is the standard two-measurement Thevenin method.','{multiple_choice}'::text[],0.72) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-10','Norton Short-Circuit Current','Medium','ECE','arena','calculate','Circuit Analysis','multiple_choice','A network has V_th = 12 V and R_th = 3 Ω. What is the Norton equivalent short-circuit current (I_N)?

Relationship: I_N = V_th / R_th','{"choices": ["36 A", "9 A", "0.25 A", "4 A"], "correct": 3}'::jsonb,'I_N = V_th / R_th = 12 / 3 = 4 A. The Norton current equals the current that flows when you short-circuit the output terminals.','{multiple_choice}'::text[],0.78) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-11','Maximum Power Transfer Theorem','Medium','ECE','arena','select','Circuit Analysis','multiple_choice','A source has internal resistance 50 Ω. For maximum power transfer to the load, R_L should equal:

Maximum Power Transfer Theorem applies when R_L = R_source.','{"choices": ["0 Ω", "25 Ω", "100 Ω", "50 Ω"], "correct": 3}'::jsonb,'Maximum power is transferred when R_L = R_th (source internal resistance) = 50 Ω. At this point, 50% of total power goes to the load.','{multiple_choice}'::text[],0.8) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-12','Superposition Principle','Medium','ECE','arena','predict','Circuit Analysis','multiple_choice','Two voltage sources act on a circuit. Source V₁ alone produces 3 A in branch X (left to right). Source V₂ alone produces 1 A in branch X (left to right). Using superposition, what is the actual current in branch X?','{"choices": ["2 A", "3 A", "1 A", "4 A"], "correct": 3}'::jsonb,'By superposition: I_total = I₁ + I₂ = 3 + 1 = 4 A (same direction, so add). If currents were opposing, you would subtract.','{multiple_choice}'::text[],0.75) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-13','Source Transformation','Medium','ECE','arena','select','Circuit Analysis','multiple_choice','A 12 V voltage source in series with a 4 Ω resistor. What is the equivalent current source representation?

Formula: I_s = V_s / R','{"choices": ["3 A parallel with 12 Ω", "48 A parallel with 4 Ω", "0.33 A parallel with 4 Ω", "3 A parallel with 4 Ω"], "correct": 3}'::jsonb,'I_s = V/R = 12/4 = 3 A. The resistor value stays the same (4 Ω) but changes from series to parallel. Source transformation preserves terminal behaviour.','{multiple_choice}'::text[],0.73) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-14','Mesh Analysis: Solving Loop Currents','Medium','ECE','arena','calculate','Circuit Analysis','multiple_choice','Two mesh equations: 6I₁ − 2I₂ = 12 and −2I₁ + 5I₂ = 0. Solve for mesh current I₁.

Hint: Substitute I₂ from the second equation into the first.','{"choices": ["2.0 A", "3.0 A", "1.8 A", "2.31 A"], "correct": 3}'::jsonb,'From eq2: I₂ = 2I₁/5. Substitute: 6I₁ − 4I₁/5 = 12 → (26/5)I₁ = 12 → I₁ = 60/26 ≈ 2.31 A. Mesh analysis uses KVL around each loop.','{multiple_choice}'::text[],0.68) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-15','Nodal Analysis: Node Voltage','Medium','ECE','arena','calculate','Circuit Analysis','multiple_choice','Node V₁ connects to a 10 V source through a 2 Ω resistor and to ground through a 5 Ω resistor. Applying KCL at V₁:

(10 − V₁)/2 = V₁/5. Solve for V₁.','{"choices": ["5.0 V", "6.67 V", "8.0 V", "7.14 V"], "correct": 3}'::jsonb,'(10 − V₁)/2 = V₁/5 → 5(10 − V₁) = 2V₁ → 50 = 7V₁ → V₁ = 50/7 ≈ 7.14 V. Nodal analysis uses KCL at every non-reference node.','{multiple_choice}'::text[],0.7) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-16','Wheatstone Bridge Balance Condition','Medium','ECE','arena','calculate','Circuit Analysis','multiple_choice','A Wheatstone bridge has R₁ = 100 Ω, R₂ = 200 Ω, R₃ = 300 Ω. For the bridge to be balanced (galvanometer reads 0), find R₄.

Balance condition: R₁/R₂ = R₃/R₄','{"choices": ["100 Ω", "150 Ω", "400 Ω", "600 Ω"], "correct": 3}'::jsonb,'Balance condition: R₄ = R₂ × R₃ / R₁ = 200 × 300 / 100 = 600 Ω. When balanced, no current flows through the galvanometer.','{multiple_choice}'::text[],0.74) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-17','RC Circuit: Time Constant','Medium','ECE','arena','calculate','Circuit Analysis','multiple_choice','An RC circuit has R = 10 kΩ and C = 100 µF. What is the time constant τ, and when does the capacitor reach 63.2% of supply voltage?

Formula: τ = RC','{"choices": ["τ = 100 ms, t = 100 ms", "τ = 10 s, t = 10 s", "τ = 10 ms, t = 10 ms", "τ = 1 s, t = 1 s"], "correct": 3}'::jsonb,'τ = RC = 10×10³ × 100×10⁻⁶ = 1 s. After one time constant (1 s), the capacitor is at 63.2% of final voltage. This is the natural exponential charging characteristic.','{multiple_choice}'::text[],0.76) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-18','RL Circuit: Time to Reach 86.5%','Medium','ECE','arena','predict','Circuit Analysis','multiple_choice','An RL circuit has L = 200 mH and R = 100 Ω. What is the time constant, and how long to reach 86.5% of steady-state current?

For RL: τ = L/R. At t = 2τ, current ≈ 86.5%.','{"choices": ["τ = 20 ms, t = 40 ms", "τ = 500 ms, t = 1 s", "τ = 200 ms, t = 400 ms", "τ = 2 ms, t = 4 ms"], "correct": 3}'::jsonb,'τ = L/R = 0.2/100 = 2 ms. 86.5% corresponds to 2τ = 4 ms. The RL circuit''s time constant governs how quickly it responds to step changes.','{multiple_choice}'::text[],0.71) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-19','LC Resonant Frequency','Medium','ECE','arena','calculate','Circuit Analysis','multiple_choice','An LC circuit has L = 25 mH and C = 40 µF. What is its resonant frequency f₀?

Formula: f₀ = 1 / (2π√(LC))','{"choices": ["503 Hz", "100 Hz", "1000 Hz", "159 Hz"], "correct": 3}'::jsonb,'f₀ = 1/(2π√(0.025 × 40×10⁻⁶)) = 1/(2π × 0.001) = 1/(6.283×10⁻³) ≈ 159 Hz. At resonance, inductive and capacitive reactances cancel.','{multiple_choice}'::text[],0.69) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-20','Mutual Inductance and Coupling Coefficient','Hard','ECE','arena','calculate','Circuit Analysis','multiple_choice','Two coupled inductors: L₁ = 4 H, L₂ = 9 H, coupling coefficient k = 0.5.

Find the mutual inductance M.

Formula: M = k√(L₁ × L₂)','{"choices": ["6 H", "1.5 H", "0.75 H", "3 H"], "correct": 3}'::jsonb,'M = k√(L₁L₂) = 0.5 × √(4 × 9) = 0.5 × 6 = 3 H. The coupling coefficient k ranges from 0 (no coupling) to 1 (perfect coupling).','{multiple_choice}'::text[],0.62) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-21','Complex Impedance: Z_L = Z_S* for Max Power','Hard','ECE','arena','select','Circuit Analysis','multiple_choice','A signal source has source impedance Z_S = 50 + j100 Ω. For maximum power transfer to the load in an AC circuit, what load impedance Z_L is required?

For complex sources: Z_L = Z_S* (complex conjugate)','{"choices": ["50 + j100 Ω", "100 Ω", "50 Ω", "50 − j100 Ω"], "correct": 3}'::jsonb,'For complex impedance, maximum power transfer requires Z_L = Z_S* (conjugate): Z_L = 50 − j100 Ω. This cancels the reactive component and maximises real power to the load.','{multiple_choice}'::text[],0.58) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-22','Star-to-Delta Transformation','Hard','ECE','arena','calculate','Circuit Analysis','multiple_choice','A star (Y) network has Ra = 3 Ω, Rb = 4 Ω, Rc = 5 Ω. Convert to delta (Δ) and find R_AB.

Formula: R_AB = (RaRb + RbRc + RcRa) / Rc','{"choices": ["12 Ω", "7.83 Ω", "15.67 Ω", "9.4 Ω"], "correct": 3}'::jsonb,'R_AB = (3×4 + 4×5 + 5×3) / 5 = (12 + 20 + 15) / 5 = 47/5 = 9.4 Ω. The Y-Δ transform is used to simplify complex circuit topologies.','{multiple_choice}'::text[],0.6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-23','Fault Diagnosis: Short-Circuited Resistor','Hard','ECE','arena','diagnose','Circuit Analysis','multiple_choice','In a two-resistor series circuit (1 kΩ each, 12 V supply), a technician measures:
• 0 V across R₁
• 12 V across R₂

What is the most likely fault?','{"choices": ["R₂ is open-circuited", "The supply has dropped to 6 V", "R₁ is short-circuited", "R₁ is open-circuited"], "correct": 2}'::jsonb,'If R₁ is short-circuited (0 Ω), the full 12 V appears across R₂ and R₁ shows 0 V. This is the classic "dead resistor" signature: 0 V = short circuit, full voltage = open circuit.','{multiple_choice}'::text[],0.65) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-24','Power Factor and Reactive Power','Hard','ECE','arena','optimise','Circuit Analysis','multiple_choice','An industrial load draws 10 kW at power factor 0.6 lagging from a 230 V AC supply.

How much capacitive reactive power (kVAR) must be added to improve PF to unity?

Q = P × tan(θ)','{"choices": ["6.67 kVAR", "16.7 kVAR", "10 kVAR", "13.3 kVAR"], "correct": 3}'::jsonb,'θ = cos⁻¹(0.6) = 53.13°; tan(53.13°) = 1.333. Q_L = 10 × 1.333 = 13.3 kVAR. Add 13.3 kVAR capacitive to cancel the inductive reactive power and achieve unity PF.','{multiple_choice}'::text[],0.55) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-ca-25','Two-Port h-Parameters: Input Current','Hard','ECE','arena','interpret','Circuit Analysis','multiple_choice','A transistor in h-parameter model: h₁₁ = 1 kΩ, h₁₂ = 0.002, h₂₁ = 50, h₂₂ = 25 µS.
With V₁ = 10 mV applied and output open (I₂ = 0):

V₁ = h₁₁ × I₁ + h₁₂ × V₂

Find I₁.','{"choices": ["500 µA", "0.02 µA", "10 mA", "10 µA"], "correct": 3}'::jsonb,'With I₂ = 0 and no feedback (treat h₁₂ × V₂ ≈ 0 for simplification): I₁ = V₁/h₁₁ = 10 mV / 1 kΩ = 10 µA. h₁₁ is the input impedance with output short-circuited.','{multiple_choice}'::text[],0.52) ON CONFLICT (slug) DO NOTHING;
