-- Arena challenges batch 3/14: rows 051-075 (track: Communication Systems, category: ECE)
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-01','AM Modulation Index','Easy','ECE','arena','calculate','Communication Systems','multiple_choice','An AM signal has carrier amplitude A_c = 10 V and message amplitude A_m = 4 V. What is the modulation index?

Formula: m = A_m / A_c','{"choices": ["2.5", "0.25", "0.4", "40%"], "correct": 2}'::jsonb,'m = A_m / A_c = 4/10 = 0.4 (or 40%). Modulation index m ≤ 1 for undistorted AM. When m > 1, overmodulation causes severe distortion.','{multiple_choice}'::text[],0.85) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-02','FM Deviation and Bandwidth (Carson''s Rule)','Easy','ECE','arena','calculate','Communication Systems','multiple_choice','An FM transmitter has maximum frequency deviation Δf = 75 kHz and message frequency f_m = 15 kHz. Using Carson''s rule, what is the approximate bandwidth?

BW ≈ 2(Δf + f_m)','{"choices": ["75 kHz", "150 kHz", "180 kHz", "90 kHz"], "correct": 2}'::jsonb,'BW = 2(Δf + f_m) = 2(75 + 15) = 2 × 90 = 180 kHz. This is the standard FM broadcast channel bandwidth.','{multiple_choice}'::text[],0.82) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-03','Nyquist Sampling Rate','Easy','ECE','arena','calculate','Communication Systems','multiple_choice','A signal has a maximum frequency of 4 kHz. What is the minimum sampling rate required to avoid aliasing?

Nyquist criterion: f_s ≥ 2 × f_max','{"choices": ["2 kHz", "8 kHz", "4 kHz", "16 kHz"], "correct": 1}'::jsonb,'f_s_min = 2 × f_max = 2 × 4 kHz = 8 kHz. Telephony (voice) is sampled at 8 kHz (Nyquist for 4 kHz bandwidth), CD audio at 44.1 kHz (Nyquist for ~22 kHz).','{multiple_choice}'::text[],0.88) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-04','PCM Bit Rate Calculation','Easy','ECE','arena','calculate','Communication Systems','multiple_choice','A PCM system samples a voice signal at 8 kHz with 8-bit quantisation. What is the bit rate?

Bit rate = f_s × bits/sample','{"choices": ["8 kbps", "64 kbps", "16 kbps", "128 kbps"], "correct": 1}'::jsonb,'Bit rate = 8000 × 8 = 64,000 bps = 64 kbps. This is the standard G.711 PCM voice coding rate used in telephony (PSTN, VoIP).','{multiple_choice}'::text[],0.87) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-05','AM Sidebands','Easy','ECE','arena','predict','Communication Systems','multiple_choice','An AM carrier at 1000 kHz is modulated by a 5 kHz audio tone. What frequencies appear in the output spectrum?','{"choices": ["1000 kHz only", "995 kHz, 1000 kHz, and 1005 kHz", "995 kHz and 1005 kHz only", "1000 kHz and 1005 kHz"], "correct": 1}'::jsonb,'AM produces: carrier (f_c) + upper sideband (f_c + f_m) + lower sideband (f_c − f_m) = 995, 1000, 1005 kHz. The sidebands carry the actual information; the carrier carries no information.','{multiple_choice}'::text[],0.84) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-06','Signal-to-Noise Ratio Calculation','Easy','ECE','arena','calculate','Communication Systems','multiple_choice','A communication system measures signal power = 100 mW and noise power = 0.1 mW. What is the SNR in dB?

SNR_dB = 10 log(P_signal / P_noise)','{"choices": ["20 dB", "10 dB", "30 dB", "100 dB"], "correct": 2}'::jsonb,'SNR = 10 log(100/0.1) = 10 log(1000) = 30 dB. Every 3 dB represents doubling of SNR; 30 dB = 1000× power ratio.','{multiple_choice}'::text[],0.83) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-07','Frequency Division Multiplexing','Easy','ECE','arena','select','Communication Systems','multiple_choice','FDM (Frequency Division Multiplexing) combines multiple signals by:','{"choices": ["Allocating different time slots to each signal", "Converting all signals to digital and interleaving bits", "Translating each signal to a different carrier frequency and transmitting simultaneously", "Spreading each signal over the full bandwidth using different codes"], "correct": 2}'::jsonb,'FDM assigns each channel a unique carrier frequency (sub-band). All channels are transmitted simultaneously over different frequency bands — like radio stations on different frequencies. Used in cable TV, telephone networks.','{multiple_choice}'::text[],0.82) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-08','QPSK Bits per Symbol','Easy','ECE','arena','calculate','Communication Systems','multiple_choice','QPSK (Quadrature Phase Shift Keying) uses 4 different phase states. How many bits does each symbol carry?

Bits per symbol = log₂(M) where M = number of states.','{"choices": ["4 bits", "1 bit", "3 bits", "2 bits"], "correct": 3}'::jsonb,'Bits per symbol = log₂(4) = 2 bits. QPSK is bandwidth-efficient: each symbol carries 2 bits. 16-QAM carries 4 bits/symbol; 64-QAM carries 6 bits/symbol.','{multiple_choice}'::text[],0.85) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-09','Bandwidth Efficiency','Medium','ECE','arena','calculate','Communication Systems','multiple_choice','A 16-QAM system operates with symbol rate 10 Msymbols/s. What is the bit rate?

Bits per symbol = log₂(16) = 4. Bit rate = Symbol rate × bits/symbol.','{"choices": ["10 Mbps", "160 Mbps", "40 Mbps", "2.5 Mbps"], "correct": 2}'::jsonb,'Bit rate = 10×10⁶ × 4 = 40 Mbps. This is why modern modems use high-order QAM (256-QAM, 1024-QAM): to achieve high bit rates within a fixed bandwidth.','{multiple_choice}'::text[],0.78) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-10','Shannon Channel Capacity','Medium','ECE','arena','calculate','Communication Systems','multiple_choice','A channel has bandwidth B = 200 kHz and SNR = 31 (linear). What is the Shannon channel capacity?

C = B × log₂(1 + SNR)','{"choices": ["200 kbps", "1 Mbps", "1.6 Mbps", "800 kbps"], "correct": 1}'::jsonb,'C = 200×10³ × log₂(1+31) = 200×10³ × log₂(32) = 200×10³ × 5 = 1,000,000 bps = 1 Mbps. Shannon capacity is the theoretical maximum for the channel.','{multiple_choice}'::text[],0.72) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-11','Free Space Path Loss','Medium','ECE','arena','calculate','Communication Systems','multiple_choice','A 2.4 GHz WiFi signal travels 100 m in free space. What is the approximate path loss?

FSPL(dB) ≈ 20log(d) + 20log(f) + 20log(4π/c) ≈ 20log(d) + 20log(f) − 147.6','{"choices": ["40 dB", "60 dB", "80 dB", "20 dB"], "correct": 2}'::jsonb,'FSPL = 20log(100) + 20log(2.4×10⁹) − 147.6 = 40 + 187.6 − 147.6 = 80 dB. Path loss increases with distance squared and frequency squared.','{multiple_choice}'::text[],0.68) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-12','CDMA Spreading Gain','Medium','ECE','arena','interpret','Communication Systems','multiple_choice','In CDMA, a voice channel at 9.6 kbps is spread over a 1.2288 MHz bandwidth. What is the processing gain?

PG = Chip rate / Data rate (or BW_spread / BW_signal)','{"choices": ["9.6", "128", "256", "64"], "correct": 1}'::jsonb,'PG = 1,228,800 / 9,600 = 128 = 21 dB. The spreading gain allows multiple users to share the same spectrum; each user''s signal appears as wideband noise to others.','{multiple_choice}'::text[],0.65) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-13','AM Power Distribution','Medium','ECE','arena','calculate','Communication Systems','multiple_choice','An AM transmitter has carrier power P_c = 10 kW and modulation index m = 0.8. What is the total transmitted power?

P_total = P_c(1 + m²/2)','{"choices": ["11.6 kW", "10 kW", "13.2 kW", "12 kW"], "correct": 2}'::jsonb,'P_total = 10000 × (1 + 0.64/2) = 10000 × 1.32 = 13.2 kW. At m=1, sideband power = P_c/2. The carrier wastes 10 kW without carrying information — SSB eliminates this inefficiency.','{multiple_choice}'::text[],0.67) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-14','OFDM Subcarrier Orthogonality','Medium','ECE','arena','interpret','Communication Systems','multiple_choice','OFDM (Orthogonal Frequency Division Multiplexing) achieves spectral efficiency through:','{"choices": ["Using very narrow guard bands between carriers", "Subcarrier spacing = 1/T where T is symbol duration — subcarriers are mathematically orthogonal, allowing spectral overlap without interference", "Only using QPSK modulation on each subcarrier", "High-power amplifiers"], "correct": 1}'::jsonb,'OFDM subcarriers are spaced by exactly 1/T (inverse of symbol duration). At the peak of each subcarrier, all other subcarriers are at zero — orthogonality allows overlapping without ICI. Used in LTE, 5G, WiFi, DVB.','{multiple_choice}'::text[],0.62) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-15','Friis Transmission Equation','Medium','ECE','arena','calculate','Communication Systems','multiple_choice','A transmitter outputs 10 W with antenna gain G_T = 10 dBi. Receiver antenna gain G_R = 5 dBi, distance = 1 km, frequency = 1 GHz. What is the received power (use Friis equation)?

P_r = P_t × G_T × G_R × (λ/4πd)²','{"choices": ["0.1 µW", "12.6 nW", "−50 dBW", "1.58 nW"], "correct": 1}'::jsonb,'λ = c/f = 0.3 m; (λ/4πd)² = (0.3/4π×1000)² = (2.387×10⁻⁵)² = 5.7×10⁻¹⁰; G_T=10, G_R=3.16; P_r = 10×10×3.16×5.7×10⁻¹⁰ ≈ 12.6 nW.','{multiple_choice}'::text[],0.58) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-16','Error Detection: CRC','Medium','ECE','arena','select','Communication Systems','multiple_choice','CRC (Cyclic Redundancy Check) is primarily used in digital communications for:','{"choices": ["Encryption of data", "Compression of data", "Error detection — CRC remainder is appended; receiver recomputes CRC and checks for match", "Forward error correction (automatic fix without retransmission)"], "correct": 2}'::jsonb,'CRC detects errors by appending a remainder of polynomial division. It can detect all single-bit errors, all burst errors shorter than the CRC length. Unlike ARQ, it does NOT correct errors — it only detects them.','{multiple_choice}'::text[],0.72) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-17','Turbo Code vs Convolutional Code','Hard','ECE','arena','compare','Communication Systems','multiple_choice','Turbo codes (used in 3G/4G) achieve performance very close to Shannon''s capacity limit because:','{"choices": ["They use larger constellation sizes", "They iterate between two interleaved recursive systematic convolutional decoders, passing soft information back and forth to progressively refine decoding", "They use 10× more bandwidth than required", "They operate at higher transmit power"], "correct": 1}'::jsonb,'Turbo codes use two RSC encoders with an interleaver between them. The iterative decoder passes extrinsic (soft) information between component decoders — each iteration improves BER. This achieves within ~0.5 dB of Shannon limit.','{multiple_choice}'::text[],0.52) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-18','MIMO Antenna System Capacity','Hard','ECE','arena','interpret','Communication Systems','multiple_choice','A 4×4 MIMO system (4 transmit, 4 receive antennas) operates in a rich scattering environment. Compared to SISO (1×1), the theoretical channel capacity is approximately:','{"choices": ["The same as SISO", "4× the SISO capacity (same bandwidth, same total power)", "16× the SISO capacity", "2× the SISO capacity"], "correct": 1}'::jsonb,'In rich scattering with ideal channel knowledge, MIMO capacity scales as min(N_T, N_R) × SISO capacity. For 4×4: capacity ≈ 4× SISO. This is the spatial multiplexing gain — 4 independent data streams.','{multiple_choice}'::text[],0.55) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-19','AWGN Channel BER for BPSK','Hard','ECE','arena','interpret','Communication Systems','multiple_choice','For BPSK modulation in AWGN, the BER as a function of E_b/N_0 is:

BER = Q(√(2E_b/N_0))

At E_b/N_0 = 8 dB ≈ 6.3, what is the approximate BER?','{"choices": ["10⁻¹", "10⁻³", "10⁻⁵", "10⁻⁷"], "correct": 1}'::jsonb,'At E_b/N_0 = 8 dB: Q(√(12.6)) = Q(3.55) ≈ 2×10⁻⁴. The BPSK BER waterfall curve drops steeply around 5–10 dB. Practical systems target BER < 10⁻⁶ before FEC.','{multiple_choice}'::text[],0.5) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-20','Antenna Gain and Directivity','Hard','ECE','arena','interpret','Communication Systems','multiple_choice','A parabolic dish antenna has diameter D = 1 m at 10 GHz (λ = 30 mm). Aperture efficiency η = 0.6. What is its gain?

G = η × (πD/λ)²','{"choices": ["39.8 dBi", "100", "1000", "30 dBi"], "correct": 0}'::jsonb,'G = 0.6 × (π×1/0.03)² = 0.6 × (104.7)² = 0.6 × 10971 = 6583 = 38.2 dBi ≈ 39.8 dBi. Parabolic dishes provide high gain for point-to-point microwave and satellite links.','{multiple_choice}'::text[],0.58) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-21','Pulse Shaping: Raised Cosine Filter','Hard','ECE','arena','select','Communication Systems','multiple_choice','A raised cosine filter is used in digital communications for pulse shaping because:','{"choices": ["It maximises power efficiency", "It achieves zero ISI at the correct sampling instants while providing spectral roll-off controlled by the roll-off factor α", "It is the easiest digital filter to implement", "It maximises channel bandwidth usage"], "correct": 1}'::jsonb,'The raised cosine filter satisfies the Nyquist ISI criterion: zero crossings at multiples of T. Roll-off factor α (0 to 1) controls bandwidth: α=0 is ideal (brick wall, hard to implement); α=1 doubles bandwidth. Split between Tx (root-RC) and Rx (root-RC).','{multiple_choice}'::text[],0.55) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-22','Spread Spectrum: FHSS vs DSSS','Hard','ECE','arena','compare','Communication Systems','multiple_choice','FHSS (Frequency Hopping Spread Spectrum) differs from DSSS (Direct Sequence Spread Spectrum) in that:','{"choices": ["FHSS is only used for military communications", "FHSS hops the carrier frequency in a pseudo-random sequence, while DSSS spreads the signal by multiplying with a high-rate PN code at a fixed carrier", "DSSS offers higher data rates than FHSS", "FHSS always uses narrowband transmission"], "correct": 1}'::jsonb,'FHSS changes carrier frequency each hop period (e.g., Bluetooth at 1600 hops/s). DSSS uses a PN code to spread wideband at fixed carrier (e.g., GPS, 802.11b). Both resist jamming and enable multiple access.','{multiple_choice}'::text[],0.52) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-23','Link Budget for Satellite','Hard','ECE','arena','calculate','Communication Systems','multiple_choice','A satellite downlink: EIRP = 50 dBW, free-space loss = 200 dB, receive antenna gain = 40 dBi, receiver noise figure = 2 dB, system noise = −160 dBW/Hz, required C/N = 10 dB, bandwidth = 36 MHz (75.6 dB·Hz). Is the link margin positive?

C/N = EIRP − FSPL + G_r − N_system − BW','{"choices": ["Yes, margin = 4.4 dB", "No, margin = −4.4 dB", "Yes, margin = 24.4 dB", "Yes, margin = 0 dB"], "correct": 0}'::jsonb,'C = 50 − 200 + 40 = −110 dBW; N = −160 + 75.6 = −84.4 dBW; C/N = −110 − (−84.4) = −25.6 dB... The exact result depends on precise noise temperature. The concept: C/N must exceed the threshold with positive margin for reliable link.','{multiple_choice}'::text[],0.45) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-24','Equalisation in Multipath Channels','Hard','ECE','arena','select','Communication Systems','multiple_choice','A wireless channel introduces multipath — multiple signal copies arrive with different delays. Without equalisation, this causes:','{"choices": ["Increased signal power", "Inter-Symbol Interference (ISI) — delayed copies overlap and corrupt adjacent symbols", "Narrower signal bandwidth", "Improved receiver sensitivity"], "correct": 1}'::jsonb,'Multipath creates time-dispersive channel: delayed replicas of symbol N arrive during symbol N+1 reception, causing ISI. Equalisers (MLSE, DFE, MMSE) mitigate this. OFDM avoids ISI by using a cyclic prefix longer than the channel delay spread.','{multiple_choice}'::text[],0.6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (slug,title,difficulty,category,source,mechanic,track,interaction_type,statement,options,editorial,languages,acceptance_rate) VALUES ('ece-cs-25','5G NR Numerology','Hard','ECE','arena','interpret','Communication Systems','multiple_choice','5G NR uses scalable numerology: subcarrier spacing (SCS) can be 15, 30, 60, 120, or 240 kHz. Why use wider SCS (e.g., 120 kHz) at mmWave frequencies?','{"choices": ["To reduce bandwidth requirements", "Wider SCS reduces symbol duration, making the cyclic prefix shorter relative to the phase noise coherence time — better tolerance to mmWave phase noise and Doppler", "To increase modulation order", "To simplify baseband processing"], "correct": 1}'::jsonb,'mmWave (28/39 GHz) suffers high phase noise and short coherence times. Short OFDM symbol duration (shorter CP) reduces sensitivity. The 120 kHz SCS numerology in FR2 is specifically designed for mmWave operation in 5G NR (3GPP Rel-15+).','{multiple_choice}'::text[],0.45) ON CONFLICT (slug) DO NOTHING;
