/**
 * Capabilio Employment Verification & Professional ELO System
 * careerEvents.js — event taxonomy, ELO model, path transition rules
 */

// ─── Career Event Types ───────────────────────────────────────────────────────

export const CAREER_EVENT_TYPES = {
  // Job entry/exit
  FIRST_JOB:                "first_job",
  COMPANY_JOIN:             "company_join",
  COMPANY_EXIT_CLEAN:       "company_exit_clean",
  COMPANY_EXIT_INVOLUNTARY: "company_exit_involuntary",

  // Tenure milestones (auto-generated by system)
  TENURE_6M:                "tenure_6m",
  TENURE_1Y:                "tenure_1y",
  TENURE_2Y:                "tenure_2y",
  TENURE_3Y:                "tenure_3y",
  TENURE_YEARLY:            "tenure_yearly",   // 4th year onwards, +20 per year

  // Growth
  PROMOTION_VERIFIED:       "promotion_verified",
  PROMOTION_SELF:           "promotion_self",
  LEADERSHIP_ENTRY:         "leadership_entry",
  INTERNATIONAL_ROLE:       "international_role",

  // Transitions
  COMPANY_SWITCH_UPWARD:    "company_switch_upward",
  COMPANY_SWITCH_LATERAL:   "company_switch_lateral",

  // Output proof
  PROJECT_OUTCOME:          "project_outcome",
  SKILL_VERIFIED:           "skill_verified",

  // Gap detection (auto)
  GAP_SHORT:                "gap_short",      // < 3 months — neutral
  GAP_LONG:                 "gap_long",       // > 6 months — minor penalty

  // Arena (professional context)
  ARENA_PROFESSIONAL:       "arena_professional",
}

// ─── ELO Delta Configuration ──────────────────────────────────────────────────

export const EVENT_ELO_CONFIG = {
  [CAREER_EVENT_TYPES.FIRST_JOB]:                { base: 80,  requiresVerification: true,  minLevel: 3 },
  [CAREER_EVENT_TYPES.COMPANY_JOIN]:             { base: 40,  requiresVerification: true,  minLevel: 3 },
  [CAREER_EVENT_TYPES.COMPANY_EXIT_CLEAN]:       { base: 10,  requiresVerification: true,  minLevel: 3 },
  [CAREER_EVENT_TYPES.COMPANY_EXIT_INVOLUNTARY]: { base: 0,   requiresVerification: true,  minLevel: 3 },

  [CAREER_EVENT_TYPES.TENURE_6M]:                { base: 15,  requiresVerification: false, minLevel: 3, autoEvent: true },
  [CAREER_EVENT_TYPES.TENURE_1Y]:                { base: 25,  requiresVerification: false, minLevel: 3, autoEvent: true },
  [CAREER_EVENT_TYPES.TENURE_2Y]:                { base: 35,  requiresVerification: false, minLevel: 3, autoEvent: true },
  [CAREER_EVENT_TYPES.TENURE_3Y]:                { base: 45,  requiresVerification: false, minLevel: 3, autoEvent: true },
  [CAREER_EVENT_TYPES.TENURE_YEARLY]:            { base: 20,  requiresVerification: false, minLevel: 3, autoEvent: true },

  [CAREER_EVENT_TYPES.PROMOTION_VERIFIED]:       { base: 50,  requiresVerification: true,  minLevel: 3 },
  [CAREER_EVENT_TYPES.PROMOTION_SELF]:           { base: 10,  requiresVerification: false, minLevel: 0 },
  [CAREER_EVENT_TYPES.LEADERSHIP_ENTRY]:         { base: 30,  requiresVerification: true,  minLevel: 3 },
  [CAREER_EVENT_TYPES.INTERNATIONAL_ROLE]:       { base: 25,  requiresVerification: true,  minLevel: 3 },

  [CAREER_EVENT_TYPES.COMPANY_SWITCH_UPWARD]:    { base: 40,  requiresVerification: true,  minLevel: 3 },
  [CAREER_EVENT_TYPES.COMPANY_SWITCH_LATERAL]:   { base: 20,  requiresVerification: true,  minLevel: 3 },

  [CAREER_EVENT_TYPES.PROJECT_OUTCOME]:          { base: 20,  requiresVerification: false, minLevel: 1 },
  [CAREER_EVENT_TYPES.SKILL_VERIFIED]:           { base: 10,  requiresVerification: false, minLevel: 2 },

  [CAREER_EVENT_TYPES.GAP_SHORT]:                { base: 0,   requiresVerification: false, minLevel: 0 },
  [CAREER_EVENT_TYPES.GAP_LONG]:                 { base: -5,  requiresVerification: false, minLevel: 0 },

  [CAREER_EVENT_TYPES.ARENA_PROFESSIONAL]:       { base: null, requiresVerification: false, minLevel: 3,
                                                   compute: (arenaScore) => Math.round((arenaScore / 100) * 25) },
}

// ─── Verification Source Types ────────────────────────────────────────────────

export const VERIFICATION_SOURCES = {
  EPFO:           "epfo",
  UMANG:          "umang",
  DIGILOCKER:     "digilocker",
  EMPLOYER_EMAIL: "employer_email",
  OFFER_LETTER:   "offer_letter",
  LINKEDIN:       "linkedin",
  MANUAL_REVIEW:  "manual_review",
  SYSTEM_AUTO:    "system_auto",
  SELF_CLAIMED:   "self_claimed",
}

// Maps source → verification level
export const SOURCE_VERIFICATION_LEVEL = {
  [VERIFICATION_SOURCES.SELF_CLAIMED]:    0,
  [VERIFICATION_SOURCES.OFFER_LETTER]:    1,
  [VERIFICATION_SOURCES.EMPLOYER_EMAIL]:  2,
  [VERIFICATION_SOURCES.LINKEDIN]:        2,
  [VERIFICATION_SOURCES.SYSTEM_AUTO]:     3,   // system tenure milestones — derive from V3 parent
  [VERIFICATION_SOURCES.DIGILOCKER]:      3,
  [VERIFICATION_SOURCES.UMANG]:           3,
  [VERIFICATION_SOURCES.EPFO]:            3,
  [VERIFICATION_SOURCES.MANUAL_REVIEW]:   3,
}

// Source display config for UI
export const SOURCE_DISPLAY = {
  [VERIFICATION_SOURCES.EPFO]:           { label: "EPFO Verified",      icon: "✓", color: "#22C55E", badge: true },
  [VERIFICATION_SOURCES.UMANG]:          { label: "UMANG Verified",     icon: "✓", color: "#22C55E", badge: true },
  [VERIFICATION_SOURCES.DIGILOCKER]:     { label: "DigiLocker Verified",icon: "✓", color: "#22C55E", badge: true },
  [VERIFICATION_SOURCES.EMPLOYER_EMAIL]: { label: "Email Verified",     icon: "🔗", color: "#14B8A6", badge: false },
  [VERIFICATION_SOURCES.OFFER_LETTER]:   { label: "Offer Letter",       icon: "📎", color: "#3B82F6", badge: false },
  [VERIFICATION_SOURCES.LINKEDIN]:       { label: "LinkedIn",           icon: "🔗", color: "#0077B5", badge: false },
  [VERIFICATION_SOURCES.MANUAL_REVIEW]:  { label: "Manually Reviewed",  icon: "✓", color: "#22C55E", badge: true },
  [VERIFICATION_SOURCES.SYSTEM_AUTO]:    { label: "Auto-detected",      icon: "⚡", color: "#6366F1", badge: false },
  [VERIFICATION_SOURCES.SELF_CLAIMED]:   { label: "Self-claimed",       icon: "⚠", color: "#94A3B8", badge: false, warning: true },
}

// ─── Path States ──────────────────────────────────────────────────────────────

export const PATH_STATES = {
  STUDENT:         "student",
  TRANSITIONING:   "transitioning",
  PROFESSIONAL:    "professional",
}

export const PATH_STATE_CONFIG = {
  [PATH_STATES.STUDENT]: {
    label:       "Student",
    icon:        "🎓",
    color:       "#6366F1",
    bgColor:     "rgba(99,102,241,0.12)",
    description: "Learning and building",
    uiMode:      "student",
  },
  [PATH_STATES.TRANSITIONING]: {
    label:       "Transitioning",
    icon:        "⏳",
    color:       "#F59E0B",
    bgColor:     "rgba(245,158,11,0.12)",
    description: "Employment verification in progress",
    uiMode:      "hybrid",
  },
  [PATH_STATES.PROFESSIONAL]: {
    label:       "Professional",
    icon:        "💼",
    color:       "#22C55E",
    bgColor:     "rgba(34,197,94,0.12)",
    description: "Verified career",
    uiMode:      "professional",
  },
}

// ─── ELO Computation Engine ───────────────────────────────────────────────────

export const PROFESSIONAL_ELO_START      = 600
export const PROFESSIONAL_ELO_FLOOR      = 400
export const BACKFILL_ELO_CAP            = 300   // max ELO from historical import in one batch
export const ARENA_WEIGHT_FOR_BLENDED    = 0.40
export const PROFESSIONAL_WEIGHT_BLENDED = 0.60

/**
 * Compute ELO delta for a career event.
 * Returns 0 for unverified events (V0) — self-claimed does not move ELO.
 */
export function computeEloDelta({ eventType, verificationLevel, arenaScore = null, daysAgo = 0 }) {
  const config = EVENT_ELO_CONFIG[eventType]
  if (!config) return 0

  // Self-claimed (V0) never earns ELO
  if (verificationLevel < config.minLevel) return 0

  // Get base delta
  let base
  if (config.compute && arenaScore !== null) {
    base = config.compute(arenaScore)
  } else {
    base = config.base ?? 0
  }

  if (base === 0) return 0

  // Verification multiplier
  const verificationMultiplier =
    verificationLevel >= 3 ? 1.0 :
    verificationLevel === 2 ? 0.6 :
    verificationLevel === 1 ? 0.3 : 0.0

  // Recency multiplier
  const recencyMultiplier =
    daysAgo <= 30  ? 1.0 :
    daysAgo <= 180 ? 0.95 :
    daysAgo <= 365 ? 0.90 : 0.85

  return Math.round(base * verificationMultiplier * recencyMultiplier)
}

/**
 * Compute blended ELO from arena and professional components.
 */
export function computeBlendedElo(arenaElo, professionalElo) {
  if (!professionalElo || professionalElo <= 0) return arenaElo
  return Math.round(
    arenaElo * ARENA_WEIGHT_FOR_BLENDED +
    professionalElo * PROFESSIONAL_WEIGHT_BLENDED
  )
}

/**
 * Compute Professional ELO from scratch given a list of career events.
 * Used for backfill on first EPFO import.
 */
export function computeProfessionalEloFromHistory(events = []) {
  const sorted = [...events].sort((a, b) => new Date(a.start_date) - new Date(b.start_date))
  let elo = PROFESSIONAL_ELO_START
  let backfillTotal = 0

  for (const event of sorted) {
    const daysAgo = Math.max(0, (Date.now() - new Date(event.created_at || event.start_date)) / 86400000)
    const delta = computeEloDelta({
      eventType:         event.event_type,
      verificationLevel: SOURCE_VERIFICATION_LEVEL[event.source_type] ?? event.verification_level ?? 0,
      daysAgo,
    })

    const cappedDelta = Math.min(delta, BACKFILL_ELO_CAP - backfillTotal)
    backfillTotal += cappedDelta
    elo = Math.max(PROFESSIONAL_ELO_FLOOR, elo + cappedDelta)

    if (backfillTotal >= BACKFILL_ELO_CAP) break
  }

  return elo
}

// ─── Path Transition Evaluation ───────────────────────────────────────────────

/**
 * Evaluate whether a user qualifies for path transition.
 * Returns { transition: true/false, targetState, reason, strength }
 */
export function evaluatePathTransition({ currentPath, careerEvents, profile }) {
  if (currentPath === PATH_STATES.PROFESSIONAL) {
    return { transition: false, reason: "Already professional" }
  }

  // Condition A — first verified job (strongest signal)
  const firstJobEvent = careerEvents.find(e =>
    e.event_type === CAREER_EVENT_TYPES.FIRST_JOB &&
    (SOURCE_VERIFICATION_LEVEL[e.source_type] ?? e.verification_level) >= 3
  )
  if (firstJobEvent) {
    return {
      transition:   true,
      targetState:  PATH_STATES.PROFESSIONAL,
      reason:       `First verified job at ${firstJobEvent.company_name}`,
      strength:     "strong",
      triggerEvent: firstJobEvent.id,
    }
  }

  // Condition B — EPFO batch with 90+ days tenure
  const epfoEvents = careerEvents.filter(e => e.source_type === VERIFICATION_SOURCES.EPFO)
  if (epfoEvents.length > 0) {
    const totalDays = epfoEvents.reduce((sum, e) => {
      const start = new Date(e.start_date)
      const end   = e.end_date ? new Date(e.end_date) : new Date()
      return sum + Math.max(0, (end - start) / 86400000)
    }, 0)
    if (totalDays >= 90) {
      return {
        transition:  true,
        targetState: PATH_STATES.PROFESSIONAL,
        reason:      `${Math.round(totalDays)} verified employment days via EPFO`,
        strength:    "strong",
        triggerEvent: epfoEvents[0].id,
      }
    }
  }

  // Condition C — composite V2 signals
  const hasEmailVerified = profile.company_email_verified === true
  const hasLinkedIn      = careerEvents.some(e => e.source_type === VERIFICATION_SOURCES.LINKEDIN)
  const hasManualConfirm = profile.employment_self_confirmed === true
  if (hasEmailVerified && hasLinkedIn && hasManualConfirm) {
    return {
      transition:  true,
      targetState: PATH_STATES.TRANSITIONING,  // V2-grade → transitioning only
      reason:      "Composite employment signals (email + LinkedIn + self-confirm)",
      strength:    "weak",
    }
  }

  return { transition: false, reason: "Insufficient verification signals" }
}

// ─── Tenure Milestone Checker ─────────────────────────────────────────────────

// Milestones in days → { eventType, elo config key }
export const TENURE_MILESTONES = [
  { days: 180,  eventType: CAREER_EVENT_TYPES.TENURE_6M,     label: "6 months" },
  { days: 365,  eventType: CAREER_EVENT_TYPES.TENURE_1Y,     label: "1 year"   },
  { days: 730,  eventType: CAREER_EVENT_TYPES.TENURE_2Y,     label: "2 years"  },
  { days: 1095, eventType: CAREER_EVENT_TYPES.TENURE_3Y,     label: "3 years"  },
  { days: 1460, eventType: CAREER_EVENT_TYPES.TENURE_YEARLY, label: "4 years"  },
  { days: 1825, eventType: CAREER_EVENT_TYPES.TENURE_YEARLY, label: "5 years"  },
]

/**
 * Given an employment record, return which milestones are due but not yet fired.
 */
export function getPendingMilestones({ startDate, existingMilestones = [] }) {
  const daysElapsed = (Date.now() - new Date(startDate)) / 86400000
  const firedTypes  = new Set(existingMilestones.map(m => m.event_type))

  return TENURE_MILESTONES.filter(m =>
    daysElapsed >= m.days && !firedTypes.has(m.eventType)
  )
}

// ─── Recruiter Trust Score ────────────────────────────────────────────────────

/**
 * Compute the recruiter-facing trust score (0–100).
 * Displayed as Low / Medium / High / Very High / Exceptional.
 */
export function computeRecruiterTrustScore({ careerEvents, blendedElo, profile }) {
  const total    = careerEvents.length
  if (total === 0) return 0

  const verified = careerEvents.filter(e =>
    (SOURCE_VERIFICATION_LEVEL[e.source_type] ?? e.verification_level ?? 0) >= 3
  ).length

  const verificationRatio = verified / total
  const epfoVerified      = careerEvents.some(e =>
    e.source_type === VERIFICATION_SOURCES.EPFO || e.source_type === VERIFICATION_SOURCES.UMANG
  )

  const verifiedTenureYears = (profile.verified_tenure_months ?? 0) / 12
  const eloFactor           = Math.min(blendedElo, 2000) / 2000

  const score = Math.round(
    verificationRatio * 40 +
    (epfoVerified ? 30 : 0) +
    Math.min(verifiedTenureYears, 5) * 4 +
    eloFactor * 30
  )

  return Math.min(100, score)
}

export const TRUST_SCORE_BANDS = [
  { min: 90,  label: "Exceptional", color: "#F59E0B" },
  { min: 75,  label: "Very High",   color: "#22C55E" },
  { min: 60,  label: "High",        color: "#14B8A6" },
  { min: 40,  label: "Medium",      color: "#3B82F6" },
  { min: 0,   label: "Low",         color: "#94A3B8" },
]

export function getTrustBand(score) {
  return TRUST_SCORE_BANDS.find(b => score >= b.min) ?? TRUST_SCORE_BANDS[TRUST_SCORE_BANDS.length - 1]
}

// ─── Aura Score Integration ───────────────────────────────────────────────────

/**
 * Compute Aura points from professional career events.
 * Professional path has different Aura weights than student path.
 */
export function computeProfessionalAuraFromEvents(events = []) {
  let pts = 0
  const caps = {
    tenure:   50,
    verified: 30,
    growth:   20,
  }
  let tenurePts = 0, verifiedPts = 0, growthPts = 0

  for (const event of events) {
    const level = SOURCE_VERIFICATION_LEVEL[event.source_type] ?? event.verification_level ?? 0
    if (level < 1) continue  // self-claimed gives no Aura points

    if ([
      CAREER_EVENT_TYPES.TENURE_6M,
      CAREER_EVENT_TYPES.TENURE_1Y,
      CAREER_EVENT_TYPES.TENURE_2Y,
      CAREER_EVENT_TYPES.TENURE_3Y,
      CAREER_EVENT_TYPES.TENURE_YEARLY,
    ].includes(event.event_type)) {
      const delta = EVENT_ELO_CONFIG[event.event_type]?.base ?? 0
      tenurePts = Math.min(tenurePts + Math.round(delta * 0.5), caps.tenure)
    }

    if ([
      CAREER_EVENT_TYPES.FIRST_JOB,
      CAREER_EVENT_TYPES.COMPANY_JOIN,
      CAREER_EVENT_TYPES.PROMOTION_VERIFIED,
    ].includes(event.event_type) && level >= 3) {
      verifiedPts = Math.min(verifiedPts + 8, caps.verified)
    }

    if ([
      CAREER_EVENT_TYPES.LEADERSHIP_ENTRY,
      CAREER_EVENT_TYPES.COMPANY_SWITCH_UPWARD,
      CAREER_EVENT_TYPES.INTERNATIONAL_ROLE,
    ].includes(event.event_type)) {
      growthPts = Math.min(growthPts + 10, caps.growth)
    }
  }

  return tenurePts + verifiedPts + growthPts
}

// ─── UI Mode Differences ─────────────────────────────────────────────────────

export const UI_MODE_CONFIG = {
  student: {
    dashboardHeadline:  "Your learning journey",
    timelineDefaultTab: "academic_project",
    featuredSections:   ["arena", "projects", "skills", "education"],
    hideSections:       ["company_history", "role_progression", "verified_employment"],
    trustBannerText:    "Build your proof with Arena challenges",
    profileBadge:       "🎓 Student",
    recruiterCTA:       "View Arena performance",
    emptyStateKey:      "student",
  },
  hybrid: {
    dashboardHeadline:  "Employment verification in progress",
    timelineDefaultTab: "professional_experience",
    featuredSections:   ["arena", "projects", "skills", "employment"],
    hideSections:       [],
    trustBannerText:    "⏳ Verification pending — add UAN to complete",
    profileBadge:       "⏳ Transitioning",
    recruiterCTA:       "View profile",
    emptyStateKey:      "transitioning",
  },
  professional: {
    dashboardHeadline:  "Your verified career",
    timelineDefaultTab: "professional_experience",
    featuredSections:   ["verified_employment", "skills", "arena", "projects"],
    hideSections:       [],
    trustBannerText:    null,  // replaced by EPFO Verified badge
    profileBadge:       "💼 Professional",
    recruiterCTA:       "View verified career history",
    emptyStateKey:      "professional",
  },
}

// ─── Career Event Display Config ─────────────────────────────────────────────

export const EVENT_DISPLAY = {
  [CAREER_EVENT_TYPES.FIRST_JOB]:             { label: "First verified job",      icon: "🚀", color: "#22C55E" },
  [CAREER_EVENT_TYPES.COMPANY_JOIN]:          { label: "Joined company",          icon: "🏢", color: "#3B82F6" },
  [CAREER_EVENT_TYPES.COMPANY_EXIT_CLEAN]:    { label: "Left company",            icon: "↪",  color: "#94A3B8" },
  [CAREER_EVENT_TYPES.TENURE_6M]:             { label: "6-month milestone",       icon: "⏱",  color: "#14B8A6" },
  [CAREER_EVENT_TYPES.TENURE_1Y]:             { label: "1-year milestone",        icon: "📅", color: "#14B8A6" },
  [CAREER_EVENT_TYPES.TENURE_2Y]:             { label: "2-year milestone",        icon: "📅", color: "#14B8A6" },
  [CAREER_EVENT_TYPES.TENURE_3Y]:             { label: "3-year milestone",        icon: "🎖",  color: "#F59E0B" },
  [CAREER_EVENT_TYPES.PROMOTION_VERIFIED]:    { label: "Promotion",               icon: "⬆",  color: "#F59E0B" },
  [CAREER_EVENT_TYPES.PROMOTION_SELF]:        { label: "Promotion (self-claimed)",icon: "⬆",  color: "#94A3B8", warning: true },
  [CAREER_EVENT_TYPES.LEADERSHIP_ENTRY]:      { label: "Leadership role",         icon: "👥", color: "#8B5CF6" },
  [CAREER_EVENT_TYPES.COMPANY_SWITCH_UPWARD]: { label: "Career move (upward)",    icon: "🎯", color: "#22C55E" },
  [CAREER_EVENT_TYPES.COMPANY_SWITCH_LATERAL]:{ label: "Company switch",          icon: "↔",  color: "#3B82F6" },
  [CAREER_EVENT_TYPES.GAP_LONG]:              { label: "Career gap",              icon: "⏸",  color: "#64748B" },
  [CAREER_EVENT_TYPES.ARENA_PROFESSIONAL]:    { label: "Arena (professional)",    icon: "⚔",  color: "#3B82F6" },
  [CAREER_EVENT_TYPES.INTERNATIONAL_ROLE]:    { label: "International role",      icon: "🌐", color: "#6366F1" },
}
