-- STEP 2: Problems 1–20 of 201
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate)
VALUES
($q$Zomato Order Pair Finder$q$,$q$two-sum$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['arrays','hash-map'],$q$## Problem

Zomato's analytics team has a list of delivery order amounts (in rupees) and a target amount `T`. Find the indices of the **two orders** whose amounts add up to exactly `T`. You may assume exactly one valid answer exists, and you cannot use the same order twice.

Return the indices as `[i, j]` where `i < j`.$q$,$q$2 ≤ n ≤ 10^4 | 1 ≤ orders[i] ≤ 10^6 | 1 ≤ T ≤ 2×10^6$q$,$q$[{"input": "orders = [200, 50, 150, 400], T = 350", "output": "[0, 2]", "explanation": "orders[0] + orders[2] = 200 + 150 = 350"}]$q$::jsonb,$q$[{"input": "[200,50,150,400]\n350", "expected_output": "[0,2]", "is_hidden": false}, {"input": "[11,2,15,7]\n9", "expected_output": "[1,3]", "is_hidden": true}]$q$::jsonb,$q$Use a hash map: for each amount, check if T - amount exists. O(n) time, O(n) space.$q$,ARRAY['python','java','javascript','go','cpp'],0.72),
($q$BSE Stock Profit Maximizer$q$,$q$best-time-to-buy-sell-stock$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['arrays','greedy'],$q$## Problem

You are given `prices[i]` = BSE stock price on day `i`. Buy once, sell once. Return the **maximum profit**. If no profit possible, return `0`.$q$,$q$1 ≤ n ≤ 10^5 | 0 ≤ prices[i] ≤ 10^4$q$,$q$[{"input": "prices = [310, 280, 420, 210, 500, 390]", "output": "290", "explanation": "Buy at 210 (day 4), sell at 500 (day 5) = 290"}]$q$::jsonb,$q$[{"input": "[310,280,420,210,500,390]", "expected_output": "290", "is_hidden": false}, {"input": "[900,800,700,600]", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$Track running min price and max profit. Single pass O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.68),
($q$Swiggy Rating Maximum Subarray$q$,$q$maximum-subarray$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['arrays','dynamic-programming','kadane'],$q$## Problem

Swiggy tracks daily net satisfaction scores (can be negative). Given `scores`, find the contiguous subarray with the **largest sum** (Kadane's algorithm).$q$,$q$1 ≤ n ≤ 10^5 | -10^4 ≤ scores[i] ≤ 10^4$q$,$q$[{"input": "scores = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6", "explanation": "Subarray [4,-1,2,1] = 6"}]$q$::jsonb,$q$[{"input": "[-2,1,-3,4,-1,2,1,-5,4]", "expected_output": "6", "is_hidden": false}, {"input": "[1]", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$cur = max(x, cur+x); best = max(best, cur). O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.63),
($q$IRCTC Train Schedule Merger$q$,$q$merge-intervals$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','sorting','intervals'],$q$## Problem

IRCTC needs to merge overlapping maintenance windows on a track. Given intervals `[[start,end],...]` in minutes from midnight, return merged non-overlapping intervals.$q$,$q$1 ≤ n ≤ 10^4 | 0 ≤ start ≤ end ≤ 1440$q$,$q$[{"input": "intervals = [[60,90],[80,120],[200,240],[230,300]]", "output": "[[60,120],[200,300]]", "explanation": "[60,90]+[80,120] overlap; [200,240]+[230,300] overlap"}]$q$::jsonb,$q$[{"input": "[[60,90],[80,120],[200,240],[230,300]]", "expected_output": "[[60,120],[200,300]]", "is_hidden": false}, {"input": "[[1,4],[4,5]]", "expected_output": "[[1,5]]", "is_hidden": true}]$q$::jsonb,$q$Sort by start. Extend last merged end if overlap. O(n log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.56),
($q$Flipkart Cart Three Sum$q$,$q$three-sum$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','two-pointers','sorting'],$q$## Problem

Flipkart offers price adjustments (positive = addition, negative = discount). Find all **unique triplets** from `prices` summing to **zero**.$q$,$q$3 ≤ n ≤ 3000 | -10^5 ≤ prices[i] ≤ 10^5$q$,$q$[{"input": "prices = [-1,0,1,2,-1,-4]", "output": "[[-1,-1,2],[-1,0,1]]"}]$q$::jsonb,$q$[{"input": "[-1,0,1,2,-1,-4]", "expected_output": "[[-1,-1,2],[-1,0,1]]", "is_hidden": false}, {"input": "[0,0,0]", "expected_output": "[[0,0,0]]", "is_hidden": true}]$q$::jsonb,$q$Sort. For each element, two pointers on rest. Skip duplicates. O(n²).$q$,ARRAY['python','java','javascript','go','cpp'],0.41),
($q$Paytm Wallet Container Volume$q$,$q$container-with-most-water$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','two-pointers'],$q$## Problem

Given `n` wall heights, find two walls that together hold the **most water**. Return maximum water units.$q$,$q$2 ≤ n ≤ 10^5 | 0 ≤ height[i] ≤ 10^4$q$,$q$[{"input": "height = [1,8,6,2,5,4,8,3,7]", "output": "49", "explanation": "Walls at idx 1,8: min(8,7)×7=49"}]$q$::jsonb,$q$[{"input": "[1,8,6,2,5,4,8,3,7]", "expected_output": "49", "is_hidden": false}, {"input": "[1,1]", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$Two pointers from both ends. Move pointer with smaller height. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.58),
($q$Mumbai Monsoon Water Trap$q$,$q$trapping-rain-water$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['arrays','two-pointers','stack'],$q$## Problem

Mumbai's drainage engineers mapped city elevation. Given `heights`, compute how many units of rainwater can be trapped after monsoon rains.$q$,$q$1 ≤ n ≤ 2×10^4 | 0 ≤ heights[i] ≤ 10^5$q$,$q$[{"input": "heights = [0,1,0,2,1,0,1,3,2,1,2,1]", "output": "6"}]$q$::jsonb,$q$[{"input": "[0,1,0,2,1,0,1,3,2,1,2,1]", "expected_output": "6", "is_hidden": false}, {"input": "[4,2,0,3,2,5]", "expected_output": "9", "is_hidden": true}]$q$::jsonb,$q$Two-pointer: leftMax, rightMax. water[i]=min(leftMax,rightMax)-height[i]. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.35),
($q$OYO Room Booking Jump Game$q$,$q$jump-game$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','greedy'],$q$## Problem

`jumps[i]` = max steps from position `i`. Starting at index 0, determine if you can **reach the last index**.$q$,$q$1 ≤ n ≤ 10^4 | 0 ≤ jumps[i] ≤ 10$q$,$q$[{"input": "jumps = [2,3,1,1,4]", "output": "true"}, {"input": "jumps = [3,2,1,0,4]", "output": "false"}]$q$::jsonb,$q$[{"input": "[2,3,1,1,4]", "expected_output": "true", "is_hidden": false}, {"input": "[3,2,1,0,4]", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$Track maxReach. If i > maxReach, return false. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.49),
($q$Nykaa Product Self-Excluding Product$q$,$q$product-of-array-except-self$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','prefix-product'],$q$## Problem

Given `prices`, return array where `result[i]` = product of all elements **except** `prices[i]`. No division, O(n).$q$,$q$2 ≤ n ≤ 10^5 | -30 ≤ prices[i] ≤ 30$q$,$q$[{"input": "prices = [1,2,3,4]", "output": "[24,12,8,6]"}]$q$::jsonb,$q$[{"input": "[1,2,3,4]", "expected_output": "[24,12,8,6]", "is_hidden": false}, {"input": "[-1,1,0,-3,3]", "expected_output": "[0,0,9,0,0]", "is_hidden": true}]$q$::jsonb,$q$Prefix product left-to-right × suffix product right-to-left. O(n) O(1) extra.$q$,ARRAY['python','java','javascript','go','cpp'],0.64),
($q$Reliance Jio Tower Spiral Read$q$,$q$spiral-matrix$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','matrix','simulation'],$q$## Problem

Given an `m×n` grid of signal strengths, return all elements in **clockwise spiral order**.$q$,$q$1 ≤ m,n ≤ 10 | -100 ≤ grid[i][j] ≤ 100$q$,$q$[{"input": "grid = [[1,2,3],[4,5,6],[7,8,9]]", "output": "[1,2,3,6,9,8,7,4,5]"}]$q$::jsonb,$q$[{"input": "[[1,2,3],[4,5,6],[7,8,9]]", "expected_output": "[1,2,3,6,9,8,7,4,5]", "is_hidden": false}, {"input": "[[1,2],[3,4]]", "expected_output": "[1,2,4,3]", "is_hidden": true}]$q$::jsonb,$q$Peel layers: top row, right col, bottom row, left col. Shrink boundaries. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.52),
($q$IndiGo Seat Booking Subarray Sum$q$,$q$subarray-sum-equals-k$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','hash-map','prefix-sum'],$q$## Problem

Given loyalty `points` array and target `k`, count **contiguous subarrays** whose sum equals `k`.$q$,$q$1 ≤ n ≤ 2×10^4 | -1000 ≤ points[i] ≤ 1000 | -10^7 ≤ k ≤ 10^7$q$,$q$[{"input": "points = [1,1,1], k = 2", "output": "2"}]$q$::jsonb,$q$[{"input": "[1,1,1]\n2", "expected_output": "2", "is_hidden": false}, {"input": "[1,2,3]\n3", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$Prefix sum + hashmap. For each sum S, count prev sums equal to S-k. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.48),
($q$Ola Ride Longest Consecutive Route$q$,$q$longest-consecutive-sequence$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','hash-set'],$q$## Problem

Given unsorted `checkpoints` array, find the **longest consecutive sequence** length. Solve in O(n).$q$,$q$0 ≤ n ≤ 10^5 | -10^9 ≤ checkpoints[i] ≤ 10^9$q$,$q$[{"input": "checkpoints = [100,4,200,1,3,2]", "output": "4", "explanation": "1,2,3,4"}]$q$::jsonb,$q$[{"input": "[100,4,200,1,3,2]", "expected_output": "4", "is_hidden": false}, {"input": "[0,3,7,2,5,8,4,6,0,1]", "expected_output": "9", "is_hidden": true}]$q$::jsonb,$q$HashSet. For each x where x-1 not in set, count consecutive. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.55),
($q$Hotstar Trending Majority Stream$q$,$q$majority-element$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['arrays','boyer-moore'],$q$## Problem

Given video ID stream `views`, find the video appearing more than `n/2` times (guaranteed to exist).$q$,$q$1 ≤ n ≤ 5×10^4 | Majority element always exists$q$,$q$[{"input": "views = [3,2,3]", "output": "3"}, {"input": "views = [2,2,1,1,1,2,2]", "output": "2"}]$q$::jsonb,$q$[{"input": "[3,2,3]", "expected_output": "3", "is_hidden": false}, {"input": "[2,2,1,1,1,2,2]", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$Boyer-Moore Voting: candidate + count. If count=0, new candidate. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.74),
($q$Myntra Discount Sort Colors$q$,$q$sort-colors$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','two-pointers','dutch-national-flag'],$q$## Problem

Clothing tiers: 0=no discount, 1=10% off, 2=50% off. Sort `tiers` in-place with single pass, O(1) extra.$q$,$q$1 ≤ n ≤ 300 | tiers[i] ∈ {0,1,2}$q$,$q$[{"input": "tiers = [2,0,2,1,1,0]", "output": "[0,0,1,1,2,2]"}]$q$::jsonb,$q$[{"input": "[2,0,2,1,1,0]", "expected_output": "[0,0,1,1,2,2]", "is_hidden": false}, {"input": "[2,0,1]", "expected_output": "[0,1,2]", "is_hidden": true}]$q$::jsonb,$q$Dutch National Flag: lo/mid/hi pointers. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.61),
($q$PhonePe Transaction Kth Largest$q$,$q$kth-largest-element$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','heap','quickselect'],$q$## Problem

Find the **Kth largest** transaction amount in an unsorted list. Not kth distinct.$q$,$q$1 ≤ k ≤ n ≤ 10^4 | -10^4 ≤ transactions[i] ≤ 10^4$q$,$q$[{"input": "transactions = [3,2,1,5,6,4], k = 2", "output": "5"}, {"input": "transactions = [3,2,3,1,2,4,5,5,6], k = 4", "output": "4"}]$q$::jsonb,$q$[{"input": "[3,2,1,5,6,4]\n2", "expected_output": "5", "is_hidden": false}, {"input": "[3,2,3,1,2,4,5,5,6]\n4", "expected_output": "4", "is_hidden": true}]$q$::jsonb,$q$Min-heap of size k. O(n log k). Or Quickselect O(n) avg.$q$,ARRAY['python','java','javascript','go','cpp'],0.58),
($q$BigBasket Delivery Meeting Rooms$q$,$q$meeting-rooms-ii$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','sorting','heap','intervals'],$q$## Problem

Given delivery slot `meetings = [[start,end],...]`, find minimum **conference rooms** needed.$q$,$q$0 ≤ n ≤ 10^4 | 0 ≤ start < end ≤ 10^6$q$,$q$[{"input": "meetings = [[0,30],[5,10],[15,20]]", "output": "2"}]$q$::jsonb,$q$[{"input": "[[0,30],[5,10],[15,20]]", "expected_output": "2", "is_hidden": false}, {"input": "[[7,10],[2,4]]", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$Sort by start. Min-heap of end times. Reuse room if heap.top ≤ start. Size = answer. O(n log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.54),
($q$Amazon India Warehouse Next Permutation$q$,$q$next-permutation$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','permutation'],$q$## Problem

Rearrange `digits` into the lexicographically **next greater permutation** in-place. If largest, rearrange to smallest.$q$,$q$1 ≤ n ≤ 100 | 0 ≤ digits[i] ≤ 9$q$,$q$[{"input": "digits = [1,2,3]", "output": "[1,3,2]"}, {"input": "digits = [3,2,1]", "output": "[1,2,3]"}]$q$::jsonb,$q$[{"input": "[1,2,3]", "expected_output": "[1,3,2]", "is_hidden": false}, {"input": "[3,2,1]", "expected_output": "[1,2,3]", "is_hidden": true}]$q$::jsonb,$q$Find rightmost i where arr[i]<arr[i+1]. Find rightmost j>i where arr[j]>arr[i]. Swap, reverse suffix.$q$,ARRAY['python','java','javascript','go','cpp'],0.44),
($q$Dunzo Delivery Maximum Product Subarray$q$,$q$maximum-product-subarray$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','dynamic-programming'],$q$## Problem

Given efficiency `multipliers` array, find the contiguous subarray with **maximum product**.$q$,$q$1 ≤ n ≤ 2×10^4 | -10 ≤ multipliers[i] ≤ 10$q$,$q$[{"input": "multipliers = [2,3,-2,4]", "output": "6"}, {"input": "multipliers = [-2,0,-1]", "output": "0"}]$q$::jsonb,$q$[{"input": "[2,3,-2,4]", "expected_output": "6", "is_hidden": false}, {"input": "[-2,0,-1]", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$Track curMax and curMin (negatives flip). At each step update both. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.46),
($q$Rapido Biker Find Duplicate$q$,$q$find-the-duplicate-number$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','floyd-cycle'],$q$## Problem

`n+1` integers in range `[1,n]` — one is duplicated. Find it without modifying array, O(1) extra space.$q$,$q$1 ≤ n ≤ 10^5 | Only one duplicate$q$,$q$[{"input": "rider_ids = [1,3,4,2,2]", "output": "2"}, {"input": "rider_ids = [3,1,3,4,2]", "output": "3"}]$q$::jsonb,$q$[{"input": "[1,3,4,2,2]", "expected_output": "2", "is_hidden": false}, {"input": "[3,1,3,4,2]", "expected_output": "3", "is_hidden": true}]$q$::jsonb,$q$Floyd cycle detection treating array as linked list. O(n) time, O(1) space.$q$,ARRAY['python','java','javascript','go','cpp'],0.43),
($q$Set Matrix Zeroes Warehouse Grid$q$,$q$set-matrix-zeroes$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['arrays','matrix'],$q$## Problem

A Warehousing grid represents stock levels. If any cell is `0`, set its **entire row and column** to `0` in-place. Use O(1) extra space.$q$,$q$1 ≤ m,n ≤ 200 | -2^31 ≤ matrix[i][j] ≤ 2^31-1$q$,$q$[{"input": "matrix = [[1,1,1],[1,0,1],[1,1,1]]", "output": "[[1,0,1],[0,0,0],[1,0,1]]"}]$q$::jsonb,$q$[{"input": "[[1,1,1],[1,0,1],[1,1,1]]", "expected_output": "[[1,0,1],[0,0,0],[1,0,1]]", "is_hidden": false}, {"input": "[[0,1,2,0],[3,4,5,2],[1,3,1,5]]", "expected_output": "[[0,0,0,0],[0,4,5,0],[0,3,1,0]]", "is_hidden": true}]$q$::jsonb,$q$Use first row/col as markers. Two passes. O(m×n) time O(1) space.$q$,ARRAY['python','java','javascript','go','cpp'],0.55)
ON CONFLICT (slug) DO NOTHING;