-- STEP 2: Insert problems 1–20
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate) VALUES
('Zomato Order Pair Finder','two-sum','Easy','DSA',ARRAY['arrays','hash-map'],'## Problem

Zomato''s analytics team has a list of delivery order amounts (in rupees) and a target amount `T`. Find the indices of the **two orders** whose amounts add up to exactly `T`. You may assume exactly one valid answer exists, and you cannot use the same order twice.

Return the indices as `[i, j]` where `i < j`.','2 ≤ n ≤ 10^4 | 1 ≤ orders[i] ≤ 10^6 | 1 ≤ T ≤ 2×10^6','[{"input": "orders = [200, 50, 150, 400], T = 350", "output": "[0, 2]", "explanation": "orders[0] + orders[2] = 200 + 150 = 350"}]'::jsonb,'[{"input": "[200,50,150,400]\n350", "expected_output": "[0,2]", "is_hidden": false}, {"input": "[11,2,15,7]\n9", "expected_output": "[1,3]", "is_hidden": true}]'::jsonb,'Use a hash map: for each amount, check if T - amount exists. O(n) time, O(n) space.',ARRAY['python','java','javascript','go','cpp'],0.72),
('BSE Stock Profit Maximizer','best-time-to-buy-sell-stock','Easy','DSA',ARRAY['arrays','greedy'],'## Problem

You are given `prices[i]` = BSE stock price on day `i`. Buy once, sell once. Return the **maximum profit**. If no profit possible, return `0`.','1 ≤ n ≤ 10^5 | 0 ≤ prices[i] ≤ 10^4','[{"input": "prices = [310, 280, 420, 210, 500, 390]", "output": "290", "explanation": "Buy at 210 (day 4), sell at 500 (day 5) = 290"}]'::jsonb,'[{"input": "[310,280,420,210,500,390]", "expected_output": "290", "is_hidden": false}, {"input": "[900,800,700,600]", "expected_output": "0", "is_hidden": true}]'::jsonb,'Track running min price and max profit. Single pass O(n).',ARRAY['python','java','javascript','go','cpp'],0.68),
('Swiggy Rating Maximum Subarray','maximum-subarray','Easy','DSA',ARRAY['arrays','dynamic-programming','kadane'],'## Problem

Swiggy tracks daily net satisfaction scores (can be negative). Given `scores`, find the contiguous subarray with the **largest sum** (Kadane''s algorithm).','1 ≤ n ≤ 10^5 | -10^4 ≤ scores[i] ≤ 10^4','[{"input": "scores = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6", "explanation": "Subarray [4,-1,2,1] = 6"}]'::jsonb,'[{"input": "[-2,1,-3,4,-1,2,1,-5,4]", "expected_output": "6", "is_hidden": false}, {"input": "[1]", "expected_output": "1", "is_hidden": true}]'::jsonb,'cur = max(x, cur+x); best = max(best, cur). O(n).',ARRAY['python','java','javascript','go','cpp'],0.63),
('IRCTC Train Schedule Merger','merge-intervals','Medium','DSA',ARRAY['arrays','sorting','intervals'],'## Problem

IRCTC needs to merge overlapping maintenance windows on a track. Given intervals `[[start,end],...]` in minutes from midnight, return merged non-overlapping intervals.','1 ≤ n ≤ 10^4 | 0 ≤ start ≤ end ≤ 1440','[{"input": "intervals = [[60,90],[80,120],[200,240],[230,300]]", "output": "[[60,120],[200,300]]", "explanation": "[60,90]+[80,120] overlap; [200,240]+[230,300] overlap"}]'::jsonb,'[{"input": "[[60,90],[80,120],[200,240],[230,300]]", "expected_output": "[[60,120],[200,300]]", "is_hidden": false}, {"input": "[[1,4],[4,5]]", "expected_output": "[[1,5]]", "is_hidden": true}]'::jsonb,'Sort by start. Extend last merged end if overlap. O(n log n).',ARRAY['python','java','javascript','go','cpp'],0.56),
('Flipkart Cart Three Sum','three-sum','Medium','DSA',ARRAY['arrays','two-pointers','sorting'],'## Problem

Flipkart offers price adjustments (positive = addition, negative = discount). Find all **unique triplets** from `prices` summing to **zero**.','3 ≤ n ≤ 3000 | -10^5 ≤ prices[i] ≤ 10^5','[{"input": "prices = [-1,0,1,2,-1,-4]", "output": "[[-1,-1,2],[-1,0,1]]"}]'::jsonb,'[{"input": "[-1,0,1,2,-1,-4]", "expected_output": "[[-1,-1,2],[-1,0,1]]", "is_hidden": false}, {"input": "[0,0,0]", "expected_output": "[[0,0,0]]", "is_hidden": true}]'::jsonb,'Sort. For each element, two pointers on rest. Skip duplicates. O(n²).',ARRAY['python','java','javascript','go','cpp'],0.41),
('Paytm Wallet Container Volume','container-with-most-water','Medium','DSA',ARRAY['arrays','two-pointers'],'## Problem

Given `n` wall heights, find two walls that together hold the **most water**. Return maximum water units.','2 ≤ n ≤ 10^5 | 0 ≤ height[i] ≤ 10^4','[{"input": "height = [1,8,6,2,5,4,8,3,7]", "output": "49", "explanation": "Walls at idx 1,8: min(8,7)×7=49"}]'::jsonb,'[{"input": "[1,8,6,2,5,4,8,3,7]", "expected_output": "49", "is_hidden": false}, {"input": "[1,1]", "expected_output": "1", "is_hidden": true}]'::jsonb,'Two pointers from both ends. Move pointer with smaller height. O(n).',ARRAY['python','java','javascript','go','cpp'],0.58),
('Mumbai Monsoon Water Trap','trapping-rain-water','Hard','DSA',ARRAY['arrays','two-pointers','stack'],'## Problem

Mumbai''s drainage engineers mapped city elevation. Given `heights`, compute how many units of rainwater can be trapped after monsoon rains.','1 ≤ n ≤ 2×10^4 | 0 ≤ heights[i] ≤ 10^5','[{"input": "heights = [0,1,0,2,1,0,1,3,2,1,2,1]", "output": "6"}]'::jsonb,'[{"input": "[0,1,0,2,1,0,1,3,2,1,2,1]", "expected_output": "6", "is_hidden": false}, {"input": "[4,2,0,3,2,5]", "expected_output": "9", "is_hidden": true}]'::jsonb,'Two-pointer: leftMax, rightMax. water[i]=min(leftMax,rightMax)-height[i]. O(n) O(1).',ARRAY['python','java','javascript','go','cpp'],0.35),
('OYO Room Booking Jump Game','jump-game','Medium','DSA',ARRAY['arrays','greedy'],'## Problem

`jumps[i]` = max steps from position `i`. Starting at index 0, determine if you can **reach the last index**.','1 ≤ n ≤ 10^4 | 0 ≤ jumps[i] ≤ 10','[{"input": "jumps = [2,3,1,1,4]", "output": "true"}, {"input": "jumps = [3,2,1,0,4]", "output": "false"}]'::jsonb,'[{"input": "[2,3,1,1,4]", "expected_output": "true", "is_hidden": false}, {"input": "[3,2,1,0,4]", "expected_output": "false", "is_hidden": true}]'::jsonb,'Track maxReach. If i > maxReach, return false. O(n).',ARRAY['python','java','javascript','go','cpp'],0.49),
('Nykaa Product Self-Excluding Product','product-of-array-except-self','Medium','DSA',ARRAY['arrays','prefix-product'],'## Problem

Given `prices`, return array where `result[i]` = product of all elements **except** `prices[i]`. No division, O(n).','2 ≤ n ≤ 10^5 | -30 ≤ prices[i] ≤ 30','[{"input": "prices = [1,2,3,4]", "output": "[24,12,8,6]"}]'::jsonb,'[{"input": "[1,2,3,4]", "expected_output": "[24,12,8,6]", "is_hidden": false}, {"input": "[-1,1,0,-3,3]", "expected_output": "[0,0,9,0,0]", "is_hidden": true}]'::jsonb,'Prefix product left-to-right × suffix product right-to-left. O(n) O(1) extra.',ARRAY['python','java','javascript','go','cpp'],0.64),
('Reliance Jio Tower Spiral Read','spiral-matrix','Medium','DSA',ARRAY['arrays','matrix','simulation'],'## Problem

Given an `m×n` grid of signal strengths, return all elements in **clockwise spiral order**.','1 ≤ m,n ≤ 10 | -100 ≤ grid[i][j] ≤ 100','[{"input": "grid = [[1,2,3],[4,5,6],[7,8,9]]", "output": "[1,2,3,6,9,8,7,4,5]"}]'::jsonb,'[{"input": "[[1,2,3],[4,5,6],[7,8,9]]", "expected_output": "[1,2,3,6,9,8,7,4,5]", "is_hidden": false}, {"input": "[[1,2],[3,4]]", "expected_output": "[1,2,4,3]", "is_hidden": true}]'::jsonb,'Peel layers: top row, right col, bottom row, left col. Shrink boundaries. O(m×n).',ARRAY['python','java','javascript','go','cpp'],0.52),
('IndiGo Seat Booking Subarray Sum','subarray-sum-equals-k','Medium','DSA',ARRAY['arrays','hash-map','prefix-sum'],'## Problem

Given loyalty `points` array and target `k`, count **contiguous subarrays** whose sum equals `k`.','1 ≤ n ≤ 2×10^4 | -1000 ≤ points[i] ≤ 1000 | -10^7 ≤ k ≤ 10^7','[{"input": "points = [1,1,1], k = 2", "output": "2"}]'::jsonb,'[{"input": "[1,1,1]\n2", "expected_output": "2", "is_hidden": false}, {"input": "[1,2,3]\n3", "expected_output": "2", "is_hidden": true}]'::jsonb,'Prefix sum + hashmap. For each sum S, count prev sums equal to S-k. O(n).',ARRAY['python','java','javascript','go','cpp'],0.48),
('Ola Ride Longest Consecutive Route','longest-consecutive-sequence','Medium','DSA',ARRAY['arrays','hash-set'],'## Problem

Given unsorted `checkpoints` array, find the **longest consecutive sequence** length. Solve in O(n).','0 ≤ n ≤ 10^5 | -10^9 ≤ checkpoints[i] ≤ 10^9','[{"input": "checkpoints = [100,4,200,1,3,2]", "output": "4", "explanation": "1,2,3,4"}]'::jsonb,'[{"input": "[100,4,200,1,3,2]", "expected_output": "4", "is_hidden": false}, {"input": "[0,3,7,2,5,8,4,6,0,1]", "expected_output": "9", "is_hidden": true}]'::jsonb,'HashSet. For each x where x-1 not in set, count consecutive. O(n).',ARRAY['python','java','javascript','go','cpp'],0.55),
('Hotstar Trending Majority Stream','majority-element','Easy','DSA',ARRAY['arrays','boyer-moore'],'## Problem

Given video ID stream `views`, find the video appearing more than `n/2` times (guaranteed to exist).','1 ≤ n ≤ 5×10^4 | Majority element always exists','[{"input": "views = [3,2,3]", "output": "3"}, {"input": "views = [2,2,1,1,1,2,2]", "output": "2"}]'::jsonb,'[{"input": "[3,2,3]", "expected_output": "3", "is_hidden": false}, {"input": "[2,2,1,1,1,2,2]", "expected_output": "2", "is_hidden": true}]'::jsonb,'Boyer-Moore Voting: candidate + count. If count=0, new candidate. O(n) O(1).',ARRAY['python','java','javascript','go','cpp'],0.74),
('Myntra Discount Sort Colors','sort-colors','Medium','DSA',ARRAY['arrays','two-pointers','dutch-national-flag'],'## Problem

Clothing tiers: 0=no discount, 1=10% off, 2=50% off. Sort `tiers` in-place with single pass, O(1) extra.','1 ≤ n ≤ 300 | tiers[i] ∈ {0,1,2}','[{"input": "tiers = [2,0,2,1,1,0]", "output": "[0,0,1,1,2,2]"}]'::jsonb,'[{"input": "[2,0,2,1,1,0]", "expected_output": "[0,0,1,1,2,2]", "is_hidden": false}, {"input": "[2,0,1]", "expected_output": "[0,1,2]", "is_hidden": true}]'::jsonb,'Dutch National Flag: lo/mid/hi pointers. O(n).',ARRAY['python','java','javascript','go','cpp'],0.61),
('PhonePe Transaction Kth Largest','kth-largest-element','Medium','DSA',ARRAY['arrays','heap','quickselect'],'## Problem

Find the **Kth largest** transaction amount in an unsorted list. Not kth distinct.','1 ≤ k ≤ n ≤ 10^4 | -10^4 ≤ transactions[i] ≤ 10^4','[{"input": "transactions = [3,2,1,5,6,4], k = 2", "output": "5"}, {"input": "transactions = [3,2,3,1,2,4,5,5,6], k = 4", "output": "4"}]'::jsonb,'[{"input": "[3,2,1,5,6,4]\n2", "expected_output": "5", "is_hidden": false}, {"input": "[3,2,3,1,2,4,5,5,6]\n4", "expected_output": "4", "is_hidden": true}]'::jsonb,'Min-heap of size k. O(n log k). Or Quickselect O(n) avg.',ARRAY['python','java','javascript','go','cpp'],0.58),
('BigBasket Delivery Meeting Rooms','meeting-rooms-ii','Medium','DSA',ARRAY['arrays','sorting','heap','intervals'],'## Problem

Given delivery slot `meetings = [[start,end],...]`, find minimum **conference rooms** needed.','0 ≤ n ≤ 10^4 | 0 ≤ start < end ≤ 10^6','[{"input": "meetings = [[0,30],[5,10],[15,20]]", "output": "2"}]'::jsonb,'[{"input": "[[0,30],[5,10],[15,20]]", "expected_output": "2", "is_hidden": false}, {"input": "[[7,10],[2,4]]", "expected_output": "1", "is_hidden": true}]'::jsonb,'Sort by start. Min-heap of end times. Reuse room if heap.top ≤ start. Size = answer. O(n log n).',ARRAY['python','java','javascript','go','cpp'],0.54),
('Amazon India Warehouse Next Permutation','next-permutation','Medium','DSA',ARRAY['arrays','permutation'],'## Problem

Rearrange `digits` into the lexicographically **next greater permutation** in-place. If largest, rearrange to smallest.','1 ≤ n ≤ 100 | 0 ≤ digits[i] ≤ 9','[{"input": "digits = [1,2,3]", "output": "[1,3,2]"}, {"input": "digits = [3,2,1]", "output": "[1,2,3]"}]'::jsonb,'[{"input": "[1,2,3]", "expected_output": "[1,3,2]", "is_hidden": false}, {"input": "[3,2,1]", "expected_output": "[1,2,3]", "is_hidden": true}]'::jsonb,'Find rightmost i where arr[i]<arr[i+1]. Find rightmost j>i where arr[j]>arr[i]. Swap, reverse suffix.',ARRAY['python','java','javascript','go','cpp'],0.44),
('Dunzo Delivery Maximum Product Subarray','maximum-product-subarray','Medium','DSA',ARRAY['arrays','dynamic-programming'],'## Problem

Given efficiency `multipliers` array, find the contiguous subarray with **maximum product**.','1 ≤ n ≤ 2×10^4 | -10 ≤ multipliers[i] ≤ 10','[{"input": "multipliers = [2,3,-2,4]", "output": "6"}, {"input": "multipliers = [-2,0,-1]", "output": "0"}]'::jsonb,'[{"input": "[2,3,-2,4]", "expected_output": "6", "is_hidden": false}, {"input": "[-2,0,-1]", "expected_output": "0", "is_hidden": true}]'::jsonb,'Track curMax and curMin (negatives flip). At each step update both. O(n).',ARRAY['python','java','javascript','go','cpp'],0.46),
('Rapido Biker Find Duplicate','find-the-duplicate-number','Medium','DSA',ARRAY['arrays','floyd-cycle'],'## Problem

`n+1` integers in range `[1,n]` — one is duplicated. Find it without modifying array, O(1) extra space.','1 ≤ n ≤ 10^5 | Only one duplicate','[{"input": "rider_ids = [1,3,4,2,2]", "output": "2"}, {"input": "rider_ids = [3,1,3,4,2]", "output": "3"}]'::jsonb,'[{"input": "[1,3,4,2,2]", "expected_output": "2", "is_hidden": false}, {"input": "[3,1,3,4,2]", "expected_output": "3", "is_hidden": true}]'::jsonb,'Floyd cycle detection treating array as linked list. O(n) time, O(1) space.',ARRAY['python','java','javascript','go','cpp'],0.43),
('Set Matrix Zeroes Warehouse Grid','set-matrix-zeroes','Medium','DSA',ARRAY['arrays','matrix'],'## Problem

A Warehousing grid represents stock levels. If any cell is `0`, set its **entire row and column** to `0` in-place. Use O(1) extra space.','1 ≤ m,n ≤ 200 | -2^31 ≤ matrix[i][j] ≤ 2^31-1','[{"input": "matrix = [[1,1,1],[1,0,1],[1,1,1]]", "output": "[[1,0,1],[0,0,0],[1,0,1]]"}]'::jsonb,'[{"input": "[[1,1,1],[1,0,1],[1,1,1]]", "expected_output": "[[1,0,1],[0,0,0],[1,0,1]]", "is_hidden": false}, {"input": "[[0,1,2,0],[3,4,5,2],[1,3,1,5]]", "expected_output": "[[0,0,0,0],[0,4,5,0],[0,3,1,0]]", "is_hidden": true}]'::jsonb,'Use first row/col as markers. Two passes. O(m×n) time O(1) space.',ARRAY['python','java','javascript','go','cpp'],0.55)
ON CONFLICT (slug) DO NOTHING;