-- STEP 3: Problems 21–40 of 201
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate)
VALUES
($q$Swiggy Search Longest Unique Window$q$,$q$longest-substring-without-repeating$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','sliding-window','hash-map'],$q$## Problem

Find the length of the **longest substring without repeating characters** in search string `s`.$q$,$q$0 ≤ len(s) ≤ 5×10^4 | s consists of printable ASCII$q$,$q$[{"input": "s = \"zomato\"", "output": "5", "explanation": "\"zomat\" length 5, o repeats"}, {"input": "s = \"bbbbb\"", "output": "1"}]$q$::jsonb,$q$[{"input": "\"zomato\"", "expected_output": "5", "is_hidden": false}, {"input": "\"bbbbb\"", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$Sliding window + hashmap of last seen index. Move left past repeat. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.61),
($q$Shaadi.com Profile Anagram Check$q$,$q$valid-anagram$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['strings','hash-map'],$q$## Problem

Determine if strings `s` and `t` are **anagrams** of each other.$q$,$q$1 ≤ len(s),len(t) ≤ 5×10^4 | lowercase English letters$q$,$q$[{"input": "s = \"listen\", t = \"silent\"", "output": "true"}, {"input": "s = \"rat\", t = \"car\"", "output": "false"}]$q$::jsonb,$q$[{"input": "\"anagram\"\n\"nagaram\"", "expected_output": "true", "is_hidden": false}, {"input": "\"rat\"\n\"car\"", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$Count char frequencies in array[26]. Compare. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.71),
($q$BookMyShow Ticket Group Anagrams$q$,$q$group-anagrams$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','hash-map','sorting'],$q$## Problem

Group all strings in `tickets` that are anagrams of each other into sublists.$q$,$q$1 ≤ n ≤ 10^4 | 0 ≤ len(tickets[i]) ≤ 100$q$,$q$[{"input": "tickets = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "output": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]"}]$q$::jsonb,$q$[{"input": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "expected_output": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]", "is_hidden": false}, {"input": "[\"\"]", "expected_output": "[[\"\"]]", "is_hidden": true}]$q$::jsonb,$q$Use sorted string as hashmap key. O(n·k·log k).$q$,ARRAY['python','java','javascript','go','cpp'],0.65),
($q$Zepto QR Code Valid Parentheses$q$,$q$valid-parentheses$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['strings','stack'],$q$## Problem

Given string `s` with only `()[]{}`characters, determine if brackets are **validly matched**.$q$,$q$1 ≤ len(s) ≤ 10^4$q$,$q$[{"input": "s = \"()[]{}\"", "output": "true"}, {"input": "s = \"([)]\"", "output": "false"}]$q$::jsonb,$q$[{"input": "\"()[]{}\"", "expected_output": "true", "is_hidden": false}, {"input": "\"([)]\"", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$Stack: push opening, on closing check top match. Empty at end = valid. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.77),
($q$MakeMyTrip Itinerary Palindrome$q$,$q$longest-palindromic-substring$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','dynamic-programming','expand-around-center'],$q$## Problem

Given string `s`, return the **longest palindromic substring**.$q$,$q$1 ≤ len(s) ≤ 1000$q$,$q$[{"input": "s = \"babad\"", "output": "\"bab\""}, {"input": "s = \"cbbd\"", "output": "\"bb\""}]$q$::jsonb,$q$[{"input": "\"babad\"", "expected_output": "\"bab\"", "is_hidden": false}, {"input": "\"cbbd\"", "expected_output": "\"bb\"", "is_hidden": true}]$q$::jsonb,$q$Expand around each center (odd/even). Track max. O(n²) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.39),
($q$Urban Company Service Keyword Window$q$,$q$minimum-window-substring$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['strings','sliding-window','hash-map'],$q$## Problem

Find the **minimum window substring** of `s` that contains all characters of `t`.$q$,$q$1 ≤ len(s),len(t) ≤ 10^5$q$,$q$[{"input": "s = \"ADOBECODEBANC\", t = \"ABC\"", "output": "\"BANC\""}]$q$::jsonb,$q$[{"input": "\"ADOBECODEBANC\"\n\"ABC\"", "expected_output": "\"BANC\"", "is_hidden": false}, {"input": "\"a\"\n\"a\"", "expected_output": "\"a\"", "is_hidden": true}]$q$::jsonb,$q$Sliding window: expand right until covered, shrink left. Track min length. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.31),
($q$Naukri.com Resume Word Break$q$,$q$word-break$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','dynamic-programming'],$q$## Problem

Return `true` if string `s` can be **segmented** into words all present in `wordDict`.$q$,$q$1 ≤ len(s) ≤ 300 | 1 ≤ len(wordDict) ≤ 1000$q$,$q$[{"input": "s = \"leetcode\", wordDict = [\"leet\",\"code\"]", "output": "true"}, {"input": "s = \"catsandog\", wordDict = [\"cats\",\"dog\",\"and\",\"cat\"]", "output": "false"}]$q$::jsonb,$q$[{"input": "\"leetcode\"\n[\"leet\",\"code\"]", "expected_output": "true", "is_hidden": false}, {"input": "\"catsandog\"\n[\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$dp[i]=true if s[0..i] segmentable. For each i, try all j<i. O(n²).$q$,ARRAY['python','java','javascript','go','cpp'],0.45),
($q$HDFC Bank OTP Decode Ways$q$,$q$decode-ways$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','dynamic-programming'],$q$## Problem

A=1..Z=26. Given digit string `code`, return the **number of ways** to decode it.$q$,$q$1 ≤ len(code) ≤ 100 | Only digits$q$,$q$[{"input": "code = \"226\"", "output": "3", "explanation": "BZ, VF, BBF"}]$q$::jsonb,$q$[{"input": "\"226\"", "expected_output": "3", "is_hidden": false}, {"input": "\"06\"", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$dp[i] = ways for s[0..i-1]. Add dp[i-1] if s[i-1]!='0'; dp[i-2] if s[i-2..i-1] in [10,26]. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.42),
($q$Paytm UPI Handle Longest Common Prefix$q$,$q$longest-common-prefix$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['strings','trie'],$q$## Problem

Find the **longest common prefix** among `handles` array. Return empty string if none.$q$,$q$1 ≤ n ≤ 200 | 0 ≤ len(handles[i]) ≤ 200$q$,$q$[{"input": "handles = [\"flower\",\"flow\",\"flight\"]", "output": "\"fl\""}, {"input": "handles = [\"dog\",\"racecar\",\"car\"]", "output": "\"\""}]$q$::jsonb,$q$[{"input": "[\"flower\",\"flow\",\"flight\"]", "expected_output": "\"fl\"", "is_hidden": false}, {"input": "[\"dog\",\"racecar\",\"car\"]", "expected_output": "\"\"", "is_hidden": true}]$q$::jsonb,$q$Sort array. Compare only first and last string. O(n·m).$q$,ARRAY['python','java','javascript','go','cpp'],0.69),
($q$WhatsApp India Reverse Words$q$,$q$reverse-words-in-string$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','two-pointers'],$q$## Problem

Reverse the order of **words** in string `s`. Strip extra spaces.$q$,$q$1 ≤ len(s) ≤ 10^4$q$,$q$[{"input": "s = \"the sky is blue\"", "output": "\"blue is sky the\""}, {"input": "s = \"  hello world  \"", "output": "\"world hello\""}]$q$::jsonb,$q$[{"input": "\"the sky is blue\"", "expected_output": "\"blue is sky the\"", "is_hidden": false}, {"input": "\"  hello world  \"", "expected_output": "\"world hello\"", "is_hidden": true}]$q$::jsonb,$q$Split on whitespace, reverse list, join. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.59),
($q$Meesho Order Chain Reversal$q$,$q$reverse-linked-list$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['linked-list','recursion'],$q$## Problem

Reverse a singly linked list and return the new head.$q$,$q$0 ≤ n ≤ 5000 | -5000 ≤ val ≤ 5000$q$,$q$[{"input": "head = 1→2→3→4→5", "output": "5→4→3→2→1"}]$q$::jsonb,$q$[{"input": "[1,2,3,4,5]", "expected_output": "[5,4,3,2,1]", "is_hidden": false}, {"input": "[1,2]", "expected_output": "[2,1]", "is_hidden": true}]$q$::jsonb,$q$Iterative: prev=None. While cur: save next, point back, advance. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.78),
($q$CRED Bill Merge Sorted Lists$q$,$q$merge-two-sorted-lists$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['linked-list','recursion'],$q$## Problem

Merge two sorted linked lists into one sorted list.$q$,$q$0 ≤ n,m ≤ 50 | -100 ≤ val ≤ 100$q$,$q$[{"input": "list1 = 1→2→4, list2 = 1→3→4", "output": "1→1→2→3→4→4"}]$q$::jsonb,$q$[{"input": "[1,2,4]\n[1,3,4]", "expected_output": "[1,1,2,3,4,4]", "is_hidden": false}, {"input": "[]\n[]", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$Compare heads, attach smaller, recurse. O(n+m).$q$,ARRAY['python','java','javascript','go','cpp'],0.76),
($q$Ather Scooter Route Cycle Detection$q$,$q$linked-list-cycle$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['linked-list','floyd-cycle'],$q$## Problem

Detect if linked list has a **cycle**. Use O(1) memory.$q$,$q$0 ≤ n ≤ 10^4 | pos is -1 or valid index$q$,$q$[{"input": "head = [3,2,0,-4], pos = 1", "output": "true", "explanation": "Tail connects back to index 1"}]$q$::jsonb,$q$[{"input": "[3,2,0,-4]\n1", "expected_output": "true", "is_hidden": false}, {"input": "[1]\n-1", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$Floyd's: slow 1 step, fast 2 steps. If they meet, cycle. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.73),
($q$Groww Portfolio LRU Cache$q$,$q$lru-cache$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['linked-list','hash-map','design'],$q$## Problem

Design an **LRU Cache** with capacity `k`. `get(key)` and `put(key,value)` both O(1). Evict LRU on overflow.$q$,$q$1 ≤ capacity ≤ 3000 | At most 3×10^4 calls$q$,$q$[{"input": "LRUCache(2); put(1,1); put(2,2); get(1)→1; put(3,3); get(2)→-1", "output": "1, -1"}]$q$::jsonb,$q$[{"input": "cap=2\nput(1,1),put(2,2),get(1),put(3,3),get(2),get(3)", "expected_output": "1,-1,3", "is_hidden": false}, {"input": "cap=1\nput(2,1),get(2),put(3,2),get(2),get(3)", "expected_output": "1,-1,2", "is_hidden": true}]$q$::jsonb,$q$Doubly-linked list + hashmap. Most recent at head. O(1) get/put.$q$,ARRAY['python','java','javascript','go','cpp'],0.38),
($q$Razorpay Payment Add Two Numbers$q$,$q$add-two-numbers$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['linked-list','math'],$q$## Problem

Two numbers stored as reversed linked lists of digits. Add them and return sum as reversed linked list.$q$,$q$1 ≤ n,m ≤ 100 | 0 ≤ digit ≤ 9$q$,$q$[{"input": "l1 = 2→4→3, l2 = 5→6→4", "output": "7→0→8", "explanation": "342 + 465 = 807"}]$q$::jsonb,$q$[{"input": "[2,4,3]\n[5,6,4]", "expected_output": "[7,0,8]", "is_hidden": false}, {"input": "[9,9,9]\n[1]", "expected_output": "[0,0,0,1]", "is_hidden": true}]$q$::jsonb,$q$Traverse both with carry. node = (sum%10), carry = sum//10. O(max(m,n)).$q$,ARRAY['python','java','javascript','go','cpp'],0.51),
($q$Swiggy Delivery Remove Nth From End$q$,$q$remove-nth-node-from-end$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['linked-list','two-pointers'],$q$## Problem

Remove the **nth node from the end** of linked list in one pass.$q$,$q$1 ≤ n ≤ sz ≤ 30$q$,$q$[{"input": "head = 1→2→3→4→5, n = 2", "output": "1→2→3→5"}]$q$::jsonb,$q$[{"input": "[1,2,3,4,5]\n2", "expected_output": "[1,2,3,5]", "is_hidden": false}, {"input": "[1]\n1", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$Two pointers n+1 apart. Move both until fast=None. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.57),
($q$Copy List with Random Pointer$q$,$q$copy-list-with-random-pointer$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['linked-list','hash-map'],$q$## Problem

A linked list where each node has `next` and `random` pointers. Create a **deep copy** of the list.$q$,$q$0 ≤ n ≤ 1000 | -10^4 ≤ val ≤ 10^4 | random points to any node or null$q$,$q$[{"input": "head = [[7,null],[13,0],[11,4],[10,2],[1,0]]", "output": "[[7,null],[13,0],[11,4],[10,2],[1,0]]"}]$q$::jsonb,$q$[{"input": "[[7,null],[13,0],[11,4],[10,2],[1,0]]", "expected_output": "[[7,null],[13,0],[11,4],[10,2],[1,0]]", "is_hidden": false}, {"input": "[[1,1],[2,1]]", "expected_output": "[[1,1],[2,1]]", "is_hidden": true}]$q$::jsonb,$q$Hashmap from original to copy. Two passes: create nodes, then set next and random. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.55),
($q$Vedantu Course Tree Depth$q$,$q$maximum-depth-binary-tree$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['trees','dfs','recursion'],$q$## Problem

Find the **maximum depth** of a binary tree (longest root-to-leaf path).$q$,$q$0 ≤ n ≤ 10^4$q$,$q$[{"input": "root = [3,9,20,null,null,15,7]", "output": "3"}]$q$::jsonb,$q$[{"input": "[3,9,20,null,null,15,7]", "expected_output": "3", "is_hidden": false}, {"input": "[1,null,2]", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$DFS: 1 + max(depth(left), depth(right)). Base: None→0. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.81),
($q$BYJU's Concept Tree Invert$q$,$q$invert-binary-tree$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['trees','dfs'],$q$## Problem

Invert (mirror) a binary tree — swap all left and right children.$q$,$q$0 ≤ n ≤ 100$q$,$q$[{"input": "root = [4,2,7,1,3,6,9]", "output": "[4,7,2,9,6,3,1]"}]$q$::jsonb,$q$[{"input": "[4,2,7,1,3,6,9]", "expected_output": "[4,7,2,9,6,3,1]", "is_hidden": false}, {"input": "[2,1,3]", "expected_output": "[2,3,1]", "is_hidden": true}]$q$::jsonb,$q$Swap children, recurse. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.82),
($q$IIT Ranking BST Validate$q$,$q$validate-binary-search-tree$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','dfs','bst'],$q$## Problem

Validate that a binary tree is a valid BST — each node's value is strictly between all values in its subtrees.$q$,$q$1 ≤ n ≤ 10^4 | -2^31 ≤ val ≤ 2^31-1$q$,$q$[{"input": "root = [2,1,3]", "output": "true"}, {"input": "root = [5,1,4,null,null,3,6]", "output": "false"}]$q$::jsonb,$q$[{"input": "[2,1,3]", "expected_output": "true", "is_hidden": false}, {"input": "[5,1,4,null,null,3,6]", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$DFS with (min,max) bounds. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.52)
ON CONFLICT (slug) DO NOTHING;