-- STEP 3: Insert problems 21–40
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate) VALUES
('Swiggy Search Longest Unique Window','longest-substring-without-repeating','Medium','DSA',ARRAY['strings','sliding-window','hash-map'],'## Problem

Find the length of the **longest substring without repeating characters** in search string `s`.','0 ≤ len(s) ≤ 5×10^4 | s consists of printable ASCII','[{"input": "s = \"zomato\"", "output": "5", "explanation": "\"zomat\" length 5, o repeats"}, {"input": "s = \"bbbbb\"", "output": "1"}]'::jsonb,'[{"input": "\"zomato\"", "expected_output": "5", "is_hidden": false}, {"input": "\"bbbbb\"", "expected_output": "1", "is_hidden": true}]'::jsonb,'Sliding window + hashmap of last seen index. Move left past repeat. O(n).',ARRAY['python','java','javascript','go','cpp'],0.61),
('Shaadi.com Profile Anagram Check','valid-anagram','Easy','DSA',ARRAY['strings','hash-map'],'## Problem

Determine if strings `s` and `t` are **anagrams** of each other.','1 ≤ len(s),len(t) ≤ 5×10^4 | lowercase English letters','[{"input": "s = \"listen\", t = \"silent\"", "output": "true"}, {"input": "s = \"rat\", t = \"car\"", "output": "false"}]'::jsonb,'[{"input": "\"anagram\"\n\"nagaram\"", "expected_output": "true", "is_hidden": false}, {"input": "\"rat\"\n\"car\"", "expected_output": "false", "is_hidden": true}]'::jsonb,'Count char frequencies in array[26]. Compare. O(n).',ARRAY['python','java','javascript','go','cpp'],0.71),
('BookMyShow Ticket Group Anagrams','group-anagrams','Medium','DSA',ARRAY['strings','hash-map','sorting'],'## Problem

Group all strings in `tickets` that are anagrams of each other into sublists.','1 ≤ n ≤ 10^4 | 0 ≤ len(tickets[i]) ≤ 100','[{"input": "tickets = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "output": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]"}]'::jsonb,'[{"input": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "expected_output": "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]", "is_hidden": false}, {"input": "[\"\"]", "expected_output": "[[\"\"]]", "is_hidden": true}]'::jsonb,'Use sorted string as hashmap key. O(n·k·log k).',ARRAY['python','java','javascript','go','cpp'],0.65),
('Zepto QR Code Valid Parentheses','valid-parentheses','Easy','DSA',ARRAY['strings','stack'],'## Problem

Given string `s` with only `()[]{}`characters, determine if brackets are **validly matched**.','1 ≤ len(s) ≤ 10^4','[{"input": "s = \"()[]{}\"", "output": "true"}, {"input": "s = \"([)]\"", "output": "false"}]'::jsonb,'[{"input": "\"()[]{}\"", "expected_output": "true", "is_hidden": false}, {"input": "\"([)]\"", "expected_output": "false", "is_hidden": true}]'::jsonb,'Stack: push opening, on closing check top match. Empty at end = valid. O(n).',ARRAY['python','java','javascript','go','cpp'],0.77),
('MakeMyTrip Itinerary Palindrome','longest-palindromic-substring','Medium','DSA',ARRAY['strings','dynamic-programming','expand-around-center'],'## Problem

Given string `s`, return the **longest palindromic substring**.','1 ≤ len(s) ≤ 1000','[{"input": "s = \"babad\"", "output": "\"bab\""}, {"input": "s = \"cbbd\"", "output": "\"bb\""}]'::jsonb,'[{"input": "\"babad\"", "expected_output": "\"bab\"", "is_hidden": false}, {"input": "\"cbbd\"", "expected_output": "\"bb\"", "is_hidden": true}]'::jsonb,'Expand around each center (odd/even). Track max. O(n²) O(1).',ARRAY['python','java','javascript','go','cpp'],0.39),
('Urban Company Service Keyword Window','minimum-window-substring','Hard','DSA',ARRAY['strings','sliding-window','hash-map'],'## Problem

Find the **minimum window substring** of `s` that contains all characters of `t`.','1 ≤ len(s),len(t) ≤ 10^5','[{"input": "s = \"ADOBECODEBANC\", t = \"ABC\"", "output": "\"BANC\""}]'::jsonb,'[{"input": "\"ADOBECODEBANC\"\n\"ABC\"", "expected_output": "\"BANC\"", "is_hidden": false}, {"input": "\"a\"\n\"a\"", "expected_output": "\"a\"", "is_hidden": true}]'::jsonb,'Sliding window: expand right until covered, shrink left. Track min length. O(n).',ARRAY['python','java','javascript','go','cpp'],0.31),
('Naukri.com Resume Word Break','word-break','Medium','DSA',ARRAY['strings','dynamic-programming'],'## Problem

Return `true` if string `s` can be **segmented** into words all present in `wordDict`.','1 ≤ len(s) ≤ 300 | 1 ≤ len(wordDict) ≤ 1000','[{"input": "s = \"leetcode\", wordDict = [\"leet\",\"code\"]", "output": "true"}, {"input": "s = \"catsandog\", wordDict = [\"cats\",\"dog\",\"and\",\"cat\"]", "output": "false"}]'::jsonb,'[{"input": "\"leetcode\"\n[\"leet\",\"code\"]", "expected_output": "true", "is_hidden": false}, {"input": "\"catsandog\"\n[\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]", "expected_output": "false", "is_hidden": true}]'::jsonb,'dp[i]=true if s[0..i] segmentable. For each i, try all j<i. O(n²).',ARRAY['python','java','javascript','go','cpp'],0.45),
('HDFC Bank OTP Decode Ways','decode-ways','Medium','DSA',ARRAY['strings','dynamic-programming'],'## Problem

A=1..Z=26. Given digit string `code`, return the **number of ways** to decode it.','1 ≤ len(code) ≤ 100 | Only digits','[{"input": "code = \"226\"", "output": "3", "explanation": "BZ, VF, BBF"}]'::jsonb,'[{"input": "\"226\"", "expected_output": "3", "is_hidden": false}, {"input": "\"06\"", "expected_output": "0", "is_hidden": true}]'::jsonb,'dp[i] = ways for s[0..i-1]. Add dp[i-1] if s[i-1]!=''0''; dp[i-2] if s[i-2..i-1] in [10,26]. O(n).',ARRAY['python','java','javascript','go','cpp'],0.42),
('Paytm UPI Handle Longest Common Prefix','longest-common-prefix','Easy','DSA',ARRAY['strings','trie'],'## Problem

Find the **longest common prefix** among `handles` array. Return empty string if none.','1 ≤ n ≤ 200 | 0 ≤ len(handles[i]) ≤ 200','[{"input": "handles = [\"flower\",\"flow\",\"flight\"]", "output": "\"fl\""}, {"input": "handles = [\"dog\",\"racecar\",\"car\"]", "output": "\"\""}]'::jsonb,'[{"input": "[\"flower\",\"flow\",\"flight\"]", "expected_output": "\"fl\"", "is_hidden": false}, {"input": "[\"dog\",\"racecar\",\"car\"]", "expected_output": "\"\"", "is_hidden": true}]'::jsonb,'Sort array. Compare only first and last string. O(n·m).',ARRAY['python','java','javascript','go','cpp'],0.69),
('WhatsApp India Reverse Words','reverse-words-in-string','Medium','DSA',ARRAY['strings','two-pointers'],'## Problem

Reverse the order of **words** in string `s`. Strip extra spaces.','1 ≤ len(s) ≤ 10^4','[{"input": "s = \"the sky is blue\"", "output": "\"blue is sky the\""}, {"input": "s = \"  hello world  \"", "output": "\"world hello\""}]'::jsonb,'[{"input": "\"the sky is blue\"", "expected_output": "\"blue is sky the\"", "is_hidden": false}, {"input": "\"  hello world  \"", "expected_output": "\"world hello\"", "is_hidden": true}]'::jsonb,'Split on whitespace, reverse list, join. O(n).',ARRAY['python','java','javascript','go','cpp'],0.59),
('Meesho Order Chain Reversal','reverse-linked-list','Easy','DSA',ARRAY['linked-list','recursion'],'## Problem

Reverse a singly linked list and return the new head.','0 ≤ n ≤ 5000 | -5000 ≤ val ≤ 5000','[{"input": "head = 1→2→3→4→5", "output": "5→4→3→2→1"}]'::jsonb,'[{"input": "[1,2,3,4,5]", "expected_output": "[5,4,3,2,1]", "is_hidden": false}, {"input": "[1,2]", "expected_output": "[2,1]", "is_hidden": true}]'::jsonb,'Iterative: prev=None. While cur: save next, point back, advance. O(n).',ARRAY['python','java','javascript','go','cpp'],0.78),
('CRED Bill Merge Sorted Lists','merge-two-sorted-lists','Easy','DSA',ARRAY['linked-list','recursion'],'## Problem

Merge two sorted linked lists into one sorted list.','0 ≤ n,m ≤ 50 | -100 ≤ val ≤ 100','[{"input": "list1 = 1→2→4, list2 = 1→3→4", "output": "1→1→2→3→4→4"}]'::jsonb,'[{"input": "[1,2,4]\n[1,3,4]", "expected_output": "[1,1,2,3,4,4]", "is_hidden": false}, {"input": "[]\n[]", "expected_output": "[]", "is_hidden": true}]'::jsonb,'Compare heads, attach smaller, recurse. O(n+m).',ARRAY['python','java','javascript','go','cpp'],0.76),
('Ather Scooter Route Cycle Detection','linked-list-cycle','Easy','DSA',ARRAY['linked-list','floyd-cycle'],'## Problem

Detect if linked list has a **cycle**. Use O(1) memory.','0 ≤ n ≤ 10^4 | pos is -1 or valid index','[{"input": "head = [3,2,0,-4], pos = 1", "output": "true", "explanation": "Tail connects back to index 1"}]'::jsonb,'[{"input": "[3,2,0,-4]\n1", "expected_output": "true", "is_hidden": false}, {"input": "[1]\n-1", "expected_output": "false", "is_hidden": true}]'::jsonb,'Floyd''s: slow 1 step, fast 2 steps. If they meet, cycle. O(n) O(1).',ARRAY['python','java','javascript','go','cpp'],0.73),
('Groww Portfolio LRU Cache','lru-cache','Medium','DSA',ARRAY['linked-list','hash-map','design'],'## Problem

Design an **LRU Cache** with capacity `k`. `get(key)` and `put(key,value)` both O(1). Evict LRU on overflow.','1 ≤ capacity ≤ 3000 | At most 3×10^4 calls','[{"input": "LRUCache(2); put(1,1); put(2,2); get(1)→1; put(3,3); get(2)→-1", "output": "1, -1"}]'::jsonb,'[{"input": "cap=2\nput(1,1),put(2,2),get(1),put(3,3),get(2),get(3)", "expected_output": "1,-1,3", "is_hidden": false}, {"input": "cap=1\nput(2,1),get(2),put(3,2),get(2),get(3)", "expected_output": "1,-1,2", "is_hidden": true}]'::jsonb,'Doubly-linked list + hashmap. Most recent at head. O(1) get/put.',ARRAY['python','java','javascript','go','cpp'],0.38),
('Razorpay Payment Add Two Numbers','add-two-numbers','Medium','DSA',ARRAY['linked-list','math'],'## Problem

Two numbers stored as reversed linked lists of digits. Add them and return sum as reversed linked list.','1 ≤ n,m ≤ 100 | 0 ≤ digit ≤ 9','[{"input": "l1 = 2→4→3, l2 = 5→6→4", "output": "7→0→8", "explanation": "342 + 465 = 807"}]'::jsonb,'[{"input": "[2,4,3]\n[5,6,4]", "expected_output": "[7,0,8]", "is_hidden": false}, {"input": "[9,9,9]\n[1]", "expected_output": "[0,0,0,1]", "is_hidden": true}]'::jsonb,'Traverse both with carry. node = (sum%10), carry = sum//10. O(max(m,n)).',ARRAY['python','java','javascript','go','cpp'],0.51),
('Swiggy Delivery Remove Nth From End','remove-nth-node-from-end','Medium','DSA',ARRAY['linked-list','two-pointers'],'## Problem

Remove the **nth node from the end** of linked list in one pass.','1 ≤ n ≤ sz ≤ 30','[{"input": "head = 1→2→3→4→5, n = 2", "output": "1→2→3→5"}]'::jsonb,'[{"input": "[1,2,3,4,5]\n2", "expected_output": "[1,2,3,5]", "is_hidden": false}, {"input": "[1]\n1", "expected_output": "[]", "is_hidden": true}]'::jsonb,'Two pointers n+1 apart. Move both until fast=None. O(n).',ARRAY['python','java','javascript','go','cpp'],0.57),
('Copy List with Random Pointer','copy-list-with-random-pointer','Medium','DSA',ARRAY['linked-list','hash-map'],'## Problem

A linked list where each node has `next` and `random` pointers. Create a **deep copy** of the list.','0 ≤ n ≤ 1000 | -10^4 ≤ val ≤ 10^4 | random points to any node or null','[{"input": "head = [[7,null],[13,0],[11,4],[10,2],[1,0]]", "output": "[[7,null],[13,0],[11,4],[10,2],[1,0]]"}]'::jsonb,'[{"input": "[[7,null],[13,0],[11,4],[10,2],[1,0]]", "expected_output": "[[7,null],[13,0],[11,4],[10,2],[1,0]]", "is_hidden": false}, {"input": "[[1,1],[2,1]]", "expected_output": "[[1,1],[2,1]]", "is_hidden": true}]'::jsonb,'Hashmap from original to copy. Two passes: create nodes, then set next and random. O(n).',ARRAY['python','java','javascript','go','cpp'],0.55),
('Vedantu Course Tree Depth','maximum-depth-binary-tree','Easy','DSA',ARRAY['trees','dfs','recursion'],'## Problem

Find the **maximum depth** of a binary tree (longest root-to-leaf path).','0 ≤ n ≤ 10^4','[{"input": "root = [3,9,20,null,null,15,7]", "output": "3"}]'::jsonb,'[{"input": "[3,9,20,null,null,15,7]", "expected_output": "3", "is_hidden": false}, {"input": "[1,null,2]", "expected_output": "2", "is_hidden": true}]'::jsonb,'DFS: 1 + max(depth(left), depth(right)). Base: None→0. O(n).',ARRAY['python','java','javascript','go','cpp'],0.81),
('BYJU''s Concept Tree Invert','invert-binary-tree','Easy','DSA',ARRAY['trees','dfs'],'## Problem

Invert (mirror) a binary tree — swap all left and right children.','0 ≤ n ≤ 100','[{"input": "root = [4,2,7,1,3,6,9]", "output": "[4,7,2,9,6,3,1]"}]'::jsonb,'[{"input": "[4,2,7,1,3,6,9]", "expected_output": "[4,7,2,9,6,3,1]", "is_hidden": false}, {"input": "[2,1,3]", "expected_output": "[2,3,1]", "is_hidden": true}]'::jsonb,'Swap children, recurse. O(n).',ARRAY['python','java','javascript','go','cpp'],0.82),
('IIT Ranking BST Validate','validate-binary-search-tree','Medium','DSA',ARRAY['trees','dfs','bst'],'## Problem

Validate that a binary tree is a valid BST — each node''s value is strictly between all values in its subtrees.','1 ≤ n ≤ 10^4 | -2^31 ≤ val ≤ 2^31-1','[{"input": "root = [2,1,3]", "output": "true"}, {"input": "root = [5,1,4,null,null,3,6]", "output": "false"}]'::jsonb,'[{"input": "[2,1,3]", "expected_output": "true", "is_hidden": false}, {"input": "[5,1,4,null,null,3,6]", "expected_output": "false", "is_hidden": true}]'::jsonb,'DFS with (min,max) bounds. O(n).',ARRAY['python','java','javascript','go','cpp'],0.52)
ON CONFLICT (slug) DO NOTHING;