-- STEP 4: Problems 41–60 of 201
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate)
VALUES
($q$Infosys Org Chart LCA$q$,$q$lowest-common-ancestor-bst$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','bst','dfs'],$q$## Problem

In a BST, find the **Lowest Common Ancestor** of nodes `p` and `q`.$q$,$q$2 ≤ n ≤ 10^5 | p and q both exist$q$,$q$[{"input": "root = [6,2,8,0,4,7,9], p=2, q=8", "output": "6"}, {"input": "root = [6,2,8,0,4,7,9], p=2, q=4", "output": "2"}]$q$::jsonb,$q$[{"input": "[6,2,8,0,4,7,9]\n2\n8", "expected_output": "6", "is_hidden": false}, {"input": "[6,2,8,0,4,7,9]\n2\n4", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$If both < node go left; if both > go right; else current is LCA. O(h).$q$,ARRAY['python','java','javascript','go','cpp'],0.65),
($q$Taj Hotel Floor Level Order$q$,$q$binary-tree-level-order-traversal$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','bfs','queue'],$q$## Problem

Return the **level-order traversal** of a binary tree as nested sublists.$q$,$q$0 ≤ n ≤ 2000$q$,$q$[{"input": "root = [3,9,20,null,null,15,7]", "output": "[[3],[9,20],[15,7]]"}]$q$::jsonb,$q$[{"input": "[3,9,20,null,null,15,7]", "expected_output": "[[3],[9,20],[15,7]]", "is_hidden": false}, {"input": "[1]", "expected_output": "[[1]]", "is_hidden": true}]$q$::jsonb,$q$BFS with queue. Record level size, process exactly that many. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.69),
($q$Juspay Path Sum Problem$q$,$q$path-sum$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['trees','dfs'],$q$## Problem

Return `true` if there is a **root-to-leaf path** summing to `targetSum`.$q$,$q$0 ≤ n ≤ 5000 | -1000 ≤ val,targetSum ≤ 1000$q$,$q$[{"input": "root = [5,4,8,11,null,13,4,7,2], targetSum=22", "output": "true", "explanation": "5→4→11→2=22"}]$q$::jsonb,$q$[{"input": "[5,4,8,11,null,13,4,7,2,null,null,null,1]\n22", "expected_output": "true", "is_hidden": false}, {"input": "[1,2,3]\n5", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$DFS subtract val. At leaf check remaining==0. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.7),
($q$Ola Maps Right Side Tree View$q$,$q$binary-tree-right-side-view$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','bfs'],$q$## Problem

Return values of nodes visible from the **right side** of a binary tree (rightmost per level).$q$,$q$0 ≤ n ≤ 100$q$,$q$[{"input": "root = [1,2,3,null,5,null,4]", "output": "[1,3,4]"}]$q$::jsonb,$q$[{"input": "[1,2,3,null,5,null,4]", "expected_output": "[1,3,4]", "is_hidden": false}, {"input": "[1,null,3]", "expected_output": "[1,3]", "is_hidden": true}]$q$::jsonb,$q$BFS level order: last element of each level. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.68),
($q$Nagarro Binary Tree Max Path$q$,$q$binary-tree-maximum-path-sum$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['trees','dfs','dynamic-programming'],$q$## Problem

A **path** can go through any nodes. Find the **maximum path sum** (at least one node).$q$,$q$1 ≤ n ≤ 3×10^4 | -1000 ≤ val ≤ 1000$q$,$q$[{"input": "root = [-10,9,20,null,null,15,7]", "output": "42", "explanation": "Path 15→20→7"}]$q$::jsonb,$q$[{"input": "[-10,9,20,null,null,15,7]", "expected_output": "42", "is_hidden": false}, {"input": "[1,2,3]", "expected_output": "6", "is_hidden": true}]$q$::jsonb,$q$DFS returns max single-path gain. Update global max with left+val+right. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.33),
($q$BST Kth Smallest Element$q$,$q$kth-smallest-in-bst$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','bst','dfs'],$q$## Problem

Given a BST and integer `k`, return the **kth smallest** element.$q$,$q$1 ≤ k ≤ n ≤ 10^4 | 0 ≤ val ≤ 10^4$q$,$q$[{"input": "root = [3,1,4,null,2], k=1", "output": "1"}, {"input": "root = [5,3,6,2,4,null,null,1], k=3", "output": "3"}]$q$::jsonb,$q$[{"input": "[3,1,4,null,2]\n1", "expected_output": "1", "is_hidden": false}, {"input": "[5,3,6,2,4,null,null,1]\n3", "expected_output": "3", "is_hidden": true}]$q$::jsonb,$q$In-order traversal (iterative or recursive). k-th visited node. O(h+k).$q$,ARRAY['python','java','javascript','go','cpp'],0.71),
($q$Sorted Array to BST Construction$q$,$q$sorted-array-to-bst$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['trees','dfs','divide-conquer'],$q$## Problem

Convert a sorted `nums` array into a **height-balanced BST**.$q$,$q$1 ≤ n ≤ 10^4 | -10^4 ≤ nums[i] ≤ 10^4 | nums is sorted ascending$q$,$q$[{"input": "nums = [-10,-3,0,5,9]", "output": "[0,-3,9,-10,null,5]"}]$q$::jsonb,$q$[{"input": "[-10,-3,0,5,9]", "expected_output": "[0,-3,9,-10,null,5]", "is_hidden": false}, {"input": "[1,3]", "expected_output": "[3,1]", "is_hidden": true}]$q$::jsonb,$q$Recursively use mid as root, left half as left subtree, right half as right. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.77),
($q$Kerala Backwaters Island Counter$q$,$q$number-of-islands$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','dfs','bfs','union-find'],$q$## Problem

Given `m×n` grid of '1' (land) and '0' (water), count the **number of islands** (connected land groups).$q$,$q$1 ≤ m,n ≤ 300 | grid[i][j] ∈ {'0','1'}$q$,$q$[{"input": "grid = [[\"1\",\"1\",\"0\"],[\"0\",\"1\",\"0\"],[\"0\",\"0\",\"1\"]]", "output": "2"}]$q$::jsonb,$q$[{"input": "[[\"1\",\"1\",\"0\"],[\"0\",\"1\",\"0\"],[\"0\",\"0\",\"1\"]]", "expected_output": "2", "is_hidden": false}, {"input": "[[\"1\",\"1\",\"1\"],[\"1\",\"1\",\"1\"]]", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$DFS/BFS from each unvisited '1', mark connected. Count DFS calls. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.57),
($q$UPSC Exam Course Schedule$q$,$q$course-schedule$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','topological-sort','cycle-detection'],$q$## Problem

`n` subjects with `prerequisites[i]=[a,b]` meaning b before a. Can you finish all? (Detect cycle in directed graph.)$q$,$q$1 ≤ n ≤ 2000 | 0 ≤ prerequisites.length ≤ 5000$q$,$q$[{"input": "n=2, prerequisites=[[1,0]]", "output": "true"}, {"input": "n=2, prerequisites=[[1,0],[0,1]]", "output": "false"}]$q$::jsonb,$q$[{"input": "2\n[[1,0]]", "expected_output": "true", "is_hidden": false}, {"input": "2\n[[1,0],[0,1]]", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$DFS cycle detection with 3 states. O(V+E).$q$,ARRAY['python','java','javascript','go','cpp'],0.48),
($q$Course Schedule II Order$q$,$q$course-schedule-ii$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','topological-sort'],$q$## Problem

Return a valid **order** to finish all courses given prerequisites. If impossible, return empty array.$q$,$q$1 ≤ n ≤ 2000 | 0 ≤ prerequisites.length ≤ 5000$q$,$q$[{"input": "n=4, prerequisites=[[1,0],[2,0],[3,1],[3,2]]", "output": "[0,1,2,3]"}]$q$::jsonb,$q$[{"input": "4\n[[1,0],[2,0],[3,1],[3,2]]", "expected_output": "[0,1,2,3]", "is_hidden": false}, {"input": "2\n[[1,0]]", "expected_output": "[0,1]", "is_hidden": true}]$q$::jsonb,$q$Kahn's algorithm (BFS) or DFS topological sort. Append to result in reverse finish order. O(V+E).$q$,ARRAY['python','java','javascript','go','cpp'],0.51),
($q$Hyderabad Metro Network Delay$q$,$q$network-delay-time$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','dijkstra','shortest-path'],$q$## Problem

Given `n` stations, `times[i]=[src,dst,time]`, starting station `k`, return **min time** to reach all stations. Return -1 if impossible.$q$,$q$1 ≤ k ≤ n ≤ 100 | 1 ≤ times.length ≤ 6000$q$,$q$[{"input": "times=[[2,1,1],[2,3,1],[3,4,1]], n=4, k=2", "output": "2"}]$q$::jsonb,$q$[{"input": "[[2,1,1],[2,3,1],[3,4,1]]\n4\n2", "expected_output": "2", "is_hidden": false}, {"input": "[[1,2,1]]\n2\n2", "expected_output": "-1", "is_hidden": true}]$q$::jsonb,$q$Dijkstra from k. Answer = max dist. If any inf, return -1. O(E log V).$q$,ARRAY['python','java','javascript','go','cpp'],0.51),
($q$Bangalore Traffic Rotting Mangoes$q$,$q$rotting-oranges$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','bfs','matrix'],$q$## Problem

Grid: 0=empty, 1=fresh mango, 2=rotten. Each minute fresh adjacent to rotten rots. Return min minutes, or -1.$q$,$q$1 ≤ m,n ≤ 10 | grid[i][j] ∈ {0,1,2}$q$,$q$[{"input": "grid = [[2,1,1],[1,1,0],[0,1,1]]", "output": "4"}]$q$::jsonb,$q$[{"input": "[[2,1,1],[1,1,0],[0,1,1]]", "expected_output": "4", "is_hidden": false}, {"input": "[[2,1,1],[0,1,1],[1,0,1]]", "expected_output": "-1", "is_hidden": true}]$q$::jsonb,$q$Multi-source BFS from all rotten. Minutes = BFS levels. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.56),
($q$Indian Railways Cheapest Flight$q$,$q$cheapest-flights-within-k-stops$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','bellman-ford','dynamic-programming'],$q$## Problem

Find **cheapest price** from `src` to `dst` with at most `k` stops. Return -1 if impossible.$q$,$q$1 ≤ n ≤ 100 | 0 ≤ flights.length ≤ 6000 | 0 ≤ k ≤ n-1$q$,$q$[{"input": "n=3, flights=[[0,1,100],[1,2,100],[0,2,500]], src=0, dst=2, k=1", "output": "200"}]$q$::jsonb,$q$[{"input": "3\n[[0,1,100],[1,2,100],[0,2,500]]\n0\n2\n1", "expected_output": "200", "is_hidden": false}, {"input": "3\n[[0,1,100],[1,2,100],[0,2,500]]\n0\n2\n0", "expected_output": "500", "is_hidden": true}]$q$::jsonb,$q$Bellman-Ford k+1 rounds. Copy prev distances per round. O(k×E).$q$,ARRAY['python','java','javascript','go','cpp'],0.4),
($q$Pacific Atlantic Water Flow$q$,$q$pacific-atlantic-water-flow$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','dfs','bfs','matrix'],$q$## Problem

An island grid: water flows to Pacific (top/left edges) or Atlantic (bottom/right edges) if it can reach lower/equal adjacent cells. Find cells that can flow to **both oceans**.$q$,$q$1 ≤ m,n ≤ 200 | 0 ≤ heights[i][j] ≤ 10^5$q$,$q$[{"input": "heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", "output": "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]"}]$q$::jsonb,$q$[{"input": "[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", "expected_output": "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]", "is_hidden": false}, {"input": "[[1]]", "expected_output": "[[0,0]]", "is_hidden": true}]$q$::jsonb,$q$BFS/DFS from each ocean's border going uphill. Intersection = answer. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.49),
($q$Delhi Metro Surrounded Regions$q$,$q$surrounded-regions$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','dfs','bfs'],$q$## Problem

Given grid of 'X' and 'O', capture all 'O' regions **completely surrounded** by 'X' (4-directionally). Border-connected 'O's are not captured.$q$,$q$1 ≤ m,n ≤ 200 | grid[i][j] ∈ {'X','O'}$q$,$q$[{"input": "board = [[\"X\",\"X\",\"X\"],[\"X\",\"O\",\"X\"],[\"X\",\"X\",\"X\"]]", "output": "[[\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\"]]"}]$q$::jsonb,$q$[{"input": "[[\"X\",\"X\",\"X\"],[\"X\",\"O\",\"X\"],[\"X\",\"X\",\"X\"]]", "expected_output": "[[\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\"]]", "is_hidden": false}, {"input": "[[\"X\"]]", "expected_output": "[[\"X\"]]", "is_hidden": true}]$q$::jsonb,$q$DFS from all border 'O's, mark safe. Then flip remaining 'O' to 'X'. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.41),
($q$Stairs to ISRO Launch Pad$q$,$q$climbing-stairs$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['dynamic-programming','fibonacci'],$q$## Problem

`n` step launch pad. Climb 1 or 2 steps at a time. How many **distinct ways** to reach top?$q$,$q$1 ≤ n ≤ 45$q$,$q$[{"input": "n = 3", "output": "3", "explanation": "1+1+1, 1+2, 2+1"}, {"input": "n = 2", "output": "2"}]$q$::jsonb,$q$[{"input": "3", "expected_output": "3", "is_hidden": false}, {"input": "10", "expected_output": "89", "is_hidden": true}]$q$::jsonb,$q$dp[i]=dp[i-1]+dp[i-2]. Fibonacci. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.83),
($q$Thief Looting Delhi Markets$q$,$q$house-robber$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['dynamic-programming'],$q$## Problem

Rob non-adjacent stalls. Given `money[i]` per stall, return **maximum money** without triggering alarms.$q$,$q$1 ≤ n ≤ 100 | 0 ≤ money[i] ≤ 400$q$,$q$[{"input": "money = [1,2,3,1]", "output": "4"}, {"input": "money = [2,7,9,3,1]", "output": "12"}]$q$::jsonb,$q$[{"input": "[1,2,3,1]", "expected_output": "4", "is_hidden": false}, {"input": "[2,7,9,3,1]", "expected_output": "12", "is_hidden": true}]$q$::jsonb,$q$dp[i]=max(dp[i-1], dp[i-2]+money[i]). O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.76),
($q$House Robber Circular Market$q$,$q$house-robber-ii$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming'],$q$## Problem

Now the stalls form a **circle** (first and last are adjacent). Return max money.$q$,$q$1 ≤ n ≤ 100 | 0 ≤ money[i] ≤ 1000$q$,$q$[{"input": "money = [2,3,2]", "output": "3"}, {"input": "money = [1,2,3,1]", "output": "4"}]$q$::jsonb,$q$[{"input": "[2,3,2]", "expected_output": "3", "is_hidden": false}, {"input": "[1,2,3,1]", "expected_output": "4", "is_hidden": true}]$q$::jsonb,$q$Run House Robber on [0..n-2] and [1..n-1], take max. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.45),
($q$RBI Coin Change Minimum$q$,$q$coin-change$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','greedy'],$q$## Problem

Given coin `denominations` and `amount`, find **minimum coins** to make amount. Return -1 if impossible.$q$,$q$1 ≤ len(coins) ≤ 12 | 1 ≤ coins[i] ≤ 2^31-1 | 0 ≤ amount ≤ 10^4$q$,$q$[{"input": "coins = [1,5,6,9], amount = 11", "output": "2", "explanation": "5+6=11"}, {"input": "coins = [2], amount = 3", "output": "-1"}]$q$::jsonb,$q$[{"input": "[1,5,6,9]\n11", "expected_output": "2", "is_hidden": false}, {"input": "[2]\n3", "expected_output": "-1", "is_hidden": true}]$q$::jsonb,$q$dp[i]=min coins for amount i. For each amount try each coin. O(amount×coins).$q$,ARRAY['python','java','javascript','go','cpp'],0.5),
($q$NSE Stock Longest Increasing Sequence$q$,$q$longest-increasing-subsequence$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','binary-search'],$q$## Problem

Find the length of the **longest strictly increasing subsequence** in `prices` array.$q$,$q$1 ≤ n ≤ 2500 | -10^4 ≤ prices[i] ≤ 10^4$q$,$q$[{"input": "prices = [10,9,2,5,3,7,101,18]", "output": "4", "explanation": "[2,3,7,18]"}]$q$::jsonb,$q$[{"input": "[10,9,2,5,3,7,101,18]", "expected_output": "4", "is_hidden": false}, {"input": "[0,1,0,3,2,3]", "expected_output": "4", "is_hidden": true}]$q$::jsonb,$q$O(n²) DP or O(n log n) patience sorting with binary search on tails array.$q$,ARRAY['python','java','javascript','go','cpp'],0.53)
ON CONFLICT (slug) DO NOTHING;