-- STEP 4: Insert problems 41–60
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate) VALUES
('Infosys Org Chart LCA','lowest-common-ancestor-bst','Medium','DSA',ARRAY['trees','bst','dfs'],'## Problem

In a BST, find the **Lowest Common Ancestor** of nodes `p` and `q`.','2 ≤ n ≤ 10^5 | p and q both exist','[{"input": "root = [6,2,8,0,4,7,9], p=2, q=8", "output": "6"}, {"input": "root = [6,2,8,0,4,7,9], p=2, q=4", "output": "2"}]'::jsonb,'[{"input": "[6,2,8,0,4,7,9]\n2\n8", "expected_output": "6", "is_hidden": false}, {"input": "[6,2,8,0,4,7,9]\n2\n4", "expected_output": "2", "is_hidden": true}]'::jsonb,'If both < node go left; if both > go right; else current is LCA. O(h).',ARRAY['python','java','javascript','go','cpp'],0.65),
('Taj Hotel Floor Level Order','binary-tree-level-order-traversal','Medium','DSA',ARRAY['trees','bfs','queue'],'## Problem

Return the **level-order traversal** of a binary tree as nested sublists.','0 ≤ n ≤ 2000','[{"input": "root = [3,9,20,null,null,15,7]", "output": "[[3],[9,20],[15,7]]"}]'::jsonb,'[{"input": "[3,9,20,null,null,15,7]", "expected_output": "[[3],[9,20],[15,7]]", "is_hidden": false}, {"input": "[1]", "expected_output": "[[1]]", "is_hidden": true}]'::jsonb,'BFS with queue. Record level size, process exactly that many. O(n).',ARRAY['python','java','javascript','go','cpp'],0.69),
('Juspay Path Sum Problem','path-sum','Easy','DSA',ARRAY['trees','dfs'],'## Problem

Return `true` if there is a **root-to-leaf path** summing to `targetSum`.','0 ≤ n ≤ 5000 | -1000 ≤ val,targetSum ≤ 1000','[{"input": "root = [5,4,8,11,null,13,4,7,2], targetSum=22", "output": "true", "explanation": "5→4→11→2=22"}]'::jsonb,'[{"input": "[5,4,8,11,null,13,4,7,2,null,null,null,1]\n22", "expected_output": "true", "is_hidden": false}, {"input": "[1,2,3]\n5", "expected_output": "false", "is_hidden": true}]'::jsonb,'DFS subtract val. At leaf check remaining==0. O(n).',ARRAY['python','java','javascript','go','cpp'],0.7),
('Ola Maps Right Side Tree View','binary-tree-right-side-view','Medium','DSA',ARRAY['trees','bfs'],'## Problem

Return values of nodes visible from the **right side** of a binary tree (rightmost per level).','0 ≤ n ≤ 100','[{"input": "root = [1,2,3,null,5,null,4]", "output": "[1,3,4]"}]'::jsonb,'[{"input": "[1,2,3,null,5,null,4]", "expected_output": "[1,3,4]", "is_hidden": false}, {"input": "[1,null,3]", "expected_output": "[1,3]", "is_hidden": true}]'::jsonb,'BFS level order: last element of each level. O(n).',ARRAY['python','java','javascript','go','cpp'],0.68),
('Nagarro Binary Tree Max Path','binary-tree-maximum-path-sum','Hard','DSA',ARRAY['trees','dfs','dynamic-programming'],'## Problem

A **path** can go through any nodes. Find the **maximum path sum** (at least one node).','1 ≤ n ≤ 3×10^4 | -1000 ≤ val ≤ 1000','[{"input": "root = [-10,9,20,null,null,15,7]", "output": "42", "explanation": "Path 15→20→7"}]'::jsonb,'[{"input": "[-10,9,20,null,null,15,7]", "expected_output": "42", "is_hidden": false}, {"input": "[1,2,3]", "expected_output": "6", "is_hidden": true}]'::jsonb,'DFS returns max single-path gain. Update global max with left+val+right. O(n).',ARRAY['python','java','javascript','go','cpp'],0.33),
('BST Kth Smallest Element','kth-smallest-in-bst','Medium','DSA',ARRAY['trees','bst','dfs'],'## Problem

Given a BST and integer `k`, return the **kth smallest** element.','1 ≤ k ≤ n ≤ 10^4 | 0 ≤ val ≤ 10^4','[{"input": "root = [3,1,4,null,2], k=1", "output": "1"}, {"input": "root = [5,3,6,2,4,null,null,1], k=3", "output": "3"}]'::jsonb,'[{"input": "[3,1,4,null,2]\n1", "expected_output": "1", "is_hidden": false}, {"input": "[5,3,6,2,4,null,null,1]\n3", "expected_output": "3", "is_hidden": true}]'::jsonb,'In-order traversal (iterative or recursive). k-th visited node. O(h+k).',ARRAY['python','java','javascript','go','cpp'],0.71),
('Sorted Array to BST Construction','sorted-array-to-bst','Easy','DSA',ARRAY['trees','dfs','divide-conquer'],'## Problem

Convert a sorted `nums` array into a **height-balanced BST**.','1 ≤ n ≤ 10^4 | -10^4 ≤ nums[i] ≤ 10^4 | nums is sorted ascending','[{"input": "nums = [-10,-3,0,5,9]", "output": "[0,-3,9,-10,null,5]"}]'::jsonb,'[{"input": "[-10,-3,0,5,9]", "expected_output": "[0,-3,9,-10,null,5]", "is_hidden": false}, {"input": "[1,3]", "expected_output": "[3,1]", "is_hidden": true}]'::jsonb,'Recursively use mid as root, left half as left subtree, right half as right. O(n).',ARRAY['python','java','javascript','go','cpp'],0.77),
('Kerala Backwaters Island Counter','number-of-islands','Medium','DSA',ARRAY['graphs','dfs','bfs','union-find'],'## Problem

Given `m×n` grid of ''1'' (land) and ''0'' (water), count the **number of islands** (connected land groups).','1 ≤ m,n ≤ 300 | grid[i][j] ∈ {''0'',''1''}','[{"input": "grid = [[\"1\",\"1\",\"0\"],[\"0\",\"1\",\"0\"],[\"0\",\"0\",\"1\"]]", "output": "2"}]'::jsonb,'[{"input": "[[\"1\",\"1\",\"0\"],[\"0\",\"1\",\"0\"],[\"0\",\"0\",\"1\"]]", "expected_output": "2", "is_hidden": false}, {"input": "[[\"1\",\"1\",\"1\"],[\"1\",\"1\",\"1\"]]", "expected_output": "1", "is_hidden": true}]'::jsonb,'DFS/BFS from each unvisited ''1'', mark connected. Count DFS calls. O(m×n).',ARRAY['python','java','javascript','go','cpp'],0.57),
('UPSC Exam Course Schedule','course-schedule','Medium','DSA',ARRAY['graphs','topological-sort','cycle-detection'],'## Problem

`n` subjects with `prerequisites[i]=[a,b]` meaning b before a. Can you finish all? (Detect cycle in directed graph.)','1 ≤ n ≤ 2000 | 0 ≤ prerequisites.length ≤ 5000','[{"input": "n=2, prerequisites=[[1,0]]", "output": "true"}, {"input": "n=2, prerequisites=[[1,0],[0,1]]", "output": "false"}]'::jsonb,'[{"input": "2\n[[1,0]]", "expected_output": "true", "is_hidden": false}, {"input": "2\n[[1,0],[0,1]]", "expected_output": "false", "is_hidden": true}]'::jsonb,'DFS cycle detection with 3 states. O(V+E).',ARRAY['python','java','javascript','go','cpp'],0.48),
('Course Schedule II Order','course-schedule-ii','Medium','DSA',ARRAY['graphs','topological-sort'],'## Problem

Return a valid **order** to finish all courses given prerequisites. If impossible, return empty array.','1 ≤ n ≤ 2000 | 0 ≤ prerequisites.length ≤ 5000','[{"input": "n=4, prerequisites=[[1,0],[2,0],[3,1],[3,2]]", "output": "[0,1,2,3]"}]'::jsonb,'[{"input": "4\n[[1,0],[2,0],[3,1],[3,2]]", "expected_output": "[0,1,2,3]", "is_hidden": false}, {"input": "2\n[[1,0]]", "expected_output": "[0,1]", "is_hidden": true}]'::jsonb,'Kahn''s algorithm (BFS) or DFS topological sort. Append to result in reverse finish order. O(V+E).',ARRAY['python','java','javascript','go','cpp'],0.51),
('Hyderabad Metro Network Delay','network-delay-time','Medium','DSA',ARRAY['graphs','dijkstra','shortest-path'],'## Problem

Given `n` stations, `times[i]=[src,dst,time]`, starting station `k`, return **min time** to reach all stations. Return -1 if impossible.','1 ≤ k ≤ n ≤ 100 | 1 ≤ times.length ≤ 6000','[{"input": "times=[[2,1,1],[2,3,1],[3,4,1]], n=4, k=2", "output": "2"}]'::jsonb,'[{"input": "[[2,1,1],[2,3,1],[3,4,1]]\n4\n2", "expected_output": "2", "is_hidden": false}, {"input": "[[1,2,1]]\n2\n2", "expected_output": "-1", "is_hidden": true}]'::jsonb,'Dijkstra from k. Answer = max dist. If any inf, return -1. O(E log V).',ARRAY['python','java','javascript','go','cpp'],0.51),
('Bangalore Traffic Rotting Mangoes','rotting-oranges','Medium','DSA',ARRAY['graphs','bfs','matrix'],'## Problem

Grid: 0=empty, 1=fresh mango, 2=rotten. Each minute fresh adjacent to rotten rots. Return min minutes, or -1.','1 ≤ m,n ≤ 10 | grid[i][j] ∈ {0,1,2}','[{"input": "grid = [[2,1,1],[1,1,0],[0,1,1]]", "output": "4"}]'::jsonb,'[{"input": "[[2,1,1],[1,1,0],[0,1,1]]", "expected_output": "4", "is_hidden": false}, {"input": "[[2,1,1],[0,1,1],[1,0,1]]", "expected_output": "-1", "is_hidden": true}]'::jsonb,'Multi-source BFS from all rotten. Minutes = BFS levels. O(m×n).',ARRAY['python','java','javascript','go','cpp'],0.56),
('Indian Railways Cheapest Flight','cheapest-flights-within-k-stops','Medium','DSA',ARRAY['graphs','bellman-ford','dynamic-programming'],'## Problem

Find **cheapest price** from `src` to `dst` with at most `k` stops. Return -1 if impossible.','1 ≤ n ≤ 100 | 0 ≤ flights.length ≤ 6000 | 0 ≤ k ≤ n-1','[{"input": "n=3, flights=[[0,1,100],[1,2,100],[0,2,500]], src=0, dst=2, k=1", "output": "200"}]'::jsonb,'[{"input": "3\n[[0,1,100],[1,2,100],[0,2,500]]\n0\n2\n1", "expected_output": "200", "is_hidden": false}, {"input": "3\n[[0,1,100],[1,2,100],[0,2,500]]\n0\n2\n0", "expected_output": "500", "is_hidden": true}]'::jsonb,'Bellman-Ford k+1 rounds. Copy prev distances per round. O(k×E).',ARRAY['python','java','javascript','go','cpp'],0.4),
('Pacific Atlantic Water Flow','pacific-atlantic-water-flow','Medium','DSA',ARRAY['graphs','dfs','bfs','matrix'],'## Problem

An island grid: water flows to Pacific (top/left edges) or Atlantic (bottom/right edges) if it can reach lower/equal adjacent cells. Find cells that can flow to **both oceans**.','1 ≤ m,n ≤ 200 | 0 ≤ heights[i][j] ≤ 10^5','[{"input": "heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", "output": "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]"}]'::jsonb,'[{"input": "[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", "expected_output": "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]", "is_hidden": false}, {"input": "[[1]]", "expected_output": "[[0,0]]", "is_hidden": true}]'::jsonb,'BFS/DFS from each ocean''s border going uphill. Intersection = answer. O(m×n).',ARRAY['python','java','javascript','go','cpp'],0.49),
('Delhi Metro Surrounded Regions','surrounded-regions','Medium','DSA',ARRAY['graphs','dfs','bfs'],'## Problem

Given grid of ''X'' and ''O'', capture all ''O'' regions **completely surrounded** by ''X'' (4-directionally). Border-connected ''O''s are not captured.','1 ≤ m,n ≤ 200 | grid[i][j] ∈ {''X'',''O''}','[{"input": "board = [[\"X\",\"X\",\"X\"],[\"X\",\"O\",\"X\"],[\"X\",\"X\",\"X\"]]", "output": "[[\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\"]]"}]'::jsonb,'[{"input": "[[\"X\",\"X\",\"X\"],[\"X\",\"O\",\"X\"],[\"X\",\"X\",\"X\"]]", "expected_output": "[[\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\"]]", "is_hidden": false}, {"input": "[[\"X\"]]", "expected_output": "[[\"X\"]]", "is_hidden": true}]'::jsonb,'DFS from all border ''O''s, mark safe. Then flip remaining ''O'' to ''X''. O(m×n).',ARRAY['python','java','javascript','go','cpp'],0.41),
('Stairs to ISRO Launch Pad','climbing-stairs','Easy','DSA',ARRAY['dynamic-programming','fibonacci'],'## Problem

`n` step launch pad. Climb 1 or 2 steps at a time. How many **distinct ways** to reach top?','1 ≤ n ≤ 45','[{"input": "n = 3", "output": "3", "explanation": "1+1+1, 1+2, 2+1"}, {"input": "n = 2", "output": "2"}]'::jsonb,'[{"input": "3", "expected_output": "3", "is_hidden": false}, {"input": "10", "expected_output": "89", "is_hidden": true}]'::jsonb,'dp[i]=dp[i-1]+dp[i-2]. Fibonacci. O(n) O(1).',ARRAY['python','java','javascript','go','cpp'],0.83),
('Thief Looting Delhi Markets','house-robber','Easy','DSA',ARRAY['dynamic-programming'],'## Problem

Rob non-adjacent stalls. Given `money[i]` per stall, return **maximum money** without triggering alarms.','1 ≤ n ≤ 100 | 0 ≤ money[i] ≤ 400','[{"input": "money = [1,2,3,1]", "output": "4"}, {"input": "money = [2,7,9,3,1]", "output": "12"}]'::jsonb,'[{"input": "[1,2,3,1]", "expected_output": "4", "is_hidden": false}, {"input": "[2,7,9,3,1]", "expected_output": "12", "is_hidden": true}]'::jsonb,'dp[i]=max(dp[i-1], dp[i-2]+money[i]). O(n) O(1).',ARRAY['python','java','javascript','go','cpp'],0.76),
('House Robber Circular Market','house-robber-ii','Medium','DSA',ARRAY['dynamic-programming'],'## Problem

Now the stalls form a **circle** (first and last are adjacent). Return max money.','1 ≤ n ≤ 100 | 0 ≤ money[i] ≤ 1000','[{"input": "money = [2,3,2]", "output": "3"}, {"input": "money = [1,2,3,1]", "output": "4"}]'::jsonb,'[{"input": "[2,3,2]", "expected_output": "3", "is_hidden": false}, {"input": "[1,2,3,1]", "expected_output": "4", "is_hidden": true}]'::jsonb,'Run House Robber on [0..n-2] and [1..n-1], take max. O(n).',ARRAY['python','java','javascript','go','cpp'],0.45),
('RBI Coin Change Minimum','coin-change','Medium','DSA',ARRAY['dynamic-programming','greedy'],'## Problem

Given coin `denominations` and `amount`, find **minimum coins** to make amount. Return -1 if impossible.','1 ≤ len(coins) ≤ 12 | 1 ≤ coins[i] ≤ 2^31-1 | 0 ≤ amount ≤ 10^4','[{"input": "coins = [1,5,6,9], amount = 11", "output": "2", "explanation": "5+6=11"}, {"input": "coins = [2], amount = 3", "output": "-1"}]'::jsonb,'[{"input": "[1,5,6,9]\n11", "expected_output": "2", "is_hidden": false}, {"input": "[2]\n3", "expected_output": "-1", "is_hidden": true}]'::jsonb,'dp[i]=min coins for amount i. For each amount try each coin. O(amount×coins).',ARRAY['python','java','javascript','go','cpp'],0.5),
('NSE Stock Longest Increasing Sequence','longest-increasing-subsequence','Medium','DSA',ARRAY['dynamic-programming','binary-search'],'## Problem

Find the length of the **longest strictly increasing subsequence** in `prices` array.','1 ≤ n ≤ 2500 | -10^4 ≤ prices[i] ≤ 10^4','[{"input": "prices = [10,9,2,5,3,7,101,18]", "output": "4", "explanation": "[2,3,7,18]"}]'::jsonb,'[{"input": "[10,9,2,5,3,7,101,18]", "expected_output": "4", "is_hidden": false}, {"input": "[0,1,0,3,2,3]", "expected_output": "4", "is_hidden": true}]'::jsonb,'O(n²) DP or O(n log n) patience sorting with binary search on tails array.',ARRAY['python','java','javascript','go','cpp'],0.53)
ON CONFLICT (slug) DO NOTHING;