-- STEP 5: Problems 61–80 of 201
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate)
VALUES
($q$Flipkart Delivery Unique Grid Paths$q$,$q$unique-paths$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','combinatorics'],$q$## Problem

Robot moves top-left to bottom-right of `m×n` grid, only right or down. Count **unique paths**.$q$,$q$1 ≤ m,n ≤ 100$q$,$q$[{"input": "m=3, n=7", "output": "28"}, {"input": "m=3, n=2", "output": "3"}]$q$::jsonb,$q$[{"input": "3\n7", "expected_output": "28", "is_hidden": false}, {"input": "3\n2", "expected_output": "3", "is_hidden": true}]$q$::jsonb,$q$dp[i][j]=dp[i-1][j]+dp[i][j-1]. Or C(m+n-2,m-1). O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.64),
($q$DRDO Robot Minimum Path Sum$q$,$q$minimum-path-sum$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','matrix'],$q$## Problem

Robot moves top-left to bottom-right of grid (only right/down). Find **minimum total cost** path.$q$,$q$1 ≤ m,n ≤ 200 | 0 ≤ grid[i][j] ≤ 100$q$,$q$[{"input": "grid = [[1,3,1],[1,5,1],[4,2,1]]", "output": "7", "explanation": "1→3→1→1→1"}]$q$::jsonb,$q$[{"input": "[[1,3,1],[1,5,1],[4,2,1]]", "expected_output": "7", "is_hidden": false}, {"input": "[[1,2],[1,1]]", "expected_output": "3", "is_hidden": true}]$q$::jsonb,$q$dp[i][j]=min(dp[i-1][j],dp[i][j-1])+grid[i][j]. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.65),
($q$Tata Motors Partition Equal Subset$q$,$q$partition-equal-subset-sum$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','arrays'],$q$## Problem

Can `weights` array be partitioned into **two subsets with equal sum**?$q$,$q$1 ≤ n ≤ 200 | 1 ≤ weights[i] ≤ 100$q$,$q$[{"input": "weights = [1,5,11,5]", "output": "true"}, {"input": "weights = [1,2,3,5]", "output": "false"}]$q$::jsonb,$q$[{"input": "[1,5,11,5]", "expected_output": "true", "is_hidden": false}, {"input": "[1,2,3,5]", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$0/1 knapsack: dp[j]=can form sum j? Total must be even. O(n×sum/2).$q$,ARRAY['python','java','javascript','go','cpp'],0.48),
($q$Target Sum Assignments$q$,$q$target-sum$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','backtracking'],$q$## Problem

Given `nums` and `target`, assign `+` or `-` to each number. How many ways to make the **sum equal target**?$q$,$q$1 ≤ n ≤ 20 | 0 ≤ nums[i] ≤ 1000 | -1000 ≤ target ≤ 1000$q$,$q$[{"input": "nums = [1,1,1,1,1], target = 3", "output": "5"}]$q$::jsonb,$q$[{"input": "[1,1,1,1,1]\n3", "expected_output": "5", "is_hidden": false}, {"input": "[1]\n1", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$DFS/DP. Reduce to subset sum: find S where sum(P) - sum(N) = target. O(n×sum).$q$,ARRAY['python','java','javascript','go','cpp'],0.57),
($q$Zerodha Trading Min Stack$q$,$q$min-stack$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['stack','design'],$q$## Problem

Design a stack with `push`, `pop`, `top`, and `getMin` — all in **O(1)** time.$q$,$q$-2^31 ≤ val ≤ 2^31-1 | At most 3×10^4 calls$q$,$q$[{"input": "push(-2),push(0),push(-3),getMin()→-3,pop(),top()→0,getMin()→-2", "output": "-3,0,-2"}]$q$::jsonb,$q$[{"input": "push(1),push(2),getMin(),push(0),getMin()", "expected_output": "1,0", "is_hidden": false}, {"input": "push(-2),push(0),push(-3),getMin(),pop(),top(),getMin()", "expected_output": "-3,0,-2", "is_hidden": true}]$q$::jsonb,$q$Auxiliary min stack: push min(val,minStack.top) alongside. O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.71),
($q$Sensex Daily Temperature Wait$q$,$q$daily-temperatures$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['stack','monotonic-stack'],$q$## Problem

For each day, how many days until a **higher closing value**? Return 0 if none.$q$,$q$1 ≤ n ≤ 10^5 | 1 ≤ closings[i] ≤ 10^4$q$,$q$[{"input": "closings = [73,74,75,71,69,72,76,73]", "output": "[1,1,4,2,1,1,0,0]"}]$q$::jsonb,$q$[{"input": "[73,74,75,71,69,72,76,73]", "expected_output": "[1,1,4,2,1,1,0,0]", "is_hidden": false}, {"input": "[30,40,50,60]", "expected_output": "[1,1,1,0]", "is_hidden": true}]$q$::jsonb,$q$Monotonic decreasing stack of indices. Pop when cur > stack top. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.62),
($q$Kolkata Tram Histogram Area$q$,$q$largest-rectangle-histogram$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['stack','monotonic-stack'],$q$## Problem

Given `heights` of histogram bars (width=1), find area of **largest rectangle** fitting within.$q$,$q$1 ≤ n ≤ 10^5 | 0 ≤ heights[i] ≤ 10^4$q$,$q$[{"input": "heights = [2,1,5,6,2,3]", "output": "10", "explanation": "Width 2, height 5 at bars 2,3"}]$q$::jsonb,$q$[{"input": "[2,1,5,6,2,3]", "expected_output": "10", "is_hidden": false}, {"input": "[2,4]", "expected_output": "4", "is_hidden": true}]$q$::jsonb,$q$Monotonic increasing stack. On pop, width=cur-stack.top-1. Area=height×width. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.33),
($q$NPCI Transaction Sliding Max$q$,$q$sliding-window-maximum$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['stack','deque','sliding-window'],$q$## Problem

For each window of `k` consecutive `transactions`, return the **maximum** value. One per window.$q$,$q$1 ≤ k ≤ n ≤ 10^5 | -10^4 ≤ transactions[i] ≤ 10^4$q$,$q$[{"input": "transactions = [1,3,-1,-3,5,3,6,7], k=3", "output": "[3,3,5,5,6,7]"}]$q$::jsonb,$q$[{"input": "[1,3,-1,-3,5,3,6,7]\n3", "expected_output": "[3,3,5,5,6,7]", "is_hidden": false}, {"input": "[1]\n1", "expected_output": "[1]", "is_hidden": true}]$q$::jsonb,$q$Deque of indices in decreasing value order. Pop expired front, smaller back. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.32),
($q$Decode String Expand$q$,$q$decode-string$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['stack','strings'],$q$## Problem

Decode string `s` where `k[encoded]` means `encoded` repeated `k` times. E.g. `3[a2[bc]]` → `abcbcabcbcabcbc`.$q$,$q$1 ≤ len(s) ≤ 30 | k ∈ [1,300] | No extra whitespace | Input is always valid$q$,$q$[{"input": "s = \"3[a]2[bc]\"", "output": "\"aaabcbc\""}, {"input": "s = \"3[a2[c]]\"", "output": "\"accaccacc\""}]$q$::jsonb,$q$[{"input": "\"3[a]2[bc]\"", "expected_output": "\"aaabcbc\"", "is_hidden": false}, {"input": "\"3[a2[c]]\"", "expected_output": "\"accaccacc\"", "is_hidden": true}]$q$::jsonb,$q$Stack: push (count, current_string) on '['. On ']', pop and repeat. O(n × max_k).$q$,ARRAY['python','java','javascript','go','cpp'],0.6),
($q$Air India Fuel Station$q$,$q$gas-station$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['greedy','arrays'],$q$## Problem

Circular route with `gas[i]` fuel and `cost[i]` to next station. Find **starting station** to complete circuit. Return -1 if impossible.$q$,$q$1 ≤ n ≤ 10^5 | 0 ≤ gas[i],cost[i] ≤ 10^4$q$,$q$[{"input": "gas = [1,2,3,4,5], cost = [3,4,5,1,2]", "output": "3"}]$q$::jsonb,$q$[{"input": "[1,2,3,4,5]\n[3,4,5,1,2]", "expected_output": "3", "is_hidden": false}, {"input": "[2,3,4]\n[3,4,3]", "expected_output": "-1", "is_hidden": true}]$q$::jsonb,$q$If total gas < total cost → -1. Greedily reset start when tank negative. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.47),
($q$Swiggy Delivery Task Scheduler$q$,$q$task-scheduler$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['greedy','heap'],$q$## Problem

Given `tasks` array and cooldown `n`, return **minimum intervals** (including idle) to finish all tasks.$q$,$q$1 ≤ tasks.length ≤ 10^4 | 0 ≤ n ≤ 100$q$,$q$[{"input": "tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n=2", "output": "8", "explanation": "A→B→idle→A→B→idle→A→B"}]$q$::jsonb,$q$[{"input": "[\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"]\n2", "expected_output": "8", "is_hidden": false}, {"input": "[\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"]\n0", "expected_output": "6", "is_hidden": true}]$q$::jsonb,$q$(maxFreq-1)×(n+1)+countOfMaxFreq. Answer=max(this, tasks.length). O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.56),
($q$Amazon India Non-Overlapping Intervals$q$,$q$non-overlapping-intervals$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['greedy','intervals','sorting'],$q$## Problem

Remove **minimum intervals** to make remaining non-overlapping.$q$,$q$1 ≤ n ≤ 2×10^4$q$,$q$[{"input": "intervals = [[1,2],[2,3],[3,4],[1,3]]", "output": "1"}, {"input": "intervals = [[1,2],[1,2],[1,2]]", "output": "2"}]$q$::jsonb,$q$[{"input": "[[1,2],[2,3],[3,4],[1,3]]", "expected_output": "1", "is_hidden": false}, {"input": "[[1,2],[1,2],[1,2]]", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$Sort by end time. Greedily keep earliest-end intervals. Removals = n - kept. O(n log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.53),
($q$Partition Labels Delivery Zones$q$,$q$partition-labels$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['greedy','strings'],$q$## Problem

Partition string `s` into as many parts as possible so each **letter appears in at most one part**. Return list of partition sizes.$q$,$q$1 ≤ len(s) ≤ 500 | s consists of lowercase letters$q$,$q$[{"input": "s = \"ababcbacadefegdehijhklij\"", "output": "[9,7,8]"}]$q$::jsonb,$q$[{"input": "\"ababcbacadefegdehijhklij\"", "expected_output": "[9,7,8]", "is_hidden": false}, {"input": "\"eccbbbbdec\"", "expected_output": "[10]", "is_hidden": true}]$q$::jsonb,$q$Record last occurrence of each char. Greedily extend partition to cover all last occurrences. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.59),
($q$ISRO Countdown Fizz Buzz$q$,$q$fizz-buzz$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['math','simulation'],$q$## Problem

For 1 to n: output 'Agni' (div by 3), 'Shakti' (div by 5), 'AgniShakti' (div by 15), else the number.$q$,$q$1 ≤ n ≤ 10^4$q$,$q$[{"input": "n = 5", "output": "[\"1\",\"2\",\"Agni\",\"4\",\"Shakti\"]"}]$q$::jsonb,$q$[{"input": "5", "expected_output": "[\"1\",\"2\",\"Agni\",\"4\",\"Shakti\"]", "is_hidden": false}, {"input": "15", "expected_output": "[\"1\",\"2\",\"Agni\",\"4\",\"Shakti\",\"Agni\",\"7\",\"8\",\"Agni\",\"Shakti\",\"11\",\"Agni\",\"13\",\"14\",\"AgniShakti\"]", "is_hidden": true}]$q$::jsonb,$q$Check div15 first, then 3, then 5, else number. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.85),
($q$RBI Prime Sieve$q$,$q$count-primes$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['math','sieve'],$q$## Problem

Count prime numbers **strictly less than** `n` using Sieve of Eratosthenes.$q$,$q$0 ≤ n ≤ 5×10^6$q$,$q$[{"input": "n = 10", "output": "4", "explanation": "Primes: 2,3,5,7"}]$q$::jsonb,$q$[{"input": "10", "expected_output": "4", "is_hidden": false}, {"input": "100", "expected_output": "25", "is_hidden": true}]$q$::jsonb,$q$Sieve: mark composites. Count True from 2 to n-1. O(n log log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.7),
($q$Reverse Integer Aadhaar$q$,$q$reverse-integer$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['math'],$q$## Problem

Given 32-bit integer `x`, return `x` with its digits **reversed**. If overflow occurs (outside [-2^31, 2^31-1]), return 0.$q$,$q$-2^31 ≤ x ≤ 2^31-1$q$,$q$[{"input": "x = 123", "output": "321"}, {"input": "x = -120", "output": "-21"}, {"input": "x = 120", "output": "21"}]$q$::jsonb,$q$[{"input": "123", "expected_output": "321", "is_hidden": false}, {"input": "-120", "expected_output": "-21", "is_hidden": true}]$q$::jsonb,$q$Pop digits (x%10) and push to result (result*10+digit). Check overflow before each push. O(log x).$q$,ARRAY['python','java','javascript','go','cpp'],0.66),
($q$Aadhaar Single Unique ID$q$,$q$single-number$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['bit-manipulation','arrays'],$q$## Problem

Every ID appears **twice** except one. Find the unique ID using O(1) space. (No hash maps!)$q$,$q$1 ≤ n ≤ 3×10^4 | n is odd$q$,$q$[{"input": "nums = [4,1,2,1,2]", "output": "4"}]$q$::jsonb,$q$[{"input": "[4,1,2,1,2]", "expected_output": "4", "is_hidden": false}, {"input": "[2,2,1]", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$XOR all elements. Pairs cancel. Result = unique. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.79),
($q$BSNL Missing Subscriber ID$q$,$q$missing-number$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['bit-manipulation','math'],$q$## Problem

Array contains n distinct numbers in [0,n]. Find the **missing number**.$q$,$q$1 ≤ n ≤ 10^4 | 0 ≤ ids[i] ≤ n$q$,$q$[{"input": "ids = [3,0,1]", "output": "2"}, {"input": "ids = [9,6,4,2,3,5,7,0,1]", "output": "8"}]$q$::jsonb,$q$[{"input": "[3,0,1]", "expected_output": "2", "is_hidden": false}, {"input": "[0,1]", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$Expected sum=n(n+1)/2. Missing=expected-actual. Or XOR. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.74),
($q$Number of 1 Bits Hamming$q$,$q$number-of-1-bits$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['bit-manipulation'],$q$## Problem

Return the number of **set bits (1s)** in the binary representation of unsigned integer `n`.$q$,$q$0 ≤ n ≤ 2^32-1$q$,$q$[{"input": "n = 11 (binary: 1011)", "output": "3"}, {"input": "n = 128 (binary: 10000000)", "output": "1"}]$q$::jsonb,$q$[{"input": "11", "expected_output": "3", "is_hidden": false}, {"input": "128", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$n & (n-1) clears lowest set bit. Count until n=0. O(number of set bits).$q$,ARRAY['python','java','javascript','go','cpp'],0.75),
($q$Durga Puja Guest Subsets$q$,$q$subsets$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['backtracking','arrays'],$q$## Problem

Return all possible **subsets** (power set) of unique `guests` array. No duplicates.$q$,$q$1 ≤ n ≤ 10 | -10 ≤ guests[i] ≤ 10 | All unique$q$,$q$[{"input": "guests = [1,2,3]", "output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"}]$q$::jsonb,$q$[{"input": "[1,2,3]", "expected_output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]", "is_hidden": false}, {"input": "[0]", "expected_output": "[[],[0]]", "is_hidden": true}]$q$::jsonb,$q$Backtracking or bitmask 0..2^n-1. O(n×2^n).$q$,ARRAY['python','java','javascript','go','cpp'],0.74)
ON CONFLICT (slug) DO NOTHING;