-- STEP 5: Insert problems 61–80
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate) VALUES
('Flipkart Delivery Unique Grid Paths','unique-paths','Medium','DSA',ARRAY['dynamic-programming','combinatorics'],'## Problem

Robot moves top-left to bottom-right of `m×n` grid, only right or down. Count **unique paths**.','1 ≤ m,n ≤ 100','[{"input": "m=3, n=7", "output": "28"}, {"input": "m=3, n=2", "output": "3"}]'::jsonb,'[{"input": "3\n7", "expected_output": "28", "is_hidden": false}, {"input": "3\n2", "expected_output": "3", "is_hidden": true}]'::jsonb,'dp[i][j]=dp[i-1][j]+dp[i][j-1]. Or C(m+n-2,m-1). O(m×n).',ARRAY['python','java','javascript','go','cpp'],0.64),
('DRDO Robot Minimum Path Sum','minimum-path-sum','Medium','DSA',ARRAY['dynamic-programming','matrix'],'## Problem

Robot moves top-left to bottom-right of grid (only right/down). Find **minimum total cost** path.','1 ≤ m,n ≤ 200 | 0 ≤ grid[i][j] ≤ 100','[{"input": "grid = [[1,3,1],[1,5,1],[4,2,1]]", "output": "7", "explanation": "1→3→1→1→1"}]'::jsonb,'[{"input": "[[1,3,1],[1,5,1],[4,2,1]]", "expected_output": "7", "is_hidden": false}, {"input": "[[1,2],[1,1]]", "expected_output": "3", "is_hidden": true}]'::jsonb,'dp[i][j]=min(dp[i-1][j],dp[i][j-1])+grid[i][j]. O(m×n).',ARRAY['python','java','javascript','go','cpp'],0.65),
('Tata Motors Partition Equal Subset','partition-equal-subset-sum','Medium','DSA',ARRAY['dynamic-programming','arrays'],'## Problem

Can `weights` array be partitioned into **two subsets with equal sum**?','1 ≤ n ≤ 200 | 1 ≤ weights[i] ≤ 100','[{"input": "weights = [1,5,11,5]", "output": "true"}, {"input": "weights = [1,2,3,5]", "output": "false"}]'::jsonb,'[{"input": "[1,5,11,5]", "expected_output": "true", "is_hidden": false}, {"input": "[1,2,3,5]", "expected_output": "false", "is_hidden": true}]'::jsonb,'0/1 knapsack: dp[j]=can form sum j? Total must be even. O(n×sum/2).',ARRAY['python','java','javascript','go','cpp'],0.48),
('Target Sum Assignments','target-sum','Medium','DSA',ARRAY['dynamic-programming','backtracking'],'## Problem

Given `nums` and `target`, assign `+` or `-` to each number. How many ways to make the **sum equal target**?','1 ≤ n ≤ 20 | 0 ≤ nums[i] ≤ 1000 | -1000 ≤ target ≤ 1000','[{"input": "nums = [1,1,1,1,1], target = 3", "output": "5"}]'::jsonb,'[{"input": "[1,1,1,1,1]\n3", "expected_output": "5", "is_hidden": false}, {"input": "[1]\n1", "expected_output": "1", "is_hidden": true}]'::jsonb,'DFS/DP. Reduce to subset sum: find S where sum(P) - sum(N) = target. O(n×sum).',ARRAY['python','java','javascript','go','cpp'],0.57),
('Zerodha Trading Min Stack','min-stack','Easy','DSA',ARRAY['stack','design'],'## Problem

Design a stack with `push`, `pop`, `top`, and `getMin` — all in **O(1)** time.','-2^31 ≤ val ≤ 2^31-1 | At most 3×10^4 calls','[{"input": "push(-2),push(0),push(-3),getMin()→-3,pop(),top()→0,getMin()→-2", "output": "-3,0,-2"}]'::jsonb,'[{"input": "push(1),push(2),getMin(),push(0),getMin()", "expected_output": "1,0", "is_hidden": false}, {"input": "push(-2),push(0),push(-3),getMin(),pop(),top(),getMin()", "expected_output": "-3,0,-2", "is_hidden": true}]'::jsonb,'Auxiliary min stack: push min(val,minStack.top) alongside. O(1).',ARRAY['python','java','javascript','go','cpp'],0.71),
('Sensex Daily Temperature Wait','daily-temperatures','Medium','DSA',ARRAY['stack','monotonic-stack'],'## Problem

For each day, how many days until a **higher closing value**? Return 0 if none.','1 ≤ n ≤ 10^5 | 1 ≤ closings[i] ≤ 10^4','[{"input": "closings = [73,74,75,71,69,72,76,73]", "output": "[1,1,4,2,1,1,0,0]"}]'::jsonb,'[{"input": "[73,74,75,71,69,72,76,73]", "expected_output": "[1,1,4,2,1,1,0,0]", "is_hidden": false}, {"input": "[30,40,50,60]", "expected_output": "[1,1,1,0]", "is_hidden": true}]'::jsonb,'Monotonic decreasing stack of indices. Pop when cur > stack top. O(n).',ARRAY['python','java','javascript','go','cpp'],0.62),
('Kolkata Tram Histogram Area','largest-rectangle-histogram','Hard','DSA',ARRAY['stack','monotonic-stack'],'## Problem

Given `heights` of histogram bars (width=1), find area of **largest rectangle** fitting within.','1 ≤ n ≤ 10^5 | 0 ≤ heights[i] ≤ 10^4','[{"input": "heights = [2,1,5,6,2,3]", "output": "10", "explanation": "Width 2, height 5 at bars 2,3"}]'::jsonb,'[{"input": "[2,1,5,6,2,3]", "expected_output": "10", "is_hidden": false}, {"input": "[2,4]", "expected_output": "4", "is_hidden": true}]'::jsonb,'Monotonic increasing stack. On pop, width=cur-stack.top-1. Area=height×width. O(n).',ARRAY['python','java','javascript','go','cpp'],0.33),
('NPCI Transaction Sliding Max','sliding-window-maximum','Hard','DSA',ARRAY['stack','deque','sliding-window'],'## Problem

For each window of `k` consecutive `transactions`, return the **maximum** value. One per window.','1 ≤ k ≤ n ≤ 10^5 | -10^4 ≤ transactions[i] ≤ 10^4','[{"input": "transactions = [1,3,-1,-3,5,3,6,7], k=3", "output": "[3,3,5,5,6,7]"}]'::jsonb,'[{"input": "[1,3,-1,-3,5,3,6,7]\n3", "expected_output": "[3,3,5,5,6,7]", "is_hidden": false}, {"input": "[1]\n1", "expected_output": "[1]", "is_hidden": true}]'::jsonb,'Deque of indices in decreasing value order. Pop expired front, smaller back. O(n).',ARRAY['python','java','javascript','go','cpp'],0.32),
('Decode String Expand','decode-string','Medium','DSA',ARRAY['stack','strings'],'## Problem

Decode string `s` where `k[encoded]` means `encoded` repeated `k` times. E.g. `3[a2[bc]]` → `abcbcabcbcabcbc`.','1 ≤ len(s) ≤ 30 | k ∈ [1,300] | No extra whitespace | Input is always valid','[{"input": "s = \"3[a]2[bc]\"", "output": "\"aaabcbc\""}, {"input": "s = \"3[a2[c]]\"", "output": "\"accaccacc\""}]'::jsonb,'[{"input": "\"3[a]2[bc]\"", "expected_output": "\"aaabcbc\"", "is_hidden": false}, {"input": "\"3[a2[c]]\"", "expected_output": "\"accaccacc\"", "is_hidden": true}]'::jsonb,'Stack: push (count, current_string) on ''[''. On '']'', pop and repeat. O(n × max_k).',ARRAY['python','java','javascript','go','cpp'],0.6),
('Air India Fuel Station','gas-station','Medium','DSA',ARRAY['greedy','arrays'],'## Problem

Circular route with `gas[i]` fuel and `cost[i]` to next station. Find **starting station** to complete circuit. Return -1 if impossible.','1 ≤ n ≤ 10^5 | 0 ≤ gas[i],cost[i] ≤ 10^4','[{"input": "gas = [1,2,3,4,5], cost = [3,4,5,1,2]", "output": "3"}]'::jsonb,'[{"input": "[1,2,3,4,5]\n[3,4,5,1,2]", "expected_output": "3", "is_hidden": false}, {"input": "[2,3,4]\n[3,4,3]", "expected_output": "-1", "is_hidden": true}]'::jsonb,'If total gas < total cost → -1. Greedily reset start when tank negative. O(n).',ARRAY['python','java','javascript','go','cpp'],0.47),
('Swiggy Delivery Task Scheduler','task-scheduler','Medium','DSA',ARRAY['greedy','heap'],'## Problem

Given `tasks` array and cooldown `n`, return **minimum intervals** (including idle) to finish all tasks.','1 ≤ tasks.length ≤ 10^4 | 0 ≤ n ≤ 100','[{"input": "tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n=2", "output": "8", "explanation": "A→B→idle→A→B→idle→A→B"}]'::jsonb,'[{"input": "[\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"]\n2", "expected_output": "8", "is_hidden": false}, {"input": "[\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"]\n0", "expected_output": "6", "is_hidden": true}]'::jsonb,'(maxFreq-1)×(n+1)+countOfMaxFreq. Answer=max(this, tasks.length). O(n).',ARRAY['python','java','javascript','go','cpp'],0.56),
('Amazon India Non-Overlapping Intervals','non-overlapping-intervals','Medium','DSA',ARRAY['greedy','intervals','sorting'],'## Problem

Remove **minimum intervals** to make remaining non-overlapping.','1 ≤ n ≤ 2×10^4','[{"input": "intervals = [[1,2],[2,3],[3,4],[1,3]]", "output": "1"}, {"input": "intervals = [[1,2],[1,2],[1,2]]", "output": "2"}]'::jsonb,'[{"input": "[[1,2],[2,3],[3,4],[1,3]]", "expected_output": "1", "is_hidden": false}, {"input": "[[1,2],[1,2],[1,2]]", "expected_output": "2", "is_hidden": true}]'::jsonb,'Sort by end time. Greedily keep earliest-end intervals. Removals = n - kept. O(n log n).',ARRAY['python','java','javascript','go','cpp'],0.53),
('Partition Labels Delivery Zones','partition-labels','Medium','DSA',ARRAY['greedy','strings'],'## Problem

Partition string `s` into as many parts as possible so each **letter appears in at most one part**. Return list of partition sizes.','1 ≤ len(s) ≤ 500 | s consists of lowercase letters','[{"input": "s = \"ababcbacadefegdehijhklij\"", "output": "[9,7,8]"}]'::jsonb,'[{"input": "\"ababcbacadefegdehijhklij\"", "expected_output": "[9,7,8]", "is_hidden": false}, {"input": "\"eccbbbbdec\"", "expected_output": "[10]", "is_hidden": true}]'::jsonb,'Record last occurrence of each char. Greedily extend partition to cover all last occurrences. O(n).',ARRAY['python','java','javascript','go','cpp'],0.59),
('ISRO Countdown Fizz Buzz','fizz-buzz','Easy','DSA',ARRAY['math','simulation'],'## Problem

For 1 to n: output ''Agni'' (div by 3), ''Shakti'' (div by 5), ''AgniShakti'' (div by 15), else the number.','1 ≤ n ≤ 10^4','[{"input": "n = 5", "output": "[\"1\",\"2\",\"Agni\",\"4\",\"Shakti\"]"}]'::jsonb,'[{"input": "5", "expected_output": "[\"1\",\"2\",\"Agni\",\"4\",\"Shakti\"]", "is_hidden": false}, {"input": "15", "expected_output": "[\"1\",\"2\",\"Agni\",\"4\",\"Shakti\",\"Agni\",\"7\",\"8\",\"Agni\",\"Shakti\",\"11\",\"Agni\",\"13\",\"14\",\"AgniShakti\"]", "is_hidden": true}]'::jsonb,'Check div15 first, then 3, then 5, else number. O(n).',ARRAY['python','java','javascript','go','cpp'],0.85),
('RBI Prime Sieve','count-primes','Easy','DSA',ARRAY['math','sieve'],'## Problem

Count prime numbers **strictly less than** `n` using Sieve of Eratosthenes.','0 ≤ n ≤ 5×10^6','[{"input": "n = 10", "output": "4", "explanation": "Primes: 2,3,5,7"}]'::jsonb,'[{"input": "10", "expected_output": "4", "is_hidden": false}, {"input": "100", "expected_output": "25", "is_hidden": true}]'::jsonb,'Sieve: mark composites. Count True from 2 to n-1. O(n log log n).',ARRAY['python','java','javascript','go','cpp'],0.7),
('Reverse Integer Aadhaar','reverse-integer','Easy','DSA',ARRAY['math'],'## Problem

Given 32-bit integer `x`, return `x` with its digits **reversed**. If overflow occurs (outside [-2^31, 2^31-1]), return 0.','-2^31 ≤ x ≤ 2^31-1','[{"input": "x = 123", "output": "321"}, {"input": "x = -120", "output": "-21"}, {"input": "x = 120", "output": "21"}]'::jsonb,'[{"input": "123", "expected_output": "321", "is_hidden": false}, {"input": "-120", "expected_output": "-21", "is_hidden": true}]'::jsonb,'Pop digits (x%10) and push to result (result*10+digit). Check overflow before each push. O(log x).',ARRAY['python','java','javascript','go','cpp'],0.66),
('Aadhaar Single Unique ID','single-number','Easy','DSA',ARRAY['bit-manipulation','arrays'],'## Problem

Every ID appears **twice** except one. Find the unique ID using O(1) space. (No hash maps!)','1 ≤ n ≤ 3×10^4 | n is odd','[{"input": "nums = [4,1,2,1,2]", "output": "4"}]'::jsonb,'[{"input": "[4,1,2,1,2]", "expected_output": "4", "is_hidden": false}, {"input": "[2,2,1]", "expected_output": "1", "is_hidden": true}]'::jsonb,'XOR all elements. Pairs cancel. Result = unique. O(n) O(1).',ARRAY['python','java','javascript','go','cpp'],0.79),
('BSNL Missing Subscriber ID','missing-number','Easy','DSA',ARRAY['bit-manipulation','math'],'## Problem

Array contains n distinct numbers in [0,n]. Find the **missing number**.','1 ≤ n ≤ 10^4 | 0 ≤ ids[i] ≤ n','[{"input": "ids = [3,0,1]", "output": "2"}, {"input": "ids = [9,6,4,2,3,5,7,0,1]", "output": "8"}]'::jsonb,'[{"input": "[3,0,1]", "expected_output": "2", "is_hidden": false}, {"input": "[0,1]", "expected_output": "2", "is_hidden": true}]'::jsonb,'Expected sum=n(n+1)/2. Missing=expected-actual. Or XOR. O(n).',ARRAY['python','java','javascript','go','cpp'],0.74),
('Number of 1 Bits Hamming','number-of-1-bits','Easy','DSA',ARRAY['bit-manipulation'],'## Problem

Return the number of **set bits (1s)** in the binary representation of unsigned integer `n`.','0 ≤ n ≤ 2^32-1','[{"input": "n = 11 (binary: 1011)", "output": "3"}, {"input": "n = 128 (binary: 10000000)", "output": "1"}]'::jsonb,'[{"input": "11", "expected_output": "3", "is_hidden": false}, {"input": "128", "expected_output": "1", "is_hidden": true}]'::jsonb,'n & (n-1) clears lowest set bit. Count until n=0. O(number of set bits).',ARRAY['python','java','javascript','go','cpp'],0.75),
('Durga Puja Guest Subsets','subsets','Medium','DSA',ARRAY['backtracking','arrays'],'## Problem

Return all possible **subsets** (power set) of unique `guests` array. No duplicates.','1 ≤ n ≤ 10 | -10 ≤ guests[i] ≤ 10 | All unique','[{"input": "guests = [1,2,3]", "output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"}]'::jsonb,'[{"input": "[1,2,3]", "expected_output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]", "is_hidden": false}, {"input": "[0]", "expected_output": "[[],[0]]", "is_hidden": true}]'::jsonb,'Backtracking or bitmask 0..2^n-1. O(n×2^n).',ARRAY['python','java','javascript','go','cpp'],0.74)
ON CONFLICT (slug) DO NOTHING;