-- STEP 6: Insert problems 81–100
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate) VALUES
('IIT JEE Combination Sum','combination-sum','Medium','DSA',ARRAY['backtracking','arrays'],'## Problem

Find all unique combinations from `marks` that sum to `target`. Numbers can be reused.','1 ≤ marks.length ≤ 30 | 2 ≤ marks[i] ≤ 40 | 1 ≤ target ≤ 40','[{"input": "marks = [2,3,6,7], target = 7", "output": "[[2,2,3],[7]]"}]'::jsonb,'[{"input": "[2,3,6,7]\n7", "expected_output": "[[2,2,3],[7]]", "is_hidden": false}, {"input": "[2,3,5]\n8", "expected_output": "[[2,2,2,2],[2,3,3],[3,5]]", "is_hidden": true}]'::jsonb,'Backtrack allowing reuse. Prune when remaining<0. O(n^(T/m)).',ARRAY['python','java','javascript','go','cpp'],0.67),
('Phone Keypad Letter Combinations','letter-combinations-phone-number','Medium','DSA',ARRAY['backtracking','strings'],'## Problem

Given a digit string `digits` (2-9), return all possible **letter combinations** it could represent on a phone keypad.','0 ≤ len(digits) ≤ 4 | digits[i] ∈ {''2'',...,''9''}','[{"input": "digits = \"23\"", "output": "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]"}]'::jsonb,'[{"input": "\"23\"", "expected_output": "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]", "is_hidden": false}, {"input": "\"\"", "expected_output": "[]", "is_hidden": true}]'::jsonb,'Backtracking: for each digit map letters, recurse. O(4^n × n) where n=len(digits).',ARRAY['python','java','javascript','go','cpp'],0.65),
('Chess Tournament N-Queens','n-queens','Hard','DSA',ARRAY['backtracking'],'## Problem

Place `n` queens on `n×n` board so none attack each other. Return all distinct solutions.','1 ≤ n ≤ 9','[{"input": "n = 4", "output": "[[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]"}]'::jsonb,'[{"input": "4", "expected_output": "[[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]", "is_hidden": false}, {"input": "1", "expected_output": "[[\"Q\"]]", "is_hidden": true}]'::jsonb,'Place queens row by row. Track col/diagonal/anti-diagonal sets. O(n!).',ARRAY['python','java','javascript','go','cpp'],0.27),
('Zerodha Top K Frequent Stocks','top-k-frequent-elements','Medium','DSA',ARRAY['heap','hash-map','bucket-sort'],'## Problem

Return the `k` **most frequently** occurring elements. Better than O(n log n).','1 ≤ n ≤ 10^5 | 1 ≤ k ≤ distinct elements','[{"input": "nums = [1,1,1,2,2,3], k=2", "output": "[1,2]"}]'::jsonb,'[{"input": "[1,1,1,2,2,3]\n2", "expected_output": "[1,2]", "is_hidden": false}, {"input": "[1]\n1", "expected_output": "[1]", "is_hidden": true}]'::jsonb,'Count freqs. Min-heap of size k or bucket sort. O(n log k).',ARRAY['python','java','javascript','go','cpp'],0.66),
('Stock Market Median Stream','find-median-from-data-stream','Hard','DSA',ARRAY['heap','design'],'## Problem

Design a data structure for `addNum(num)` and `findMedian()` on a running stream.','-10^5 ≤ num ≤ 10^5 | At most 5×10^4 calls','[{"input": "addNum(1),addNum(2),findMedian()→1.5,addNum(3),findMedian()→2.0", "output": "1.5,2.0"}]'::jsonb,'[{"input": "addNum(1),addNum(2),findMedian()", "expected_output": "1.5", "is_hidden": false}, {"input": "addNum(1),addNum(2),addNum(3),findMedian()", "expected_output": "2.0", "is_hidden": true}]'::jsonb,'Max-heap for lower half, min-heap for upper half. Balance after insert. O(log n) add, O(1) median.',ARRAY['python','java','javascript','go','cpp'],0.29),
('Flipkart Warehouse K Closest Items','k-closest-points-to-origin','Medium','DSA',ARRAY['heap','arrays'],'## Problem

Return the `k` closest `points` to origin (0,0). Distance = Euclidean (no sqrt needed for comparison).','1 ≤ k ≤ points.length ≤ 10^4 | -10^4 ≤ xi,yi ≤ 10^4','[{"input": "points = [[1,3],[-2,2]], k=1", "output": "[[-2,2]]"}]'::jsonb,'[{"input": "[[1,3],[-2,2]]\n1", "expected_output": "[[-2,2]]", "is_hidden": false}, {"input": "[[3,3],[5,-1],[-2,4]]\n2", "expected_output": "[[3,3],[-2,4]]", "is_hidden": true}]'::jsonb,'Max-heap of size k on x²+y². O(n log k). Or Quickselect O(n).',ARRAY['python','java','javascript','go','cpp'],0.67),
('Merge K Sorted Lists','merge-k-sorted-lists','Hard','DSA',ARRAY['heap','linked-list','divide-conquer'],'## Problem

Merge `k` sorted linked lists into one sorted linked list.','0 ≤ k ≤ 10^4 | 0 ≤ n ≤ 500 | -10^4 ≤ val ≤ 10^4 | Total nodes ≤ 10^4','[{"input": "lists = [[1,4,5],[1,3,4],[2,6]]", "output": "[1,1,2,3,4,4,5,6]"}]'::jsonb,'[{"input": "[[1,4,5],[1,3,4],[2,6]]", "expected_output": "[1,1,2,3,4,4,5,6]", "is_hidden": false}, {"input": "[[]]", "expected_output": "[]", "is_hidden": true}]'::jsonb,'Min-heap of (val, list_idx, node). Pop min, push next node from same list. O(N log k).',ARRAY['python','java','javascript','go','cpp'],0.4),
('Google India Search Trie','implement-trie','Medium','DSA',ARRAY['trie','design','strings'],'## Problem

Build a **Trie** with `insert(word)`, `search(word)`, and `startsWith(prefix)`.','1 ≤ len(word) ≤ 2000 | lowercase letters | At most 3×10^4 operations','[{"input": "insert(\"apple\"),search(\"apple\")→true,search(\"app\")→false,startsWith(\"app\")→true", "output": "true,false,true"}]'::jsonb,'[{"input": "insert(\"apple\"),search(\"apple\"),search(\"app\"),startsWith(\"app\")", "expected_output": "true,false,true", "is_hidden": false}, {"input": "insert(\"app\"),search(\"app\"),startsWith(\"ap\")", "expected_output": "true,true", "is_hidden": true}]'::jsonb,'TrieNode with children[26] and isEnd flag. O(m) per op where m=word length.',ARRAY['python','java','javascript','go','cpp'],0.58),
('Nykaa Product Replace Words','replace-words','Medium','DSA',ARRAY['trie','strings'],'## Problem

Replace every word in `sentence` with its shortest matching `root` from the dictionary. If no match, keep original.','1 ≤ roots.length ≤ 1000 | 1 ≤ len(root) ≤ 100','[{"input": "roots=[\"cat\",\"bat\",\"rat\"], sentence=\"the cattle was rattled by the battery\"", "output": "\"the cat was rat by the bat\""}]'::jsonb,'[{"input": "[\"cat\",\"bat\",\"rat\"]\n\"the cattle was rattled by the battery\"", "expected_output": "\"the cat was rat by the bat\"", "is_hidden": false}, {"input": "[\"a\",\"b\",\"c\"]\n\"aadsfasf absbs bbab cadsfafs\"", "expected_output": "\"a a b c\"", "is_hidden": true}]'::jsonb,'Build trie from roots. For each word traverse trie; replace on root end. O(total chars).',ARRAY['python','java','javascript','go','cpp'],0.64),
('Jump Game II Minimum Jumps','jump-game-ii','Medium','DSA',ARRAY['greedy','dynamic-programming','arrays'],'## Problem

Given `jumps[i]` = max steps from position `i`, return the **minimum number of jumps** to reach the last index. Always reachable.','1 ≤ n ≤ 10^4 | 0 ≤ jumps[i] ≤ 1000','[{"input": "jumps = [2,3,1,1,4]", "output": "2", "explanation": "Jump 1→3 (2 steps), then 3→last (1 step)"}]'::jsonb,'[{"input": "[2,3,1,1,4]", "expected_output": "2", "is_hidden": false}, {"input": "[2,3,0,1,4]", "expected_output": "2", "is_hidden": true}]'::jsonb,'Greedy BFS: track current range, next max reach. Increment jumps at range end. O(n).',ARRAY['python','java','javascript','go','cpp'],0.47),
('Binary Search IRCTC Ticket','binary-search','Easy','DSA',ARRAY['binary-search','arrays'],'## Problem

Given sorted `prices` array and `target` price, return the **index** if found, else return -1. Must be O(log n).','1 ≤ n ≤ 10^4 | -10^4 ≤ prices[i] ≤ 10^4 | Sorted ascending | All distinct','[{"input": "prices = [-1,0,3,5,9,12], target = 9", "output": "4"}, {"input": "prices = [-1,0,3,5,9,12], target = 2", "output": "-1"}]'::jsonb,'[{"input": "[-1,0,3,5,9,12]\n9", "expected_output": "4", "is_hidden": false}, {"input": "[-1,0,3,5,9,12]\n2", "expected_output": "-1", "is_hidden": true}]'::jsonb,'Standard binary search. lo=0, hi=n-1, mid=(lo+hi)//2. O(log n).',ARRAY['python','java','javascript','go','cpp'],0.8),
('Search Rotated Sorted Array','search-in-rotated-sorted-array','Medium','DSA',ARRAY['binary-search','arrays'],'## Problem

A sorted array was rotated at some pivot. Given `nums` and `target`, return index or -1 in O(log n).','1 ≤ n ≤ 5000 | -10^4 ≤ nums[i] ≤ 10^4 | All distinct','[{"input": "nums = [4,5,6,7,0,1,2], target = 0", "output": "4"}, {"input": "nums = [4,5,6,7,0,1,2], target = 3", "output": "-1"}]'::jsonb,'[{"input": "[4,5,6,7,0,1,2]\n0", "expected_output": "4", "is_hidden": false}, {"input": "[4,5,6,7,0,1,2]\n3", "expected_output": "-1", "is_hidden": true}]'::jsonb,'Binary search: determine which half is sorted, check if target falls in it. O(log n).',ARRAY['python','java','javascript','go','cpp'],0.48),
('Find Peak Element Terrain','find-peak-element','Medium','DSA',ARRAY['binary-search','arrays'],'## Problem

A peak element is strictly greater than its neighbors. Given `nums`, return the index of **any peak** in O(log n). Assume nums[-1] = nums[n] = -∞.','1 ≤ n ≤ 1000 | -2^31 ≤ nums[i] ≤ 2^31-1 | nums[i] ≠ nums[i+1]','[{"input": "nums = [1,2,3,1]", "output": "2"}, {"input": "nums = [1,2,1,3,5,6,4]", "output": "5"}]'::jsonb,'[{"input": "[1,2,3,1]", "expected_output": "2", "is_hidden": false}, {"input": "[1,2,1,3,5,6,4]", "expected_output": "5", "is_hidden": true}]'::jsonb,'Binary search: if nums[mid] < nums[mid+1], peak is on right. Else on left or at mid. O(log n).',ARRAY['python','java','javascript','go','cpp'],0.53),
('Median of Two Sorted Arrays','median-two-sorted-arrays','Hard','DSA',ARRAY['binary-search','arrays','divide-conquer'],'## Problem

Given two sorted arrays `nums1` and `nums2`, find the **median** of the combined sorted array. O(log(m+n)) required.','0 ≤ m,n ≤ 1000 | -10^6 ≤ nums[i] ≤ 10^6 | m+n ≥ 1','[{"input": "nums1 = [1,3], nums2 = [2]", "output": "2.0"}, {"input": "nums1 = [1,2], nums2 = [3,4]", "output": "2.5"}]'::jsonb,'[{"input": "[1,3]\n[2]", "expected_output": "2.0", "is_hidden": false}, {"input": "[1,2]\n[3,4]", "expected_output": "2.5", "is_hidden": true}]'::jsonb,'Binary search on smaller array to find correct partition. O(log(min(m,n))).',ARRAY['python','java','javascript','go','cpp'],0.25),
('Search 2D Matrix Flipkart','search-a-2d-matrix','Medium','DSA',ARRAY['binary-search','matrix'],'## Problem

Given an `m×n` matrix where each row is sorted and first element of each row > last element of previous row, determine if `target` exists. O(log(m×n)).','1 ≤ m,n ≤ 100 | -10^4 ≤ matrix[i][j],target ≤ 10^4','[{"input": "matrix=[[1,3,5,7],[10,11,16,20],[23,30,34,60]], target=3", "output": "true"}]'::jsonb,'[{"input": "[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\n3", "expected_output": "true", "is_hidden": false}, {"input": "[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\n13", "expected_output": "false", "is_hidden": true}]'::jsonb,'Treat matrix as flat sorted array. Binary search with (mid//n, mid%n). O(log(m×n)).',ARRAY['python','java','javascript','go','cpp'],0.55),
('Stock Buy Sell Multiple Times','best-time-buy-sell-stock-ii','Easy','DSA',ARRAY['greedy','arrays'],'## Problem

BSE stock: `prices[i]` = price on day `i`. You can buy/sell **multiple times** (hold at most one share at a time). Maximize total profit.','1 ≤ n ≤ 3×10^4 | 0 ≤ prices[i] ≤ 10^4','[{"input": "prices = [7,1,5,3,6,4]", "output": "7", "explanation": "Buy 1 sell 5 (+4), buy 3 sell 6 (+3)"}]'::jsonb,'[{"input": "[7,1,5,3,6,4]", "expected_output": "7", "is_hidden": false}, {"input": "[1,2,3,4,5]", "expected_output": "4", "is_hidden": true}]'::jsonb,'Sum all positive differences (prices[i]-prices[i-1] if positive). Greedy. O(n).',ARRAY['python','java','javascript','go','cpp'],0.7),
('Stock with Cooldown NSE','best-time-buy-sell-stock-cooldown','Medium','DSA',ARRAY['dynamic-programming','arrays'],'## Problem

Buy/sell multiple times but after selling you must wait 1 day (cooldown). Maximize profit.','1 ≤ n ≤ 5000 | 0 ≤ prices[i] ≤ 1000','[{"input": "prices = [1,2,3,0,2]", "output": "3", "explanation": "Buy 1 sell 3 (profit 2), cooldown, buy 0 sell 2 (profit 2) = wait actually optimal is 3"}]'::jsonb,'[{"input": "[1,2,3,0,2]", "expected_output": "3", "is_hidden": false}, {"input": "[1]", "expected_output": "0", "is_hidden": true}]'::jsonb,'States: held, sold, rest. held[i]=max(held[i-1],rest[i-1]-price); sold[i]=held[i-1]+price; rest[i]=max(rest[i-1],sold[i-1]). O(n).',ARRAY['python','java','javascript','go','cpp'],0.49),
('Word Search Grid Puzzle','word-search','Medium','DSA',ARRAY['backtracking','matrix','dfs'],'## Problem

Given `m×n` character grid `board` and string `word`, return `true` if the word can be constructed from **sequentially adjacent cells** (no reuse).','1 ≤ m,n ≤ 6 | 1 ≤ len(word) ≤ 15 | board and word consist of uppercase English letters','[{"input": "board=[[\"A\",\"B\",\"C\"],[\"S\",\"F\",\"C\"],[\"A\",\"D\",\"E\"]], word=\"ABCCED\"", "output": "true"}]'::jsonb,'[{"input": "[[\"A\",\"B\",\"C\"],[\"S\",\"F\",\"C\"],[\"A\",\"D\",\"E\"]]\n\"ABCCED\"", "expected_output": "true", "is_hidden": false}, {"input": "[[\"A\",\"B\",\"C\"],[\"S\",\"F\",\"C\"],[\"A\",\"D\",\"E\"]]\n\"ABCB\"", "expected_output": "false", "is_hidden": true}]'::jsonb,'DFS/backtracking from each cell. Mark visited, unmark on backtrack. O(m×n×4^len(word)).',ARRAY['python','java','javascript','go','cpp'],0.5),
('Permutations All Arrangements','permutations','Medium','DSA',ARRAY['backtracking','arrays'],'## Problem

Given array of **distinct** integers `nums`, return all possible permutations.','1 ≤ n ≤ 6 | -10 ≤ nums[i] ≤ 10 | All distinct','[{"input": "nums = [1,2,3]", "output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"}]'::jsonb,'[{"input": "[1,2,3]", "expected_output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]", "is_hidden": false}, {"input": "[0,1]", "expected_output": "[[0,1],[1,0]]", "is_hidden": true}]'::jsonb,'Backtrack: swap elements at current position with each subsequent. O(n×n!).',ARRAY['python','java','javascript','go','cpp'],0.73),
('Generate All Valid Parentheses','generate-parentheses','Medium','DSA',ARRAY['backtracking','strings'],'## Problem

Generate all combinations of **n pairs of well-formed parentheses**.','1 ≤ n ≤ 8','[{"input": "n = 3", "output": "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]"}]'::jsonb,'[{"input": "3", "expected_output": "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]", "is_hidden": false}, {"input": "1", "expected_output": "[\"()\"]", "is_hidden": true}]'::jsonb,'Backtrack: add ''('' if open<n, add '')'' if close<open. O(4^n/sqrt(n)).',ARRAY['python','java','javascript','go','cpp'],0.69)
ON CONFLICT (slug) DO NOTHING;