-- STEP 6: Problems 81–100 of 201
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate)
VALUES
($q$IIT JEE Combination Sum$q$,$q$combination-sum$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['backtracking','arrays'],$q$## Problem

Find all unique combinations from `marks` that sum to `target`. Numbers can be reused.$q$,$q$1 ≤ marks.length ≤ 30 | 2 ≤ marks[i] ≤ 40 | 1 ≤ target ≤ 40$q$,$q$[{"input": "marks = [2,3,6,7], target = 7", "output": "[[2,2,3],[7]]"}]$q$::jsonb,$q$[{"input": "[2,3,6,7]\n7", "expected_output": "[[2,2,3],[7]]", "is_hidden": false}, {"input": "[2,3,5]\n8", "expected_output": "[[2,2,2,2],[2,3,3],[3,5]]", "is_hidden": true}]$q$::jsonb,$q$Backtrack allowing reuse. Prune when remaining<0. O(n^(T/m)).$q$,ARRAY['python','java','javascript','go','cpp'],0.67),
($q$Phone Keypad Letter Combinations$q$,$q$letter-combinations-phone-number$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['backtracking','strings'],$q$## Problem

Given a digit string `digits` (2-9), return all possible **letter combinations** it could represent on a phone keypad.$q$,$q$0 ≤ len(digits) ≤ 4 | digits[i] ∈ {'2',...,'9'}$q$,$q$[{"input": "digits = \"23\"", "output": "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]"}]$q$::jsonb,$q$[{"input": "\"23\"", "expected_output": "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]", "is_hidden": false}, {"input": "\"\"", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$Backtracking: for each digit map letters, recurse. O(4^n × n) where n=len(digits).$q$,ARRAY['python','java','javascript','go','cpp'],0.65),
($q$Chess Tournament N-Queens$q$,$q$n-queens$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['backtracking'],$q$## Problem

Place `n` queens on `n×n` board so none attack each other. Return all distinct solutions.$q$,$q$1 ≤ n ≤ 9$q$,$q$[{"input": "n = 4", "output": "[[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]"}]$q$::jsonb,$q$[{"input": "4", "expected_output": "[[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]", "is_hidden": false}, {"input": "1", "expected_output": "[[\"Q\"]]", "is_hidden": true}]$q$::jsonb,$q$Place queens row by row. Track col/diagonal/anti-diagonal sets. O(n!).$q$,ARRAY['python','java','javascript','go','cpp'],0.27),
($q$Zerodha Top K Frequent Stocks$q$,$q$top-k-frequent-elements$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['heap','hash-map','bucket-sort'],$q$## Problem

Return the `k` **most frequently** occurring elements. Better than O(n log n).$q$,$q$1 ≤ n ≤ 10^5 | 1 ≤ k ≤ distinct elements$q$,$q$[{"input": "nums = [1,1,1,2,2,3], k=2", "output": "[1,2]"}]$q$::jsonb,$q$[{"input": "[1,1,1,2,2,3]\n2", "expected_output": "[1,2]", "is_hidden": false}, {"input": "[1]\n1", "expected_output": "[1]", "is_hidden": true}]$q$::jsonb,$q$Count freqs. Min-heap of size k or bucket sort. O(n log k).$q$,ARRAY['python','java','javascript','go','cpp'],0.66),
($q$Stock Market Median Stream$q$,$q$find-median-from-data-stream$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['heap','design'],$q$## Problem

Design a data structure for `addNum(num)` and `findMedian()` on a running stream.$q$,$q$-10^5 ≤ num ≤ 10^5 | At most 5×10^4 calls$q$,$q$[{"input": "addNum(1),addNum(2),findMedian()→1.5,addNum(3),findMedian()→2.0", "output": "1.5,2.0"}]$q$::jsonb,$q$[{"input": "addNum(1),addNum(2),findMedian()", "expected_output": "1.5", "is_hidden": false}, {"input": "addNum(1),addNum(2),addNum(3),findMedian()", "expected_output": "2.0", "is_hidden": true}]$q$::jsonb,$q$Max-heap for lower half, min-heap for upper half. Balance after insert. O(log n) add, O(1) median.$q$,ARRAY['python','java','javascript','go','cpp'],0.29),
($q$Flipkart Warehouse K Closest Items$q$,$q$k-closest-points-to-origin$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['heap','arrays'],$q$## Problem

Return the `k` closest `points` to origin (0,0). Distance = Euclidean (no sqrt needed for comparison).$q$,$q$1 ≤ k ≤ points.length ≤ 10^4 | -10^4 ≤ xi,yi ≤ 10^4$q$,$q$[{"input": "points = [[1,3],[-2,2]], k=1", "output": "[[-2,2]]"}]$q$::jsonb,$q$[{"input": "[[1,3],[-2,2]]\n1", "expected_output": "[[-2,2]]", "is_hidden": false}, {"input": "[[3,3],[5,-1],[-2,4]]\n2", "expected_output": "[[3,3],[-2,4]]", "is_hidden": true}]$q$::jsonb,$q$Max-heap of size k on x²+y². O(n log k). Or Quickselect O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.67),
($q$Merge K Sorted Lists$q$,$q$merge-k-sorted-lists$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['heap','linked-list','divide-conquer'],$q$## Problem

Merge `k` sorted linked lists into one sorted linked list.$q$,$q$0 ≤ k ≤ 10^4 | 0 ≤ n ≤ 500 | -10^4 ≤ val ≤ 10^4 | Total nodes ≤ 10^4$q$,$q$[{"input": "lists = [[1,4,5],[1,3,4],[2,6]]", "output": "[1,1,2,3,4,4,5,6]"}]$q$::jsonb,$q$[{"input": "[[1,4,5],[1,3,4],[2,6]]", "expected_output": "[1,1,2,3,4,4,5,6]", "is_hidden": false}, {"input": "[[]]", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$Min-heap of (val, list_idx, node). Pop min, push next node from same list. O(N log k).$q$,ARRAY['python','java','javascript','go','cpp'],0.4),
($q$Google India Search Trie$q$,$q$implement-trie$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trie','design','strings'],$q$## Problem

Build a **Trie** with `insert(word)`, `search(word)`, and `startsWith(prefix)`.$q$,$q$1 ≤ len(word) ≤ 2000 | lowercase letters | At most 3×10^4 operations$q$,$q$[{"input": "insert(\"apple\"),search(\"apple\")→true,search(\"app\")→false,startsWith(\"app\")→true", "output": "true,false,true"}]$q$::jsonb,$q$[{"input": "insert(\"apple\"),search(\"apple\"),search(\"app\"),startsWith(\"app\")", "expected_output": "true,false,true", "is_hidden": false}, {"input": "insert(\"app\"),search(\"app\"),startsWith(\"ap\")", "expected_output": "true,true", "is_hidden": true}]$q$::jsonb,$q$TrieNode with children[26] and isEnd flag. O(m) per op where m=word length.$q$,ARRAY['python','java','javascript','go','cpp'],0.58),
($q$Nykaa Product Replace Words$q$,$q$replace-words$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trie','strings'],$q$## Problem

Replace every word in `sentence` with its shortest matching `root` from the dictionary. If no match, keep original.$q$,$q$1 ≤ roots.length ≤ 1000 | 1 ≤ len(root) ≤ 100$q$,$q$[{"input": "roots=[\"cat\",\"bat\",\"rat\"], sentence=\"the cattle was rattled by the battery\"", "output": "\"the cat was rat by the bat\""}]$q$::jsonb,$q$[{"input": "[\"cat\",\"bat\",\"rat\"]\n\"the cattle was rattled by the battery\"", "expected_output": "\"the cat was rat by the bat\"", "is_hidden": false}, {"input": "[\"a\",\"b\",\"c\"]\n\"aadsfasf absbs bbab cadsfafs\"", "expected_output": "\"a a b c\"", "is_hidden": true}]$q$::jsonb,$q$Build trie from roots. For each word traverse trie; replace on root end. O(total chars).$q$,ARRAY['python','java','javascript','go','cpp'],0.64),
($q$Jump Game II Minimum Jumps$q$,$q$jump-game-ii$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['greedy','dynamic-programming','arrays'],$q$## Problem

Given `jumps[i]` = max steps from position `i`, return the **minimum number of jumps** to reach the last index. Always reachable.$q$,$q$1 ≤ n ≤ 10^4 | 0 ≤ jumps[i] ≤ 1000$q$,$q$[{"input": "jumps = [2,3,1,1,4]", "output": "2", "explanation": "Jump 1→3 (2 steps), then 3→last (1 step)"}]$q$::jsonb,$q$[{"input": "[2,3,1,1,4]", "expected_output": "2", "is_hidden": false}, {"input": "[2,3,0,1,4]", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$Greedy BFS: track current range, next max reach. Increment jumps at range end. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.47),
($q$Binary Search IRCTC Ticket$q$,$q$binary-search$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['binary-search','arrays'],$q$## Problem

Given sorted `prices` array and `target` price, return the **index** if found, else return -1. Must be O(log n).$q$,$q$1 ≤ n ≤ 10^4 | -10^4 ≤ prices[i] ≤ 10^4 | Sorted ascending | All distinct$q$,$q$[{"input": "prices = [-1,0,3,5,9,12], target = 9", "output": "4"}, {"input": "prices = [-1,0,3,5,9,12], target = 2", "output": "-1"}]$q$::jsonb,$q$[{"input": "[-1,0,3,5,9,12]\n9", "expected_output": "4", "is_hidden": false}, {"input": "[-1,0,3,5,9,12]\n2", "expected_output": "-1", "is_hidden": true}]$q$::jsonb,$q$Standard binary search. lo=0, hi=n-1, mid=(lo+hi)//2. O(log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.8),
($q$Search Rotated Sorted Array$q$,$q$search-in-rotated-sorted-array$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['binary-search','arrays'],$q$## Problem

A sorted array was rotated at some pivot. Given `nums` and `target`, return index or -1 in O(log n).$q$,$q$1 ≤ n ≤ 5000 | -10^4 ≤ nums[i] ≤ 10^4 | All distinct$q$,$q$[{"input": "nums = [4,5,6,7,0,1,2], target = 0", "output": "4"}, {"input": "nums = [4,5,6,7,0,1,2], target = 3", "output": "-1"}]$q$::jsonb,$q$[{"input": "[4,5,6,7,0,1,2]\n0", "expected_output": "4", "is_hidden": false}, {"input": "[4,5,6,7,0,1,2]\n3", "expected_output": "-1", "is_hidden": true}]$q$::jsonb,$q$Binary search: determine which half is sorted, check if target falls in it. O(log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.48),
($q$Find Peak Element Terrain$q$,$q$find-peak-element$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['binary-search','arrays'],$q$## Problem

A peak element is strictly greater than its neighbors. Given `nums`, return the index of **any peak** in O(log n). Assume nums[-1] = nums[n] = -∞.$q$,$q$1 ≤ n ≤ 1000 | -2^31 ≤ nums[i] ≤ 2^31-1 | nums[i] ≠ nums[i+1]$q$,$q$[{"input": "nums = [1,2,3,1]", "output": "2"}, {"input": "nums = [1,2,1,3,5,6,4]", "output": "5"}]$q$::jsonb,$q$[{"input": "[1,2,3,1]", "expected_output": "2", "is_hidden": false}, {"input": "[1,2,1,3,5,6,4]", "expected_output": "5", "is_hidden": true}]$q$::jsonb,$q$Binary search: if nums[mid] < nums[mid+1], peak is on right. Else on left or at mid. O(log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.53),
($q$Median of Two Sorted Arrays$q$,$q$median-two-sorted-arrays$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['binary-search','arrays','divide-conquer'],$q$## Problem

Given two sorted arrays `nums1` and `nums2`, find the **median** of the combined sorted array. O(log(m+n)) required.$q$,$q$0 ≤ m,n ≤ 1000 | -10^6 ≤ nums[i] ≤ 10^6 | m+n ≥ 1$q$,$q$[{"input": "nums1 = [1,3], nums2 = [2]", "output": "2.0"}, {"input": "nums1 = [1,2], nums2 = [3,4]", "output": "2.5"}]$q$::jsonb,$q$[{"input": "[1,3]\n[2]", "expected_output": "2.0", "is_hidden": false}, {"input": "[1,2]\n[3,4]", "expected_output": "2.5", "is_hidden": true}]$q$::jsonb,$q$Binary search on smaller array to find correct partition. O(log(min(m,n))).$q$,ARRAY['python','java','javascript','go','cpp'],0.25),
($q$Search 2D Matrix Flipkart$q$,$q$search-a-2d-matrix$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['binary-search','matrix'],$q$## Problem

Given an `m×n` matrix where each row is sorted and first element of each row > last element of previous row, determine if `target` exists. O(log(m×n)).$q$,$q$1 ≤ m,n ≤ 100 | -10^4 ≤ matrix[i][j],target ≤ 10^4$q$,$q$[{"input": "matrix=[[1,3,5,7],[10,11,16,20],[23,30,34,60]], target=3", "output": "true"}]$q$::jsonb,$q$[{"input": "[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\n3", "expected_output": "true", "is_hidden": false}, {"input": "[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\n13", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$Treat matrix as flat sorted array. Binary search with (mid//n, mid%n). O(log(m×n)).$q$,ARRAY['python','java','javascript','go','cpp'],0.55),
($q$Stock Buy Sell Multiple Times$q$,$q$best-time-buy-sell-stock-ii$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['greedy','arrays'],$q$## Problem

BSE stock: `prices[i]` = price on day `i`. You can buy/sell **multiple times** (hold at most one share at a time). Maximize total profit.$q$,$q$1 ≤ n ≤ 3×10^4 | 0 ≤ prices[i] ≤ 10^4$q$,$q$[{"input": "prices = [7,1,5,3,6,4]", "output": "7", "explanation": "Buy 1 sell 5 (+4), buy 3 sell 6 (+3)"}]$q$::jsonb,$q$[{"input": "[7,1,5,3,6,4]", "expected_output": "7", "is_hidden": false}, {"input": "[1,2,3,4,5]", "expected_output": "4", "is_hidden": true}]$q$::jsonb,$q$Sum all positive differences (prices[i]-prices[i-1] if positive). Greedy. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.7),
($q$Stock with Cooldown NSE$q$,$q$best-time-buy-sell-stock-cooldown$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','arrays'],$q$## Problem

Buy/sell multiple times but after selling you must wait 1 day (cooldown). Maximize profit.$q$,$q$1 ≤ n ≤ 5000 | 0 ≤ prices[i] ≤ 1000$q$,$q$[{"input": "prices = [1,2,3,0,2]", "output": "3", "explanation": "Buy 1 sell 3 (profit 2), cooldown, buy 0 sell 2 (profit 2) = wait actually optimal is 3"}]$q$::jsonb,$q$[{"input": "[1,2,3,0,2]", "expected_output": "3", "is_hidden": false}, {"input": "[1]", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$States: held, sold, rest. held[i]=max(held[i-1],rest[i-1]-price); sold[i]=held[i-1]+price; rest[i]=max(rest[i-1],sold[i-1]). O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.49),
($q$Word Search Grid Puzzle$q$,$q$word-search$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['backtracking','matrix','dfs'],$q$## Problem

Given `m×n` character grid `board` and string `word`, return `true` if the word can be constructed from **sequentially adjacent cells** (no reuse).$q$,$q$1 ≤ m,n ≤ 6 | 1 ≤ len(word) ≤ 15 | board and word consist of uppercase English letters$q$,$q$[{"input": "board=[[\"A\",\"B\",\"C\"],[\"S\",\"F\",\"C\"],[\"A\",\"D\",\"E\"]], word=\"ABCCED\"", "output": "true"}]$q$::jsonb,$q$[{"input": "[[\"A\",\"B\",\"C\"],[\"S\",\"F\",\"C\"],[\"A\",\"D\",\"E\"]]\n\"ABCCED\"", "expected_output": "true", "is_hidden": false}, {"input": "[[\"A\",\"B\",\"C\"],[\"S\",\"F\",\"C\"],[\"A\",\"D\",\"E\"]]\n\"ABCB\"", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$DFS/backtracking from each cell. Mark visited, unmark on backtrack. O(m×n×4^len(word)).$q$,ARRAY['python','java','javascript','go','cpp'],0.5),
($q$Permutations All Arrangements$q$,$q$permutations$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['backtracking','arrays'],$q$## Problem

Given array of **distinct** integers `nums`, return all possible permutations.$q$,$q$1 ≤ n ≤ 6 | -10 ≤ nums[i] ≤ 10 | All distinct$q$,$q$[{"input": "nums = [1,2,3]", "output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"}]$q$::jsonb,$q$[{"input": "[1,2,3]", "expected_output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]", "is_hidden": false}, {"input": "[0,1]", "expected_output": "[[0,1],[1,0]]", "is_hidden": true}]$q$::jsonb,$q$Backtrack: swap elements at current position with each subsequent. O(n×n!).$q$,ARRAY['python','java','javascript','go','cpp'],0.73),
($q$Generate All Valid Parentheses$q$,$q$generate-parentheses$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['backtracking','strings'],$q$## Problem

Generate all combinations of **n pairs of well-formed parentheses**.$q$,$q$1 ≤ n ≤ 8$q$,$q$[{"input": "n = 3", "output": "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]"}]$q$::jsonb,$q$[{"input": "3", "expected_output": "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]", "is_hidden": false}, {"input": "1", "expected_output": "[\"()\"]", "is_hidden": true}]$q$::jsonb,$q$Backtrack: add '(' if open<n, add ')' if close<open. O(4^n/sqrt(n)).$q$,ARRAY['python','java','javascript','go','cpp'],0.69)
ON CONFLICT (slug) DO NOTHING;