-- STEP 7: Problems 101–120 of 201
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate)
VALUES
($q$Palindrome Partitioning$q$,$q$palindrome-partitioning$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['backtracking','dynamic-programming','strings'],$q$## Problem

Partition string `s` such that every substring is a **palindrome**. Return all possible partitionings.$q$,$q$1 ≤ len(s) ≤ 16 | s consists of lowercase letters$q$,$q$[{"input": "s = \"aab\"", "output": "[[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]"}]$q$::jsonb,$q$[{"input": "\"aab\"", "expected_output": "[[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]", "is_hidden": false}, {"input": "\"a\"", "expected_output": "[[\"a\"]]", "is_hidden": true}]$q$::jsonb,$q$Backtrack: for each prefix that is a palindrome, recurse on remainder. Precompute palindrome DP table. O(n×2^n).$q$,ARRAY['python','java','javascript','go','cpp'],0.57),
($q$Serialize Deserialize Binary Tree$q$,$q$serialize-deserialize-binary-tree$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['trees','bfs','design'],$q$## Problem

Design an algorithm to **serialize** a binary tree to a string and **deserialize** the string back to the original tree.$q$,$q$0 ≤ n ≤ 10^4 | -1000 ≤ val ≤ 1000$q$,$q$[{"input": "root = [1,2,3,null,null,4,5]", "output": "[1,2,3,null,null,4,5]", "explanation": "Serialize then deserialize gives same tree"}]$q$::jsonb,$q$[{"input": "[1,2,3,null,null,4,5]", "expected_output": "[1,2,3,null,null,4,5]", "is_hidden": false}, {"input": "[]", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$BFS serialization with null markers. Split on comma to deserialize. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.3),
($q$Flatten Binary Tree to List$q$,$q$flatten-binary-tree-to-linked-list$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','dfs'],$q$## Problem

Flatten a binary tree into a **linked list** in-place in pre-order traversal order (using right pointers).$q$,$q$0 ≤ n ≤ 2000 | -100 ≤ val ≤ 100$q$,$q$[{"input": "root = [1,2,5,3,4,null,6]", "output": "[1,null,2,null,3,null,4,null,5,null,6]"}]$q$::jsonb,$q$[{"input": "[1,2,5,3,4,null,6]", "expected_output": "[1,null,2,null,3,null,4,null,5,null,6]", "is_hidden": false}, {"input": "[]", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$Morris traversal or pre-order stack. For each node, right-most of left subtree points to right. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.43),
($q$Graph Clone Adjacency$q$,$q$clone-graph$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','dfs','bfs','hash-map'],$q$## Problem

Given a reference to a graph node, return a **deep copy** of the entire connected undirected graph.$q$,$q$1 ≤ n ≤ 100 | 0 ≤ edges ≤ 100 | No self-loops or repeated edges$q$,$q$[{"input": "adjList = [[2,4],[1,3],[2,4],[1,3]]", "output": "[[2,4],[1,3],[2,4],[1,3]]"}]$q$::jsonb,$q$[{"input": "[[2,4],[1,3],[2,4],[1,3]]", "expected_output": "[[2,4],[1,3],[2,4],[1,3]]", "is_hidden": false}, {"input": "[[]]", "expected_output": "[[]]", "is_hidden": true}]$q$::jsonb,$q$DFS/BFS with hashmap from original→clone. Create clone if not exists, recurse neighbors. O(V+E).$q$,ARRAY['python','java','javascript','go','cpp'],0.54),
($q$Union Find Components$q$,$q$number-of-connected-components$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','union-find','dfs'],$q$## Problem

Given `n` nodes and list of `edges`, return the **number of connected components** in the undirected graph.$q$,$q$1 ≤ n ≤ 2000 | 0 ≤ edges.length ≤ 5000$q$,$q$[{"input": "n=5, edges=[[0,1],[1,2],[3,4]]", "output": "2"}, {"input": "n=5, edges=[[0,1],[1,2],[2,3],[3,4]]", "output": "1"}]$q$::jsonb,$q$[{"input": "5\n[[0,1],[1,2],[3,4]]", "expected_output": "2", "is_hidden": false}, {"input": "5\n[[0,1],[1,2],[2,3],[3,4]]", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$Union-Find or DFS. Count components by counting root nodes. O(n×α(n)) with Union-Find.$q$,ARRAY['python','java','javascript','go','cpp'],0.62),
($q$01 Matrix Distance$q$,$q$01-matrix$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','bfs','dynamic-programming'],$q$## Problem

Given binary matrix, return a matrix where each cell contains the **distance to the nearest 0**.$q$,$q$1 ≤ m,n ≤ 10^4 | 0 ≤ matrix[i][j] ≤ 1 | At least one 0$q$,$q$[{"input": "mat = [[0,0,0],[0,1,0],[0,0,0]]", "output": "[[0,0,0],[0,1,0],[0,0,0]]"}, {"input": "mat = [[0,0,0],[0,1,0],[1,1,1]]", "output": "[[0,0,0],[0,1,0],[1,2,1]]"}]$q$::jsonb,$q$[{"input": "[[0,0,0],[0,1,0],[1,1,1]]", "expected_output": "[[0,0,0],[0,1,0],[1,2,1]]", "is_hidden": false}, {"input": "[[0,0,0],[0,1,0],[0,0,0]]", "expected_output": "[[0,0,0],[0,1,0],[0,0,0]]", "is_hidden": true}]$q$::jsonb,$q$Multi-source BFS from all 0s simultaneously. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.55),
($q$Accounts Merge Social Network$q$,$q$accounts-merge$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','union-find','strings'],$q$## Problem

Merge accounts if any two accounts share an email. Each account = [name, email1, email2, ...]. Return merged accounts with sorted emails.$q$,$q$1 ≤ accounts.length ≤ 1000 | 2 ≤ accounts[i].length ≤ 10$q$,$q$[{"input": "accounts=[[\"John\",\"j@j.com\",\"j2@j.com\"],[\"John\",\"j3@j.com\"],[\"Mary\",\"m@m.com\"],[\"John\",\"j3@j.com\",\"j@j.com\"]]", "output": "[[\"John\",\"j@j.com\",\"j2@j.com\",\"j3@j.com\"],[\"Mary\",\"m@m.com\"]]"}]$q$::jsonb,$q$[{"input": "[[\"John\",\"j@j.com\",\"j2@j.com\"],[\"John\",\"j3@j.com\"],[\"Mary\",\"m@m.com\"],[\"John\",\"j3@j.com\",\"j@j.com\"]]", "expected_output": "[[\"John\",\"j@j.com\",\"j2@j.com\",\"j3@j.com\"],[\"Mary\",\"m@m.com\"]]", "is_hidden": false}, {"input": "[[\"Gabe\",\"Gabe0@m.co\",\"Gabe3@m.co\"],[\"Kevin\",\"Kevin3@m.co\",\"Kevin5@m.co\"]]", "expected_output": "[[\"Gabe\",\"Gabe0@m.co\",\"Gabe3@m.co\"],[\"Kevin\",\"Kevin3@m.co\",\"Kevin5@m.co\"]]", "is_hidden": true}]$q$::jsonb,$q$Union-Find on emails. Group by root, sort emails. O(A log A) where A = total emails.$q$,ARRAY['python','java','javascript','go','cpp'],0.44),
($q$Word Ladder Transformation$q$,$q$word-ladder$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['graphs','bfs','strings'],$q$## Problem

Transform `beginWord` to `endWord` changing one letter at a time (all intermediates in `wordList`). Return the **length of shortest transformation sequence**, or 0 if impossible.$q$,$q$1 ≤ len(beginWord) ≤ 10 | 1 ≤ wordList.length ≤ 5000$q$,$q$[{"input": "beginWord=\"hit\", endWord=\"cog\", wordList=[\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]", "output": "5", "explanation": "hit→hot→dot→dog→cog"}]$q$::jsonb,$q$[{"input": "\"hit\"\n\"cog\"\n[\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]", "expected_output": "5", "is_hidden": false}, {"input": "\"hit\"\n\"cog\"\n[\"hot\",\"dot\",\"dog\",\"lot\",\"log\"]", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$BFS: for each word, try all single-char substitutions. Use set for O(1) lookup. O(M²×N) where M=word length, N=words.$q$,ARRAY['python','java','javascript','go','cpp'],0.28),
($q$Longest Common Subsequence DNA$q$,$q$longest-common-subsequence$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','strings'],$q$## Problem

Given strings `text1` and `text2`, return the length of their **longest common subsequence** (LCS). If none, return 0.$q$,$q$1 ≤ len(text1),len(text2) ≤ 1000 | lowercase letters$q$,$q$[{"input": "text1=\"abcde\", text2=\"ace\"", "output": "3", "explanation": "LCS is \"ace\""}, {"input": "text1=\"abc\", text2=\"abc\"", "output": "3"}]$q$::jsonb,$q$[{"input": "\"abcde\"\n\"ace\"", "expected_output": "3", "is_hidden": false}, {"input": "\"abc\"\n\"def\"", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$dp[i][j] = LCS of text1[0..i] and text2[0..j]. If chars match +1, else max(dp[i-1][j], dp[i][j-1]). O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.58),
($q$Edit Distance Typo Correction$q$,$q$edit-distance$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['dynamic-programming','strings'],$q$## Problem

Given `word1` and `word2`, find the **minimum edit distance** (insert, delete, replace) to transform word1 to word2.$q$,$q$0 ≤ len(word1),len(word2) ≤ 500 | lowercase letters$q$,$q$[{"input": "word1=\"horse\", word2=\"ros\"", "output": "3", "explanation": "horse→rorse→rose→ros"}]$q$::jsonb,$q$[{"input": "\"horse\"\n\"ros\"", "expected_output": "3", "is_hidden": false}, {"input": "\"intention\"\n\"execution\"", "expected_output": "5", "is_hidden": true}]$q$::jsonb,$q$dp[i][j] = edit dist for word1[0..i], word2[0..j]. If chars match dp[i-1][j-1]; else min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])+1. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.38),
($q$Longest Palindromic Subsequence$q$,$q$longest-palindromic-subsequence$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','strings'],$q$## Problem

Given string `s`, find the length of the **longest palindromic subsequence**.$q$,$q$1 ≤ len(s) ≤ 1000 | s consists of lowercase letters$q$,$q$[{"input": "s = \"bbbab\"", "output": "4", "explanation": "\"bbbb\""}, {"input": "s = \"cbbd\"", "output": "2"}]$q$::jsonb,$q$[{"input": "\"bbbab\"", "expected_output": "4", "is_hidden": false}, {"input": "\"cbbd\"", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$LPS(s) = LCS(s, reverse(s)). Or interval DP: dp[i][j]=dp[i+1][j-1]+2 if s[i]==s[j]. O(n²).$q$,ARRAY['python','java','javascript','go','cpp'],0.51),
($q$Counting Bits Popcount$q$,$q$counting-bits$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['dynamic-programming','bit-manipulation'],$q$## Problem

Return array `ans` where `ans[i]` = number of **1 bits** in binary representation of `i`, for 0 ≤ i ≤ n.$q$,$q$0 ≤ n ≤ 10^5$q$,$q$[{"input": "n = 5", "output": "[0,1,1,2,1,2]", "explanation": "0→0, 1→1, 2→1, 3→2, 4→1, 5→2"}]$q$::jsonb,$q$[{"input": "5", "expected_output": "[0,1,1,2,1,2]", "is_hidden": false}, {"input": "2", "expected_output": "[0,1,1]", "is_hidden": true}]$q$::jsonb,$q$dp[i] = dp[i>>1] + (i&1). O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.76),
($q$Candy Distribution CBSE$q$,$q$candy$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['greedy','arrays'],$q$## Problem

Teacher distributes candies to n students. Each student must get ≥1 candy. Students with higher rating than adjacent get more candies. Find **minimum total candies**.$q$,$q$1 ≤ n ≤ 2×10^4 | 0 ≤ ratings[i] ≤ 2×10^4$q$,$q$[{"input": "ratings = [1,0,2]", "output": "5", "explanation": "[2,1,2]"}, {"input": "ratings = [1,2,2]", "output": "4", "explanation": "[1,2,1]"}]$q$::jsonb,$q$[{"input": "[1,0,2]", "expected_output": "5", "is_hidden": false}, {"input": "[1,2,2]", "expected_output": "4", "is_hidden": true}]$q$::jsonb,$q$Two passes: left-to-right (increasing), right-to-left (decreasing). Take max at each position. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.33),
($q$Assign Cookies School Kids$q$,$q$assign-cookies$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['greedy','arrays','sorting'],$q$## Problem

Each child has a greed factor `g[i]`, each cookie has size `s[j]`. Cookie `j` satisfies child `i` if `s[j] >= g[i]`. Maximize satisfied children.$q$,$q$1 ≤ g.length ≤ 3×10^4 | 0 ≤ g[i],s[j] ≤ 2^31-1$q$,$q$[{"input": "g = [1,2,3], s = [1,1]", "output": "1"}, {"input": "g = [1,2], s = [1,2,3]", "output": "2"}]$q$::jsonb,$q$[{"input": "[1,2,3]\n[1,1]", "expected_output": "1", "is_hidden": false}, {"input": "[1,2]\n[1,2,3]", "expected_output": "2", "is_hidden": true}]$q$::jsonb,$q$Sort both. Two-pointer greedy: match smallest adequate cookie to smallest greedy child. O(n log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.66),
($q$Two City Scheduling Flight$q$,$q$two-city-scheduling$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['greedy','arrays','sorting'],$q$## Problem

2n people, each with cost to go to city A or B. Send exactly n to each city. Return **minimum total cost**.$q$,$q$2 ≤ n ≤ 100 | costs.length == 2n | 1 ≤ costs[i][j] ≤ 1000$q$,$q$[{"input": "costs = [[10,20],[30,200],[400,50],[30,20]]", "output": "110", "explanation": "Send persons 0,1 to A, persons 2,3 to B"}]$q$::jsonb,$q$[{"input": "[[10,20],[30,200],[400,50],[30,20]]", "expected_output": "110", "is_hidden": false}, {"input": "[[259,770],[448,54],[926,667],[184,139],[840,118],[577,469]]", "expected_output": "1859", "is_hidden": true}]$q$::jsonb,$q$Sort by (cost_A - cost_B). First n go to A, rest to B. O(n log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.64),
($q$Minimum Arrows Burst Balloons$q$,$q$minimum-number-arrows-burst-balloons$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['greedy','intervals','sorting'],$q$## Problem

Balloons at x-coordinates `[start, end]`. Vertical arrow shot at `x` bursts all balloons where `start ≤ x ≤ end`. Return **minimum arrows** to burst all balloons.$q$,$q$1 ≤ points.length ≤ 10^4 | -2^31 ≤ start ≤ end ≤ 2^31-1$q$,$q$[{"input": "points = [[10,16],[2,8],[1,6],[7,12]]", "output": "2"}]$q$::jsonb,$q$[{"input": "[[10,16],[2,8],[1,6],[7,12]]", "expected_output": "2", "is_hidden": false}, {"input": "[[1,2],[3,4],[5,6],[7,8]]", "expected_output": "4", "is_hidden": true}]$q$::jsonb,$q$Sort by end. Greedily shoot at current end. Move to next non-overlapping balloon. O(n log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.57),
($q$Power Function Fast Exponentiation$q$,$q$powx-n$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['math','recursion','binary-search'],$q$## Problem

Implement `pow(x, n)` — compute **x raised to the power n**. Handle negative n.$q$,$q$-100.0 < x < 100.0 | -2^31 ≤ n ≤ 2^31-1 | -10^4 < x^n < 10^4$q$,$q$[{"input": "x=2.0, n=10", "output": "1024.0"}, {"input": "x=2.1, n=3", "output": "9.261"}, {"input": "x=2.0, n=-2", "output": "0.25"}]$q$::jsonb,$q$[{"input": "2.0\n10", "expected_output": "1024.0", "is_hidden": false}, {"input": "2.0\n-2", "expected_output": "0.25", "is_hidden": true}]$q$::jsonb,$q$Fast exponentiation: if n even, pow(x*x, n/2). If n odd, x*pow(x*x, (n-1)/2). O(log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.62),
($q$Happy Number Cycle Detection$q$,$q$happy-number$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['math','hash-set','floyd-cycle'],$q$## Problem

A happy number: repeatedly replace with sum of squares of digits; if reaches 1 → happy. If cycles without reaching 1 → not happy. Return true if `n` is happy.$q$,$q$1 ≤ n ≤ 2^31-1$q$,$q$[{"input": "n = 19", "output": "true", "explanation": "1²+9²=82 → 8²+2²=68 → ... → 1"}, {"input": "n = 2", "output": "false"}]$q$::jsonb,$q$[{"input": "19", "expected_output": "true", "is_hidden": false}, {"input": "2", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$Use set or Floyd's to detect cycle. O(log n) per step.$q$,ARRAY['python','java','javascript','go','cpp'],0.72),
($q$XOR Maximum Pair Bitwise$q$,$q$maximum-xor-two-numbers$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['bit-manipulation','trie'],$q$## Problem

Given integer array `nums`, find the **maximum XOR** of any two elements.$q$,$q$1 ≤ n ≤ 2×10^5 | 0 ≤ nums[i] ≤ 2^31-1$q$,$q$[{"input": "nums = [3,10,5,25,2,8]", "output": "28", "explanation": "5 XOR 25 = 28"}]$q$::jsonb,$q$[{"input": "[3,10,5,25,2,8]", "expected_output": "28", "is_hidden": false}, {"input": "[0]", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$Build trie of binary representations. For each num, traverse trie greedily choosing opposite bit. O(n×32).$q$,ARRAY['python','java','javascript','go','cpp'],0.38),
($q$Sudoku Solver Game$q$,$q$sudoku-solver$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['backtracking','matrix'],$q$## Problem

Solve a Sudoku puzzle by filling in empty cells marked `'.'`. One valid solution guaranteed.$q$,$q$board is 9×9 | digits 1-9 and '.' | Valid puzzle with unique solution$q$,$q$[{"input": "board = [[\"5\",\"3\",\".\",\".\",\"7\",...]]", "output": "Solved board"}]$q$::jsonb,$q$[{"input": "[[\"5\",\"3\",\".\",\".\",\"7\",\".\",\".\",\".\",\".\"],[\"6\",\".\",\".\",\"1\",\"9\",\"5\",\".\",\".\",\".\"],[\".\",\"9\",\"8\",\".\",\".\",\".\",\".\",\"6\",\".\"],[\"8\",\".\",\".\",\".\",\"6\",\".\",\".\",\".\",\"3\"],[\"4\",\".\",\".\",\"8\",\".\",\"3\",\".\",\".\",\"1\"],[\"7\",\".\",\".\",\".\",\"2\",\".\",\".\",\".\",\"6\"],[\".\",\"6\",\".\",\".\",\".\",\".\",\"2\",\"8\",\".\"],[\".\",\".\",\".\",\"4\",\"1\",\"9\",\".\",\".\",\"5\"],[\".\",\".\",\".\",\".\",\"8\",\".\",\".\",\"7\",\"9\"]]", "expected_output": "[[\"5\",\"3\",\"4\",\"6\",\"7\",\"8\",\"9\",\"1\",\"2\"],[\"6\",\"7\",\"2\",\"1\",\"9\",\"5\",\"3\",\"4\",\"8\"],[\"1\",\"9\",\"8\",\"3\",\"4\",\"2\",\"5\",\"6\",\"7\"],[\"8\",\"5\",\"9\",\"7\",\"6\",\"1\",\"4\",\"2\",\"3\"],[\"4\",\"2\",\"6\",\"8\",\"5\",\"3\",\"7\",\"9\",\"1\"],[\"7\",\"1\",\"3\",\"9\",\"2\",\"4\",\"8\",\"5\",\"6\"],[\"9\",\"6\",\"1\",\"5\",\"3\",\"7\",\"2\",\"8\",\"4\"],[\"2\",\"8\",\"7\",\"4\",\"1\",\"9\",\"6\",\"3\",\"5\"],[\"3\",\"4\",\"5\",\"2\",\"8\",\"6\",\"1\",\"7\",\"9\"]]", "is_hidden": false}]$q$::jsonb,$q$Backtrack: for each '.' cell, try 1-9, check row/col/box validity, recurse. O(9^empty_cells).$q$,ARRAY['python','java','javascript','go','cpp'],0.22)
ON CONFLICT (slug) DO NOTHING;