-- STEP 8: Problems 121–140 of 201
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate)
VALUES
($q$Sort Merge Algorithm$q$,$q$sort-list$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['linked-list','sorting','divide-conquer'],$q$## Problem

Sort a linked list in **O(n log n)** time using **O(1)** extra space.$q$,$q$0 ≤ n ≤ 5×10^4 | -10^5 ≤ val ≤ 10^5$q$,$q$[{"input": "head = 4→2→1→3", "output": "1→2→3→4"}, {"input": "head = -1→5→3→4→0", "output": "-1→0→3→4→5"}]$q$::jsonb,$q$[{"input": "[4,2,1,3]", "expected_output": "[1,2,3,4]", "is_hidden": false}, {"input": "[-1,5,3,4,0]", "expected_output": "[-1,0,3,4,5]", "is_hidden": true}]$q$::jsonb,$q$Find mid with slow/fast pointers. Split. Recursively sort. Merge. O(n log n) time, O(log n) recursion stack.$q$,ARRAY['python','java','javascript','go','cpp'],0.48),
($q$Reorder Delivery List$q$,$q$reorder-list$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['linked-list','two-pointers'],$q$## Problem

Given linked list `L0→L1→...→Ln`, reorder to `L0→Ln→L1→Ln-1→L2→Ln-2→...` in-place.$q$,$q$1 ≤ n ≤ 5×10^4 | 1 ≤ val ≤ 1000$q$,$q$[{"input": "head = 1→2→3→4", "output": "1→4→2→3"}, {"input": "head = 1→2→3→4→5", "output": "1→5→2→4→3"}]$q$::jsonb,$q$[{"input": "[1,2,3,4]", "expected_output": "[1,4,2,3]", "is_hidden": false}, {"input": "[1,2,3,4,5]", "expected_output": "[1,5,2,4,3]", "is_hidden": true}]$q$::jsonb,$q$Find mid, reverse second half, merge two halves alternately. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.52),
($q$Palindrome Linked List Check$q$,$q$palindrome-linked-list$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['linked-list','two-pointers','stack'],$q$## Problem

Determine if a linked list is a **palindrome** in O(n) time and O(1) space.$q$,$q$1 ≤ n ≤ 10^5 | 0 ≤ val ≤ 9$q$,$q$[{"input": "head = 1→2→2→1", "output": "true"}, {"input": "head = 1→2", "output": "false"}]$q$::jsonb,$q$[{"input": "[1,2,2,1]", "expected_output": "true", "is_hidden": false}, {"input": "[1,2]", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$Find mid, reverse second half, compare with first half, restore. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.59),
($q$Symmetric Tree Mirror$q$,$q$symmetric-tree$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['trees','dfs','bfs'],$q$## Problem

Determine if a binary tree is a **mirror image** of itself (symmetric around center).$q$,$q$1 ≤ n ≤ 1000 | -100 ≤ val ≤ 100$q$,$q$[{"input": "root = [1,2,2,3,4,4,3]", "output": "true"}, {"input": "root = [1,2,2,null,3,null,3]", "output": "false"}]$q$::jsonb,$q$[{"input": "[1,2,2,3,4,4,3]", "expected_output": "true", "is_hidden": false}, {"input": "[1,2,2,null,3,null,3]", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$DFS isMirror(left, right): check vals, recurse isMirror(l.left,r.right) and isMirror(l.right,r.left). O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.75),
($q$Diameter of Binary Tree$q$,$q$diameter-of-binary-tree$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['trees','dfs'],$q$## Problem

Find the **diameter** of a binary tree — the length of the longest path between any two nodes (may not pass through root).$q$,$q$1 ≤ n ≤ 10^4 | -100 ≤ val ≤ 100$q$,$q$[{"input": "root = [1,2,3,4,5]", "output": "3", "explanation": "Path [4,2,1,3] has length 3"}]$q$::jsonb,$q$[{"input": "[1,2,3,4,5]", "expected_output": "3", "is_hidden": false}, {"input": "[1,2]", "expected_output": "1", "is_hidden": true}]$q$::jsonb,$q$DFS returns depth. At each node update ans = max(ans, leftDepth+rightDepth). O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.79),
($q$Balanced Binary Tree Check$q$,$q$balanced-binary-tree$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['trees','dfs'],$q$## Problem

Determine if a binary tree is **height-balanced** — for every node, the heights of left and right subtrees differ by at most 1.$q$,$q$0 ≤ n ≤ 5000 | -10^4 ≤ val ≤ 10^4$q$,$q$[{"input": "root = [3,9,20,null,null,15,7]", "output": "true"}, {"input": "root = [1,2,2,3,3,null,null,4,4]", "output": "false"}]$q$::jsonb,$q$[{"input": "[3,9,20,null,null,15,7]", "expected_output": "true", "is_hidden": false}, {"input": "[1,2,2,3,3,null,null,4,4]", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$DFS: return -1 if unbalanced subtree found. Otherwise return height. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.71),
($q$Reorganize String No Adjacent$q$,$q$reorganize-string$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['heap','greedy','strings'],$q$## Problem

Rearrange `s` so that **no two adjacent characters are the same**. Return any valid arrangement, or "" if impossible.$q$,$q$1 ≤ len(s) ≤ 500 | s consists of lowercase letters$q$,$q$[{"input": "s = \"aab\"", "output": "\"aba\""}, {"input": "s = \"aaab\"", "output": "\"\""}]$q$::jsonb,$q$[{"input": "\"aab\"", "expected_output": "\"aba\"", "is_hidden": false}, {"input": "\"aaab\"", "expected_output": "\"\"", "is_hidden": true}]$q$::jsonb,$q$Max-heap by frequency. Always pick most frequent that differs from last placed. O(n log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.52),
($q$Remove K Digits Make Smallest$q$,$q$remove-k-digits$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['stack','greedy','strings'],$q$## Problem

Given number string `num` and integer `k`, remove `k` digits to make the **smallest possible number**. No leading zeros.$q$,$q$1 ≤ len(num) ≤ 10^5 | 0 ≤ k ≤ len(num) | num contains only digits$q$,$q$[{"input": "num = \"1432219\", k = 3", "output": "\"1219\""}, {"input": "num = \"10200\", k = 1", "output": "\"200\""}]$q$::jsonb,$q$[{"input": "\"1432219\"\n3", "expected_output": "\"1219\"", "is_hidden": false}, {"input": "\"10200\"\n1", "expected_output": "\"200\"", "is_hidden": true}]$q$::jsonb,$q$Monotonic increasing stack. Pop larger digits while k>0. Trim leading zeros. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.45),
($q$Infosys Employee Second Highest Salary$q$,$q$second-highest-salary$q$,$q$Easy$q$,$q$SQL$q$,ARRAY['sql','subquery','aggregation'],$q$## Problem

The Infosys HR database has an `Employee` table:
```sql
| Id | Salary |
|----|--------|
| 1  | 100000 |
| 2  | 200000 |
| 3  | 300000 |
```
Write a SQL query to find the **second highest salary**. Return `null` if it doesn't exist.$q$,$q$Table: Employee(Id INT, Salary INT) | May have duplicate salaries$q$,$q$[{"input": "Employee: [(1,100000),(2,200000),(3,300000)]", "output": "200000"}, {"input": "Employee: [(1,100000)]", "output": "null"}]$q$::jsonb,$q$[{"input": "[(1,100),(2,200),(3,300)]", "expected_output": "200", "is_hidden": false}, {"input": "[(1,100)]", "expected_output": "null", "is_hidden": true}]$q$::jsonb,$q$SELECT MAX(Salary) FROM Employee WHERE Salary < (SELECT MAX(Salary) FROM Employee). Or use OFFSET 1.$q$,ARRAY['mysql','postgresql'],0.65),
($q$TCS Rank Employee Scores$q$,$q$rank-scores$q$,$q$Medium$q$,$q$SQL$q$,ARRAY['sql','window-functions','ranking'],$q$## Problem

TCS's performance database has a `Scores` table. Write a SQL query to **rank scores** — same scores get same rank, ranks are consecutive (dense rank). Sort by score descending.$q$,$q$Table: Scores(Id INT, Score DECIMAL) | No NULL scores$q$,$q$[{"input": "Scores: [(1,3.50),(2,3.65),(3,4.00),(4,3.85),(5,4.00),(6,3.65)]", "output": "[(4.00,1),(4.00,1),(3.85,2),(3.65,3),(3.65,3),(3.50,4)]"}]$q$::jsonb,$q$[{"input": "[(1,3.50),(2,3.65),(3,4.00)]", "expected_output": "[(4.00,1),(3.65,2),(3.50,3)]", "is_hidden": false}, {"input": "[(1,1.0)]", "expected_output": "[(1.0,1)]", "is_hidden": true}]$q$::jsonb,$q$SELECT Score, DENSE_RANK() OVER (ORDER BY Score DESC) AS 'Rank' FROM Scores ORDER BY Score DESC.$q$,ARRAY['mysql','postgresql'],0.58),
($q$Wipro Rising Temperature Days$q$,$q$rising-temperature$q$,$q$Easy$q$,$q$SQL$q$,ARRAY['sql','self-join','date-functions'],$q$## Problem

Wipro's data center temperature log has a `Weather` table (Id, RecordDate, Temperature). Find all dates where temperature was **higher than the previous day**. Return the IDs.$q$,$q$Table: Weather(Id INT, RecordDate DATE, Temperature INT)$q$,$q$[{"input": "Weather: [(1,'2015-01-01',10),(2,'2015-01-02',25),(3,'2015-01-03',20),(4,'2015-01-04',30)]", "output": "[2,4]"}]$q$::jsonb,$q$[{"input": "[(1,'2015-01-01',10),(2,'2015-01-02',25)]", "expected_output": "[2]", "is_hidden": false}, {"input": "[(1,'2015-01-01',10),(2,'2015-01-03',25)]", "expected_output": "[2]", "is_hidden": true}]$q$::jsonb,$q$Self-join or LAG window function. WHERE w1.Temperature > w2.Temperature AND DATEDIFF(w1.RecordDate, w2.RecordDate) = 1.$q$,ARRAY['mysql','postgresql'],0.72),
($q$Amazon India Customers Without Orders$q$,$q$customers-who-never-order$q$,$q$Easy$q$,$q$SQL$q$,ARRAY['sql','left-join','subquery'],$q$## Problem

Amazon India has `Customers(Id, Name)` and `Orders(Id, CustomerId)` tables. Find all customers who **never placed an order**.$q$,$q$Tables: Customers(Id INT, Name VARCHAR) | Orders(Id INT, CustomerId INT)$q$,$q$[{"input": "Customers:[(1,'Henry'),(2,'Arun'),(3,'Priya')] | Orders:[(1,3),(2,1)]", "output": "['Arun']", "explanation": "Customer 2 (Arun) has no orders"}]$q$::jsonb,$q$[{"input": "Customers:[(1,'A'),(2,'B')] Orders:[(1,1)]", "expected_output": "['B']", "is_hidden": false}, {"input": "Customers:[(1,'A')] Orders:[(1,1)]", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$SELECT Name FROM Customers LEFT JOIN Orders ON CustomerId=Id WHERE Orders.Id IS NULL. Or NOT IN subquery.$q$,ARRAY['mysql','postgresql'],0.77),
($q$Flipkart Employee Manager Salary$q$,$q$employees-earning-more-than-managers$q$,$q$Easy$q$,$q$SQL$q$,ARRAY['sql','self-join'],$q$## Problem

Flipkart's HR has `Employee(Id, Name, Salary, ManagerId)`. Find employees who earn **more than their manager**.$q$,$q$ManagerId references Id in same table | May be NULL for top-level employees$q$,$q$[{"input": "[(1,'Rohan',100000,3),(2,'Priya',85000,1),(3,'Suresh',70000,null)]", "output": "['Rohan']", "explanation": "Rohan earns 100000 > manager Suresh's 70000"}]$q$::jsonb,$q$[{"input": "[(1,'Rohan',100000,3),(2,'Priya',85000,1),(3,'Suresh',70000,null)]", "expected_output": "['Rohan']", "is_hidden": false}, {"input": "[(1,'A',1000,null)]", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$SELECT e.Name FROM Employee e JOIN Employee m ON e.ManagerId=m.Id WHERE e.Salary > m.Salary.$q$,ARRAY['mysql','postgresql'],0.75),
($q$HCL Delete Duplicate Emails$q$,$q$delete-duplicate-emails$q$,$q$Easy$q$,$q$SQL$q$,ARRAY['sql','delete','subquery'],$q$## Problem

HCL's user table `Person(Id, Email)` has duplicate emails. Delete all **duplicate emails**, keeping the row with smallest Id.$q$,$q$Table: Person(Id INT PRIMARY KEY, Email VARCHAR)$q$,$q$[{"input": "Person: [(1,'a@a.com'),(2,'b@b.com'),(3,'a@a.com')]", "output": "Keep: [(1,'a@a.com'),(2,'b@b.com')]"}]$q$::jsonb,$q$[{"input": "[(1,'a@a.com'),(2,'b@b.com'),(3,'a@a.com')]", "expected_output": "[(1,'a@a.com'),(2,'b@b.com')]", "is_hidden": false}, {"input": "[(1,'a@a.com'),(2,'a@a.com')]", "expected_output": "[(1,'a@a.com')]", "is_hidden": true}]$q$::jsonb,$q$DELETE FROM Person WHERE Id NOT IN (SELECT MIN(Id) FROM Person GROUP BY Email).$q$,ARRAY['mysql','postgresql'],0.69),
($q$Combine Customer Orders Tables$q$,$q$combine-two-tables$q$,$q$Easy$q$,$q$SQL$q$,ARRAY['sql','left-join'],$q$## Problem

Given `Person(PersonId, FirstName, LastName)` and `Address(AddressId, PersonId, City, State)`, report FirstName, LastName, City, State for each person. Include persons **without address** (NULL for missing).$q$,$q$PersonId in Person, Address references it$q$,$q$[{"input": "Person:[(1,'A','B')] Address:[]", "output": "[('A','B',null,null)]"}]$q$::jsonb,$q$[{"input": "Person:[(1,'Wang','Fang')] Address:[(1,1,'Nanjing','Jiangsu')]", "expected_output": "[('Wang','Fang','Nanjing','Jiangsu')]", "is_hidden": false}, {"input": "Person:[(1,'A','B')] Address:[]", "expected_output": "[('A','B',null,null)]", "is_hidden": true}]$q$::jsonb,$q$SELECT FirstName,LastName,City,State FROM Person LEFT JOIN Address ON Person.PersonId=Address.PersonId.$q$,ARRAY['mysql','postgresql'],0.82),
($q$Consecutive Numbers Logging$q$,$q$consecutive-numbers$q$,$q$Medium$q$,$q$SQL$q$,ARRAY['sql','window-functions','self-join'],$q$## Problem

Find all numbers in `Logs(Id, Num)` that appear **at least three times consecutively**.$q$,$q$Table: Logs(Id INT AUTO_INCREMENT, Num VARCHAR)$q$,$q$[{"input": "Logs:[(1,1),(2,1),(3,1),(4,2),(5,1),(6,2),(7,2)]", "output": "[1]", "explanation": "1 appears three times consecutively at rows 1,2,3"}]$q$::jsonb,$q$[{"input": "[(1,1),(2,1),(3,1),(4,2)]", "expected_output": "[1]", "is_hidden": false}, {"input": "[(1,1),(2,1),(3,2),(4,2),(5,2)]", "expected_output": "[2]", "is_hidden": true}]$q$::jsonb,$q$Self-join L1,L2,L3 where L1.Id+1=L2.Id, L2.Id+1=L3.Id and all nums equal. Or LAG/LEAD window functions.$q$,ARRAY['mysql','postgresql'],0.48),
($q$Department Highest Salary Finder$q$,$q$department-highest-salary$q$,$q$Medium$q$,$q$SQL$q$,ARRAY['sql','subquery','aggregation','join'],$q$## Problem

Given `Employee(Id,Name,Salary,DepartmentId)` and `Department(Id,Name)`, find the **employee(s) with highest salary** in each department.$q$,$q$At least one employee per department | Multiple employees may share highest salary$q$,$q$[{"input": "Employee:[(1,'Arjun',70000,1),(2,'Bob',80000,1),(3,'Priya',60000,2)] Department:[(1,'IT'),(2,'HR')]", "output": "[('IT','Bob',80000),('HR','Priya',60000)]"}]$q$::jsonb,$q$[{"input": "Emp:[(1,'A',70000,1),(2,'B',80000,1)] Dept:[(1,'IT')]", "expected_output": "[('IT','B',80000)]", "is_hidden": false}, {"input": "Emp:[(1,'A',70000,1),(2,'B',70000,1)] Dept:[(1,'IT')]", "expected_output": "[('IT','A',70000),('IT','B',70000)]", "is_hidden": true}]$q$::jsonb,$q$SELECT d.Name, e.Name, e.Salary FROM Employee e JOIN Department d ON e.DeptId=d.Id WHERE (e.DeptId,e.Salary) IN (SELECT DeptId,MAX(Salary) FROM Employee GROUP BY DeptId).$q$,ARRAY['mysql','postgresql'],0.53),
($q$Department Top Three Salaries$q$,$q$department-top-three-salaries$q$,$q$Hard$q$,$q$SQL$q$,ARRAY['sql','window-functions','dense-rank'],$q$## Problem

Find employees who earn in the **top three unique salaries** within their department.$q$,$q$Same tables as Department Highest Salary | Top 3 unique salary values$q$,$q$[{"input": "Employee:[(1,'A',100,1),(2,'B',90,1),(3,'C',80,1),(4,'D',70,1)] Department:[(1,'IT')]", "output": "[('IT','A',100),('IT','B',90),('IT','C',80)]"}]$q$::jsonb,$q$[{"input": "Emp:[(1,'A',100,1),(2,'B',90,1),(3,'C',80,1),(4,'D',70,1)] Dept:[(1,'IT')]", "expected_output": "[('IT','A',100),('IT','B',90),('IT','C',80)]", "is_hidden": false}, {"input": "Emp:[(1,'A',100,1),(2,'A',100,1),(3,'B',90,1)] Dept:[(1,'IT')]", "expected_output": "[('IT','A',100),('IT','A',100),('IT','B',90)]", "is_hidden": true}]$q$::jsonb,$q$DENSE_RANK() OVER (PARTITION BY DepartmentId ORDER BY Salary DESC) ≤ 3.$q$,ARRAY['mysql','postgresql'],0.35),
($q$Paytm Active Users Monthly$q$,$q$active-users$q$,$q$Medium$q$,$q$SQL$q$,ARRAY['sql','window-functions','date-functions'],$q$## Problem

Given `Logins(UserId, LoginDate)`, find users who logged in for **5 or more consecutive days**. Return user IDs (no duplicates).$q$,$q$Table: Logins(UserId INT, LoginDate DATE) | Dates are unique per user$q$,$q$[{"input": "Logins:[(1,'2021-01-01'),(1,'2021-01-02'),(1,'2021-01-03'),(1,'2021-01-04'),(1,'2021-01-05'),(2,'2021-01-01')]", "output": "[1]"}]$q$::jsonb,$q$[{"input": "[(1,'2021-01-01'),(1,'2021-01-02'),(1,'2021-01-03'),(1,'2021-01-04'),(1,'2021-01-05')]", "expected_output": "[1]", "is_hidden": false}, {"input": "[(1,'2021-01-01'),(1,'2021-01-03')]", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$Use ROW_NUMBER() partitioned by UserId ordered by LoginDate. LoginDate - ROW_NUMBER() = constant for consecutive days. Count groups ≥ 5.$q$,ARRAY['mysql','postgresql'],0.42),
($q$Nth Highest Salary Generic$q$,$q$nth-highest-salary$q$,$q$Medium$q$,$q$SQL$q$,ARRAY['sql','subquery','offset'],$q$## Problem

Create a SQL function `getNthHighestSalary(N INT)` that returns the **Nth highest salary** from `Employee` table. Return NULL if fewer than N distinct salaries.$q$,$q$Table: Employee(Id INT, Salary INT) | 1 ≤ N$q$,$q$[{"input": "Employee:[(1,300),(2,200),(3,100)], N=2", "output": "200"}, {"input": "Employee:[(1,100)], N=2", "output": "null"}]$q$::jsonb,$q$[{"input": "N=2\n[(1,300),(2,200),(3,100)]", "expected_output": "200", "is_hidden": false}, {"input": "N=2\n[(1,100)]", "expected_output": "null", "is_hidden": true}]$q$::jsonb,$q$SELECT DISTINCT Salary FROM Employee ORDER BY Salary DESC LIMIT 1 OFFSET N-1. Wrap in function with NULL check.$q$,ARRAY['mysql','postgresql'],0.55)
ON CONFLICT (slug) DO NOTHING;