-- STEP 10: Problems 161–180 of 201
INSERT INTO problems (title,slug,difficulty,category,tags,statement,constraints,examples,test_cases,editorial,languages,acceptance_rate)
VALUES
($q$Integer to Roman Numeral$q$,$q$integer-to-roman$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','math','greedy'],$q$## Problem

Convert an integer `num` to a **Roman numeral** string.$q$,$q$1 ≤ num ≤ 3999$q$,$q$[{"input": "num = 1994", "output": "\"MCMXCIV\""}, {"input": "num = 58", "output": "\"LVIII\""}]$q$::jsonb,$q$[{"input": "1994", "expected_output": "\"MCMXCIV\"", "is_hidden": false}, {"input": "3749", "expected_output": "\"MMMDCCXLIX\"", "is_hidden": true}]$q$::jsonb,$q$Table of values/symbols descending. Greedily subtract largest fitting value, append symbol. O(1) since bounded by 3999.$q$,ARRAY['python','java','javascript','go','cpp'],0.66),
($q$Count and Say Sequence$q$,$q$count-and-say$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','simulation'],$q$## Problem

The count-and-say sequence: 1→"1", 2→"11", 3→"21", 4→"1211", 5→"111221". Return the **nth term**.$q$,$q$1 ≤ n ≤ 30$q$,$q$[{"input": "n = 4", "output": "\"1211\""}, {"input": "n = 1", "output": "\"1\""}]$q$::jsonb,$q$[{"input": "4", "expected_output": "\"1211\"", "is_hidden": false}, {"input": "6", "expected_output": "\"312211\"", "is_hidden": true}]$q$::jsonb,$q$Start with "1". For each step, scan current string counting consecutive chars, build next. O(2^n).$q$,ARRAY['python','java','javascript','go','cpp'],0.59),
($q$Isomorphic Strings Check$q$,$q$isomorphic-strings$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['strings','hash-map'],$q$## Problem

Two strings `s` and `t` are isomorphic if characters in `s` can be replaced to get `t` (preserving order, one-to-one mapping). Return `true` if isomorphic.$q$,$q$1 ≤ len(s) = len(t) ≤ 5×10^4 | s and t consist of printable ASCII$q$,$q$[{"input": "s=\"egg\", t=\"add\"", "output": "true"}, {"input": "s=\"foo\", t=\"bar\"", "output": "false"}, {"input": "s=\"paper\", t=\"title\"", "output": "true"}]$q$::jsonb,$q$[{"input": "\"egg\"\n\"add\"", "expected_output": "true", "is_hidden": false}, {"input": "\"foo\"\n\"bar\"", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$Two hashmaps s→t and t→s. For each pair, check consistency of both mappings. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.69),
($q$String Compression Encoding$q$,$q$string-compression$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','two-pointers'],$q$## Problem

Compress string `chars` array in-place: consecutive repeats become char+count (e.g. ['a','a','b'] → ['a','2','b']). Single chars have no count. Return new length. O(1) extra space.$q$,$q$1 ≤ len(chars) ≤ 2000 | chars[i] is lowercase letter, digit, or symbol$q$,$q$[{"input": "chars = ['a','a','b','b','c','c','c']", "output": "6 (array becomes ['a','2','b','2','c','3'])"}, {"input": "chars = ['a']", "output": "1"}]$q$::jsonb,$q$[{"input": "['a','a','b','b','c','c','c']", "expected_output": "6", "is_hidden": false}, {"input": "['a','b','b','b','b','b','b','b','b','b','b','b','b']", "expected_output": "4", "is_hidden": true}]$q$::jsonb,$q$Two pointers: read and write. Count consecutive, write char then count digits. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.51),
($q$Ransom Note Magazine$q$,$q$ransom-note$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['strings','hash-map'],$q$## Problem

Given `ransomNote` and `magazine`, return `true` if `ransomNote` can be constructed using letters from `magazine` (each letter used at most once).$q$,$q$1 ≤ len(ransomNote),len(magazine) ≤ 10^5 | Both consist of lowercase letters$q$,$q$[{"input": "ransomNote=\"a\", magazine=\"b\"", "output": "false"}, {"input": "ransomNote=\"aa\", magazine=\"aab\"", "output": "true"}]$q$::jsonb,$q$[{"input": "\"a\"\n\"b\"", "expected_output": "false", "is_hidden": false}, {"input": "\"aa\"\n\"aab\"", "expected_output": "true", "is_hidden": true}]$q$::jsonb,$q$Count chars in magazine. For each char in ransomNote decrement; if goes < 0, return false. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.76),
($q$Implement strStr Substring Search$q$,$q$find-needle-in-haystack$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['strings','kmp','sliding-window'],$q$## Problem

Given `haystack` and `needle`, return the **index** of needle's first occurrence in haystack. Return -1 if not present.$q$,$q$1 ≤ len(haystack),len(needle) ≤ 10^4 | Both consist of lowercase letters$q$,$q$[{"input": "haystack=\"sadbutsad\", needle=\"sad\"", "output": "0"}, {"input": "haystack=\"leetcode\", needle=\"leeto\"", "output": "-1"}]$q$::jsonb,$q$[{"input": "\"sadbutsad\"\n\"sad\"", "expected_output": "0", "is_hidden": false}, {"input": "\"leetcode\"\n\"leeto\"", "expected_output": "-1", "is_hidden": true}]$q$::jsonb,$q$Built-in find() or KMP for O(n+m). Sliding window O(n×m) also accepted for this constraint.$q$,ARRAY['python','java','javascript','go','cpp'],0.72),
($q$Zigzag Conversion Rail Fence$q$,$q$zigzag-conversion$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['strings','simulation'],$q$## Problem

Write `s` in zigzag pattern on `numRows` rows (like a fence), then read row by row. Return the result string.$q$,$q$1 ≤ len(s) ≤ 1000 | 1 ≤ numRows ≤ 1000$q$,$q$[{"input": "s=\"PAYPALISHIRING\", numRows=3", "output": "\"PAHNAPLSIIGYIR\""}, {"input": "s=\"PAYPALISHIRING\", numRows=4", "output": "\"PINALSIGYAHRPI\""}]$q$::jsonb,$q$[{"input": "\"PAYPALISHIRING\"\n3", "expected_output": "\"PAHNAPLSIIGYIR\"", "is_hidden": false}, {"input": "\"A\"\n1", "expected_output": "\"A\"", "is_hidden": true}]$q$::jsonb,$q$Simulate: row idx oscillates 0..numRows-1 and back. Append char to corresponding row string. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.55),
($q$Construct Tree from Preorder Inorder$q$,$q$construct-binary-tree-preorder-inorder$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','dfs','divide-conquer'],$q$## Problem

Given `preorder` and `inorder` traversal arrays of a binary tree, construct and return the **binary tree**.$q$,$q$1 ≤ n ≤ 3000 | -3000 ≤ val ≤ 3000 | All values are unique | preorder and inorder are valid for the same tree$q$,$q$[{"input": "preorder=[3,9,20,15,7], inorder=[9,3,15,20,7]", "output": "[3,9,20,null,null,15,7]"}]$q$::jsonb,$q$[{"input": "[3,9,20,15,7]\n[9,3,15,20,7]", "expected_output": "[3,9,20,null,null,15,7]", "is_hidden": false}, {"input": "[-1]\n[-1]", "expected_output": "[-1]", "is_hidden": true}]$q$::jsonb,$q$preorder[0]=root. Find root in inorder → splits left/right subtrees. Recurse. Hashmap for O(1) lookup. O(n).$q$,ARRAY['python','java','javascript','go','cpp'],0.6),
($q$Populating Next Right Pointers$q$,$q$populating-next-right-pointers$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','bfs'],$q$## Problem

Fill each node's `next` pointer to point to the **next right node** on the same level. If no next right, set to NULL. Use O(1) extra space (no queue).$q$,$q$1 ≤ n ≤ 6000 | -100 ≤ val ≤ 100 | Perfect binary tree$q$,$q$[{"input": "root = [1,2,3,4,5,6,7]", "output": "[1,#,2,3,#,4,5,6,7,#]"}]$q$::jsonb,$q$[{"input": "[1,2,3,4,5,6,7]", "expected_output": "[1,#,2,3,#,4,5,6,7,#]", "is_hidden": false}, {"input": "[]", "expected_output": "[]", "is_hidden": true}]$q$::jsonb,$q$Iterate levels using existing next pointers. Connect children level by level. O(n) O(1).$q$,ARRAY['python','java','javascript','go','cpp'],0.67),
($q$Count Complete Tree Nodes$q$,$q$count-complete-tree-nodes$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['trees','binary-search'],$q$## Problem

Given a **complete binary tree**, count nodes in less than O(n). A complete tree has all levels full except possibly the last, which is filled from left.$q$,$q$0 ≤ n < 5×10^4 | 0 ≤ val ≤ 5×10^4$q$,$q$[{"input": "root = [1,2,3,4,5,6]", "output": "6"}]$q$::jsonb,$q$[{"input": "[1,2,3,4,5,6]", "expected_output": "6", "is_hidden": false}, {"input": "[]", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$Compute left height and right height. If equal → left subtree is perfect (2^h-1 nodes). Binary search last node position. O(log²n).$q$,ARRAY['python','java','javascript','go','cpp'],0.64),
($q$Critical Connections Network Bridge$q$,$q$critical-connections-in-network$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['graphs','dfs','tarjan'],$q$## Problem

Given `n` servers connected by `connections` (undirected), find all **critical connections** — edges whose removal disconnects the network.$q$,$q$2 ≤ n ≤ 10^5 | n-1 ≤ connections.length ≤ 10^5$q$,$q$[{"input": "n=4, connections=[[0,1],[1,2],[2,0],[1,3]]", "output": "[[1,3]]", "explanation": "Removing [1,3] disconnects server 3"}]$q$::jsonb,$q$[{"input": "4\n[[0,1],[1,2],[2,0],[1,3]]", "expected_output": "[[1,3]]", "is_hidden": false}, {"input": "2\n[[0,1]]", "expected_output": "[[0,1]]", "is_hidden": true}]$q$::jsonb,$q$Tarjan's bridge algorithm. Track discovery time and low value. Edge (u,v) is bridge if low[v] > disc[u]. O(V+E).$q$,ARRAY['python','java','javascript','go','cpp'],0.29),
($q$Minimum Spanning Tree Roads$q$,$q$minimum-spanning-tree$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['graphs','kruskal','union-find','prim'],$q$## Problem

Given `n` cities and `edges[i]=[u,v,cost]`, find the **minimum cost** to connect all cities (Minimum Spanning Tree). Return total cost. Return -1 if impossible.$q$,$q$1 ≤ n ≤ 1000 | 1 ≤ edges.length ≤ 10^4 | 1 ≤ cost ≤ 10^4$q$,$q$[{"input": "n=4, edges=[[0,1,1],[0,2,4],[1,2,2],[1,3,5],[2,3,1]]", "output": "4", "explanation": "Edges (0,1,1)+(1,2,2)+(2,3,1)=4"}]$q$::jsonb,$q$[{"input": "4\n[[0,1,1],[0,2,4],[1,2,2],[1,3,5],[2,3,1]]", "expected_output": "4", "is_hidden": false}, {"input": "2\n[[0,1,5]]", "expected_output": "5", "is_hidden": true}]$q$::jsonb,$q$Kruskal's: sort edges, add if no cycle (Union-Find). Or Prim's with min-heap. O(E log E).$q$,ARRAY['python','java','javascript','go','cpp'],0.58),
($q$Redundant Connection Cycle Finder$q$,$q$redundant-connection$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['graphs','union-find','dfs'],$q$## Problem

Given a tree with `n` nodes and one extra edge (making it have a cycle), find the **redundant edge** that can be removed to restore a valid tree. If multiple answers, return the last one in input.$q$,$q$3 ≤ n ≤ 1000 | edges[i] = [u,v], 1-indexed$q$,$q$[{"input": "edges = [[1,2],[1,3],[2,3]]", "output": "[2,3]"}, {"input": "edges = [[1,2],[2,3],[3,4],[1,4],[1,5]]", "output": "[1,4]"}]$q$::jsonb,$q$[{"input": "[[1,2],[1,3],[2,3]]", "expected_output": "[2,3]", "is_hidden": false}, {"input": "[[1,2],[2,3],[3,4],[1,4],[1,5]]", "expected_output": "[1,4]", "is_hidden": true}]$q$::jsonb,$q$Union-Find: for each edge, if both endpoints already connected → redundant. O(n×α(n)).$q$,ARRAY['python','java','javascript','go','cpp'],0.64),
($q$Find the Town Judge$q$,$q$find-the-town-judge$q$,$q$Easy$q$,$q$DSA$q$,ARRAY['graphs','arrays'],$q$## Problem

In a village of `n` people, the town judge trusts nobody and everybody (except the judge) trusts the judge. Given `trust[i]=[a,b]` (a trusts b), find the **judge's label**. Return -1 if none.$q$,$q$1 ≤ n ≤ 1000 | 0 ≤ trust.length ≤ 10^4 | trust[i] are distinct$q$,$q$[{"input": "n=3, trust=[[1,3],[2,3]]", "output": "3"}, {"input": "n=3, trust=[[1,3],[2,3],[3,1]]", "output": "-1"}]$q$::jsonb,$q$[{"input": "3\n[[1,3],[2,3]]", "expected_output": "3", "is_hidden": false}, {"input": "3\n[[1,3],[2,3],[3,1]]", "expected_output": "-1", "is_hidden": true}]$q$::jsonb,$q$Count trust-in and trust-out per person. Judge has trust-in=n-1 and trust-out=0. O(n+E).$q$,ARRAY['python','java','javascript','go','cpp'],0.74),
($q$Coin Change II Count Ways$q$,$q$coin-change-ii$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming'],$q$## Problem

Given coin `denominations` and `amount`, return the **number of combinations** (not permutations) that make up the amount. Infinite coins.$q$,$q$1 ≤ coins.length ≤ 300 | 1 ≤ coins[i] ≤ 5000 | 0 ≤ amount ≤ 5000$q$,$q$[{"input": "coins=[1,2,5], amount=5", "output": "4", "explanation": "5;2+2+1;2+1+1+1;1×5"}, {"input": "coins=[2], amount=3", "output": "0"}]$q$::jsonb,$q$[{"input": "[1,2,5]\n5", "expected_output": "4", "is_hidden": false}, {"input": "[2]\n3", "expected_output": "0", "is_hidden": true}]$q$::jsonb,$q$dp[i]+=dp[i-coin] for each coin. Outer loop over coins (not amount) to avoid permutations. O(amount×coins).$q$,ARRAY['python','java','javascript','go','cpp'],0.61),
($q$Interleaving String Verification$q$,$q$interleaving-string$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['dynamic-programming','strings'],$q$## Problem

Given `s1`, `s2`, `s3`, determine if `s3` is formed by an **interleaving** of `s1` and `s2` (preserving relative order).$q$,$q$0 ≤ len(s1),len(s2) ≤ 100 | len(s3) = len(s1)+len(s2) | All consist of lowercase letters$q$,$q$[{"input": "s1=\"aabcc\", s2=\"dbbca\", s3=\"aadbbcbcac\"", "output": "true"}, {"input": "s1=\"aabcc\", s2=\"dbbca\", s3=\"aadbbbaccc\"", "output": "false"}]$q$::jsonb,$q$[{"input": "\"aabcc\"\n\"dbbca\"\n\"aadbbcbcac\"", "expected_output": "true", "is_hidden": false}, {"input": "\"aabcc\"\n\"dbbca\"\n\"aadbbbaccc\"", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$dp[i][j]=can form s3[0..i+j-1] using s1[0..i-1] and s2[0..j-1]. Transitions from dp[i-1][j] and dp[i][j-1]. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.44),
($q$Burst Balloons Maximum Coins$q$,$q$burst-balloons$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['dynamic-programming','divide-conquer'],$q$## Problem

Burst all balloons with values `nums`. Bursting balloon `i` gives `nums[i-1]*nums[i]*nums[i+1]` coins. Maximize total coins. Add 1 padding at both ends.$q$,$q$1 ≤ n ≤ 300 | 0 ≤ nums[i] ≤ 100$q$,$q$[{"input": "nums = [3,1,5,8]", "output": "167", "explanation": "Burst 1(3×1×5), burst 5(3×5×8), burst 3(1×3×8), burst 8(1×8×1) = 15+120+24+8=167"}]$q$::jsonb,$q$[{"input": "[3,1,5,8]", "expected_output": "167", "is_hidden": false}, {"input": "[1,5]", "expected_output": "10", "is_hidden": true}]$q$::jsonb,$q$Interval DP: think of last balloon to burst in range [l,r]. dp[l][r]=max over k of nums[l-1]*nums[k]*nums[r+1]+dp[l][k-1]+dp[k+1][r]. O(n³).$q$,ARRAY['python','java','javascript','go','cpp'],0.28),
($q$Wildcard Pattern Matching$q$,$q$wildcard-matching$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['dynamic-programming','strings','recursion'],$q$## Problem

Match string `s` against pattern `p` where `?` matches any single char and `*` matches any sequence (including empty). Return `true` if full match.$q$,$q$0 ≤ len(s) ≤ 2000 | 0 ≤ len(p) ≤ 2000 | s contains only lowercase letters | p contains lowercase letters, '?', '*'$q$,$q$[{"input": "s=\"aa\", p=\"a\"", "output": "false"}, {"input": "s=\"aa\", p=\"*\"", "output": "true"}, {"input": "s=\"cb\", p=\"?a\"", "output": "false"}]$q$::jsonb,$q$[{"input": "\"aa\"\n\"*\"", "expected_output": "true", "is_hidden": false}, {"input": "\"cb\"\n\"?a\"", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$dp[i][j]=s[0..i-1] matches p[0..j-1]. If p[j-1]='*': dp[i-1][j] or dp[i][j-1]. If '?' or match: dp[i-1][j-1]. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.3),
($q$Regular Expression Matching$q$,$q$regular-expression-matching$q$,$q$Hard$q$,$q$DSA$q$,ARRAY['dynamic-programming','strings','recursion'],$q$## Problem

Match `s` against pattern `p` where `.` matches any single char and `*` matches zero or more of the preceding element. Full string match required.$q$,$q$1 ≤ len(s) ≤ 20 | 1 ≤ len(p) ≤ 30 | s contains only lowercase letters | p contains lowercase letters, '.', '*'$q$,$q$[{"input": "s=\"aa\", p=\"a*\"", "output": "true"}, {"input": "s=\"ab\", p=\".*\"", "output": "true"}, {"input": "s=\"aab\", p=\"c*a*b\"", "output": "true"}]$q$::jsonb,$q$[{"input": "\"aa\"\n\"a*\"", "expected_output": "true", "is_hidden": false}, {"input": "\"mississippi\"\n\"mis*is*p*.\"", "expected_output": "false", "is_hidden": true}]$q$::jsonb,$q$dp[i][j]=s[0..i-1] matches p[0..j-1]. Handle '*' by checking zero occurrence dp[i][j-2] or one more dp[i-1][j]. O(m×n).$q$,ARRAY['python','java','javascript','go','cpp'],0.26),
($q$Minimum Cost Connect Sticks$q$,$q$minimum-cost-to-connect-sticks$q$,$q$Medium$q$,$q$DSA$q$,ARRAY['heap','greedy'],$q$## Problem

Connect `n` sticks into one stick. Cost of connecting two sticks = sum of their lengths. Return **minimum total cost**.$q$,$q$1 ≤ sticks.length ≤ 10^4 | 1 ≤ sticks[i] ≤ 10^4$q$,$q$[{"input": "sticks = [2,4,3]", "output": "14", "explanation": "Connect 2+3=5(cost 5), then 4+5=9(cost 9): total 14"}, {"input": "sticks = [1,8,3,5]", "output": "30"}]$q$::jsonb,$q$[{"input": "[2,4,3]", "expected_output": "14", "is_hidden": false}, {"input": "[1,8,3,5]", "expected_output": "30", "is_hidden": true}]$q$::jsonb,$q$Huffman coding: always merge two smallest. Min-heap: pop two, push sum, add to total. O(n log n).$q$,ARRAY['python','java','javascript','go','cpp'],0.62)
ON CONFLICT (slug) DO NOTHING;