#!/usr/bin/env node
/**
 * generateQuestionBankDrafts.mjs — Career OS Workstream 3 content-ops
 * deliverable: generates 300 scenario-based question DRAFTS (30 per domain
 * x 10 domains), balanced difficulty, no trick questions, 4 plausible
 * options, one correct answer, a concise explanation, skill tags, and
 * source='ai_generated' — written to a JSON file matching the import
 * template shape (docs/question-bank-import-template.json), ready to run
 * through scripts/importQuestionBank.mjs for dry-run validation and
 * (separately, deliberately not from this script) a --commit insert.
 *
 * These are DRAFTS for a human reviewer. Nothing here is auto-approved —
 * this script never sets review_status and never calls the DB; it only
 * writes a JSON file. review_status='draft' is applied by
 * questionImport.js's toQuestionBankRow() at actual import time, same as
 * any other imported file.
 *
 * Design: each domain gets 3 representative skills and 10 distinct
 * "scenario frames" (a real, plausible work situation + one correct
 * behavior + three plausible-but-wrong behaviors). Each frame is
 * instantiated once per skill (10 frames x 3 skills = 30/domain),
 * substituting the skill name and domain-appropriate specifics into the
 * frame so the 3 instances of a frame are genuinely different questions,
 * not copy-paste. Difficulty cycles 1-5 across the 10 frames (2 at each
 * level) so every skill's 10 questions are already difficulty-balanced,
 * and the domain total (30) ends up with exactly 6 questions at each of
 * the 5 difficulty levels.
 */
import { writeFileSync } from "node:fs"

const QUESTION_TYPES = ["scenario", "bug_finding", "reasoning", "dashboard_interpretation", "architecture_interpretation", "operational_decision", "work_situation"]

// domain -> { skills: [3 real skill names], frames: [10 {type, difficulty, build(skill) -> {prompt, options, correctIdx, explanation}}] }
const DOMAINS = {
  software_engineering: {
    skills: ["Code Review", "API Design", "Debugging"],
    frames: [
      (skill) => ({ type: "bug_finding", difficulty: 1, prompt: `You're pairing on ${skill} and a teammate says "it works on my machine" about a failing test in CI. What's the most useful next step?`, options: ["Compare the CI environment's dependency versions against local", "Mark the test as skipped so the build passes", "Re-run CI hoping it passes this time", "Delete the test file"], correctIdx: 0, explanation: "Environment drift (dependency versions, OS, timezone) is the single most common cause of local-vs-CI mismatches — check that before touching the test itself." }),
      (skill) => ({ type: "scenario", difficulty: 2, prompt: `During a ${skill} session, you notice a function has grown to 300 lines and touches five unrelated concerns. What's the most constructive comment to leave?`, options: ["Suggest splitting it into smaller, single-purpose functions with a brief rationale", "Approve it since it technically works", "Ask them to add more comments explaining each section", "Request they rewrite it in a different language"], correctIdx: 0, explanation: "Long, multi-concern functions are a maintainability risk regardless of whether they currently work — the constructive fix is decomposition, not more comments padding over the structure problem." }),
      (skill) => ({ type: "operational_decision", difficulty: 3, prompt: `Your team is deciding on ${skill} standards. One engineer wants to block all merges without 100% test coverage. What's the more balanced position?`, options: ["Require coverage on new/changed code and critical paths, not a blanket 100%", "Agree to 100% coverage everywhere immediately", "Remove coverage requirements entirely", "Only require coverage on Fridays before releases"], correctIdx: 0, explanation: "Blanket 100% coverage mandates often produce brittle tests written just to hit the number; targeting new code and critical paths gets the real safety benefit without that perverse incentive." }),
      (skill) => ({ type: "architecture_interpretation", difficulty: 3, prompt: `You're reviewing a design doc where ${skill} decisions are made without listing any trade-offs or alternatives considered. What should you ask for?`, options: ["The alternatives that were considered and why they were rejected", "Nothing — the doc author is senior, trust it", "A longer document with more diagrams", "A vote from the whole company"], correctIdx: 0, explanation: "A design decision without visible alternatives is unreviewable — you can't evaluate a choice without knowing what it was chosen over and why." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `A ${skill} discussion turns into disagreement about naming conventions with no clear stakes either way. What's the pragmatic move?`, options: ["Defer to the existing project convention and move on", "Escalate to a company-wide policy meeting", "Block the PR until everyone agrees", "Rewrite the whole codebase to the reviewer's preferred style"], correctIdx: 0, explanation: "Low-stakes stylistic disagreements are exactly what existing conventions are for — consistency with what's already there beats re-litigating preference." }),
      (skill) => ({ type: "bug_finding", difficulty: 4, prompt: `While doing ${skill}, you spot that a retry loop has no backoff and no max-attempts limit. What's the risk, and the fix?`, options: ["It can hammer a struggling downstream service into a full outage — add exponential backoff and a cap", "No risk, retries are always safe", "It will only ever slow down the current request", "It's fine as long as the network is fast"], correctIdx: 0, explanation: "Unbounded, immediate retries are a classic way client code turns a downstream service's brief hiccup into a full outage (a retry storm) — backoff and a cap are the standard mitigation." }),
      (skill) => ({ type: "scenario", difficulty: 4, prompt: `A ${skill} change looks correct but silently swallows exceptions in a catch block with an empty body. Why does this matter even if nothing crashes?`, options: ["It hides real failures, making future debugging much harder and masking data corruption", "It doesn't matter, silence means success", "It makes the code run faster", "It's a valid pattern for production code"], correctIdx: 0, explanation: "An empty catch block doesn't prevent failure — it just prevents anyone from finding out about it, which is worse: the system keeps running in a broken state." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 3, prompt: `A ${skill}-related monitoring dashboard shows p50 latency is fine but p99 latency has tripled. What does this pattern usually indicate?`, options: ["A subset of requests are hitting a slow path (e.g. cache misses, a specific query) — most traffic is unaffected", "The whole system is uniformly slower", "The dashboard is broken", "p99 doesn't matter if p50 is fine"], correctIdx: 0, explanation: "A rising p99 with a stable p50 is the signature of a tail-latency problem affecting a minority of requests, not a system-wide slowdown — investigate what's different about the slow subset." }),
      (skill) => ({ type: "operational_decision", difficulty: 5, prompt: `Leadership wants to skip ${skill} entirely for a release to hit a deadline. As the tech lead, what's the responsible response?`, options: ["Quantify the specific risk this introduces and propose a scoped exception with monitoring, not a blanket skip", "Refuse to ship at all", "Agree silently and hope nothing breaks", "Skip it without telling anyone"], correctIdx: 0, explanation: "Refusing outright or silently complying are both worse than giving leadership the actual risk trade-off so they can make an informed, accountable call — that's what the role is for." }),
      (skill) => ({ type: "work_situation", difficulty: 5, prompt: `Two senior engineers disagree sharply on a ${skill} approach and it's stalling the team. What's the most effective way to unblock this?`, options: ["Timebox a spike to gather real data (benchmarks, prototypes) that the disagreement can be resolved against", "Let the more senior person always win", "Avoid the topic indefinitely", "Have a public vote among the whole engineering org"], correctIdx: 0, explanation: "Opinion-based stalemates are best resolved with data, not seniority or popularity — a small timeboxed spike turns a subjective argument into an objective comparison." }),
    ],
  },
  data_analytics: {
    skills: ["SQL", "Data Visualization", "Statistical Analysis"],
    frames: [
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `Using ${skill}, you find a report has 15% duplicate rows. What's the first thing to check?`, options: ["Whether a join condition is producing a fan-out (one-to-many match)", "Assume the source system is wrong and stop", "Manually delete random rows until it looks right", "Ignore it since 15% seems small"], correctIdx: 0, explanation: "Duplicate rows after a join are most often caused by a join key that isn't actually unique on one side, producing a fan-out — check the join logic before touching the data." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 2, prompt: `A ${skill} chart shows a metric spiking every Monday at 9am sharply, then dropping. What should you consider first?`, options: ["A scheduled job or batch process running at that time, not a real usage spike", "Users only work on Mondays", "The chart library has a bug", "It's always a security incident"], correctIdx: 0, explanation: "A perfectly regular, sharply-timed spike is the signature of an automated/scheduled process, not organic user behavior — check for a cron job or batch load first." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `Someone asks you to use ${skill} to prove a new feature "caused" a metric increase, with no experiment or control group. What's the honest response?`, options: ["Explain that correlation without a controlled comparison can't establish causation, and propose an A/B test or before/after with a control", "Just show the correlated chart since it's what they asked for", "Refuse to help at all", "Make up a causal claim to keep them happy"], correctIdx: 0, explanation: "Without a control group or experiment design, you can show correlation at best — an honest analyst says so and proposes how to actually test causation." }),
      (skill) => ({ type: "scenario", difficulty: 3, prompt: `Your ${skill} query runs fine on 10k rows in staging but times out on 50M rows in production. What's the most likely first culprit?`, options: ["A missing index on a column used in a WHERE/JOIN clause", "The production database is simply slower hardware", "The query syntax is invalid", "50M rows is always too many for any query"], correctIdx: 0, explanation: "A query that scales badly with row count, rather than failing outright, points at a missing index causing a full table scan rather than an indexed lookup — check execution plan/indexes first." }),
      (skill) => ({ type: "bug_finding", difficulty: 3, prompt: `A ${skill} report excludes a whole customer segment silently because of a WHERE clause that filters NULLs implicitly. How would you catch this?`, options: ["Compare total row counts before and after each filter step against the source table", "Trust the report since it ran without an error", "Assume the segment simply doesn't exist", "Re-run the same query again"], correctIdx: 0, explanation: "Silent data loss from implicit NULL handling doesn't throw an error — the only reliable catch is auditing row counts at each transformation step against the source." }),
      (skill) => ({ type: "reasoning", difficulty: 4, prompt: `Using ${skill}, you find a strong correlation between ice cream sales and drowning incidents. What's the correct interpretation?`, options: ["Both are driven by a third variable (hot weather), not one causing the other", "Ice cream causes drowning", "Drowning causes ice cream sales", "The data must be fake"], correctIdx: 0, explanation: "This is the classic confounding-variable example: a third factor (temperature) drives both, and treating the correlation as causal would be a real analytical error." }),
      (skill) => ({ type: "operational_decision", difficulty: 4, prompt: `A stakeholder wants a ${skill}-based dashboard updated in real time, but the underlying data only refreshes nightly. What's the right move?`, options: ["Explain the actual refresh cadence and label the dashboard accordingly, rather than implying false real-time-ness", "Build a fake real-time-looking refresh animation anyway", "Refuse to build the dashboard at all", "Silently ship it and hope nobody asks"], correctIdx: 0, explanation: "Implying real-time freshness when the underlying data is a day old will eventually mislead a decision — the responsible move is transparent labeling of actual data recency." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 5, prompt: `A ${skill} analysis of A/B test results shows a 2% lift with a p-value of 0.09. Leadership wants to ship it as a clear win. What's the accurate framing?`, options: ["The result is not statistically significant at the conventional 0.05 threshold — frame it as inconclusive, not a proven win", "0.09 is basically the same as 0.05, ship it as a win", "P-values don't matter if the number went up", "Rerun the test until it's significant"], correctIdx: 0, explanation: "A p-value above the conventional 0.05 threshold means the result could plausibly be noise — calling it a clear win overstates the evidence, and re-running until significance is a well-known statistical malpractice (p-hacking)." }),
      (skill) => ({ type: "scenario", difficulty: 5, prompt: `You're asked to use ${skill} to segment users, but 30% of records have missing demographic fields. What's the most defensible approach?`, options: ["Explicitly report the missing-data rate and analyze whether it's missing at random before drawing segment conclusions", "Drop all rows with any missing field silently", "Fill missing fields with a guessed average and treat it as real", "Ignore the missing data problem entirely"], correctIdx: 0, explanation: "Missing data that isn't random (e.g. a signup step some users skip) can bias segment conclusions — the defensible move is to surface and investigate the missingness pattern, not silently drop or fabricate it." }),
      (skill) => ({ type: "work_situation", difficulty: 1, prompt: `A colleague asks you to explain a ${skill} result in a way a non-technical exec can act on. What should the summary lead with?`, options: ["The business implication and recommended action, with supporting numbers after", "Every technical detail of the methodology first", "Just the raw numbers with no context", "A list of caveats with no conclusion at all"], correctIdx: 0, explanation: "A non-technical audience needs the 'so what' up front — leading with methodology or an unresolved list of caveats buries the actionable insight they actually need." }),
    ],
  },
  product_management: {
    skills: ["Prioritization", "User Research", "Roadmapping"],
    frames: [
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `During ${skill}, an engineer says a requested feature will take "about 2 weeks" with no further detail. What should you ask next?`, options: ["What assumptions that estimate depends on, and what could make it longer", "Nothing, just plan around 2 weeks exactly", "Ask for a 1-week estimate instead", "Assume it will actually take 4 weeks"], correctIdx: 0, explanation: "A bare estimate without stated assumptions is fragile — surfacing the assumptions (scope, dependencies, unknowns) is what actually makes an estimate useful for planning." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `In a ${skill} exercise, the loudest stakeholder in the room insists their pet feature is the top priority with no supporting data. How do you handle it?`, options: ["Ask what evidence or customer signal supports that priority, and weigh it against other requests using the same criteria", "Automatically prioritize it since they're loud/senior", "Dismiss it outright without discussion", "Add it to the roadmap without evaluating it"], correctIdx: 0, explanation: "Volume or seniority isn't evidence — applying the same evaluation criteria to every request, including asking for supporting data, keeps prioritization defensible." }),
      (skill) => ({ type: "operational_decision", difficulty: 3, prompt: `Your ${skill} process ranks every request by potential revenue impact only. What's the risk of that single-criterion approach?`, options: ["It can systematically ignore retention risks, tech debt, and small-but-critical fixes that don't show up as new revenue", "There is no risk, revenue is all that matters", "It makes prioritization faster, which is the only goal", "It guarantees the best long-term outcome"], correctIdx: 0, explanation: "A single-metric prioritization model has blind spots by construction — things that matter (churn prevention, technical health) but don't show up as direct new revenue get systematically deprioritized." }),
      (skill) => ({ type: "scenario", difficulty: 2, prompt: `During ${skill}, five customers ask for the same feature in one week. What should you check before assuming it's a top priority?`, options: ["Whether those five represent a broader pattern across the customer base or a small vocal segment", "Immediately promise it will ship next sprint", "Ignore it since it's only five people", "Build it exactly as each of the five described it"], correctIdx: 0, explanation: "A handful of vocal requests can be a real signal or a loud minority — checking whether it generalizes across the broader base is what separates anecdote from actual prioritization evidence." }),
      (skill) => ({ type: "reasoning", difficulty: 3, prompt: `In ${skill} interviews, a user says "I would definitely use this" about a hypothetical feature. How should you weigh that statement?`, options: ["Treat stated future intent with caution — look for evidence of actual past behavior instead", "Take it as a guarantee they will use it", "Ignore everything users say in interviews", "Build the feature immediately based on this one quote"], correctIdx: 0, explanation: "Stated hypothetical intent is one of the weakest signals in user research — what people say they'd do and what they actually do often diverge; past behavior is a much stronger predictor." }),
      (skill) => ({ type: "operational_decision", difficulty: 4, prompt: `Your ${skill} shows a major initiative slipping by a full quarter. What's the most useful update to give stakeholders?`, options: ["The specific reason for the slip, the new timeline, and what's being done differently to protect it", "Just say 'it's delayed' with no further detail", "Hide the slip until it's unavoidable to disclose", "Blame a specific team member publicly"], correctIdx: 0, explanation: "A vague or hidden delay erodes trust faster than an honest one — stakeholders need the reason, the new plan, and the safeguard, not just the bad news alone." }),
      (skill) => ({ type: "scenario", difficulty: 4, prompt: `A ${skill} session reveals two customer segments want opposite things from the same feature. What's the productive next step?`, options: ["Investigate whether this is really one feature or two distinct needs that got merged under the same request", "Pick whichever segment is bigger and ignore the other entirely", "Build a compromise that satisfies neither segment well", "Delay indefinitely until the conflict resolves itself"], correctIdx: 0, explanation: "Opposite needs under one feature name is often a sign the request has been oversimplified into a single ask when it's actually two separate underlying needs — unbundling it is usually more productive than forcing a single compromise." }),
      (skill) => ({ type: "work_situation", difficulty: 3, prompt: `Engineering pushes back that your ${skill} timeline is unrealistic. What's the constructive response?`, options: ["Ask them to walk through where the estimate breaks down and jointly rescope or resequence", "Insist on the original date regardless", "Immediately cut the timeline in half to compensate", "Escalate to their manager without discussing it with them first"], correctIdx: 0, explanation: "Pushback on a timeline is useful information, not an obstacle — understanding specifically where it breaks down lets you rescope or resequence instead of just overriding the concern." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 5, prompt: `A metric tied to your ${skill} decision improved, but a related metric got worse in the same period. What should the roadmap review focus on?`, options: ["Whether the improvement actually came at the expense of the other metric (a trade-off) or if they're unrelated", "Only celebrate the metric that improved", "Assume the two metrics are always unrelated", "Reverse the decision immediately without investigating"], correctIdx: 0, explanation: "When two metrics move in opposite directions after one change, the first question is whether there's a real trade-off relationship — celebrating one number while ignoring the other risks missing a net-negative outcome." }),
      (skill) => ({ type: "reasoning", difficulty: 5, prompt: `Leadership wants your ${skill} roadmap to commit to exact ship dates 12 months out. What's the honest position to take?`, options: ["Offer a directional roadmap with confidence levels that decrease further out, rather than false-precision fixed dates", "Commit to exact dates to seem confident", "Refuse to provide any roadmap at all", "Provide dates but plan to just ignore them later"], correctIdx: 0, explanation: "Fixed exact dates 12 months out are false precision for almost any real roadmap — an honest roadmap communicates confidence that naturally decreases further into the future instead of manufacturing certainty that doesn't exist." }),
    ],
  },
  design_ux: {
    skills: ["Usability Testing", "Wireframing", "Visual Design"],
    frames: [
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `During ${skill}, a test participant struggles to find a button that's technically visible on screen. What should you conclude?`, options: ["The button likely lacks sufficient visual prominence or is in an unexpected location for this task", "The participant is simply not tech-savvy", "The test is invalid and should be discarded", "Nothing — one user's struggle doesn't matter"], correctIdx: 0, explanation: "If a real user can't find something that's technically present, the design has a discoverability problem — dismissing it as a user issue misses the actual usability signal." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `In ${skill}, a stakeholder says "I don't like this color" as the entire critique of a proposal. How do you respond productively?`, options: ["Ask what specifically about the color isn't working for them relative to the design goals (contrast, brand, mood)", "Change the color immediately with no discussion", "Defend the color without asking anything", "Ignore the feedback since it's just an opinion"], correctIdx: 0, explanation: "Vague aesthetic feedback becomes actionable once you unpack what concern is behind it — contrast, brand alignment, and emotional tone are all different problems with different fixes." }),
      (skill) => ({ type: "scenario", difficulty: 2, prompt: `A ${skill} review shows a form has 12 required fields for a simple signup. What's the likely usability impact?`, options: ["Higher abandonment — each additional required field tends to reduce completion rate", "No impact, more fields always feel more trustworthy", "It will improve conversion by seeming thorough", "Users don't notice form length at all"], correctIdx: 0, explanation: "Form length and required-field count are well-established abandonment drivers — a 12-field signup form for a simple action is a strong candidate for simplification." }),
      (skill) => ({ type: "operational_decision", difficulty: 3, prompt: `Your ${skill} plan only tests with five internal employees, not real target users. What's the concern?`, options: ["Internal employees are too familiar with the product to represent a first-time or target user's actual struggles", "Five is too few people no matter who they are", "Employee feedback is always wrong", "There's no concern, employees are users too"], correctIdx: 0, explanation: "The core issue isn't sample size alone — it's that internal familiarity with the product masks the very confusion a fresh, representative user would hit." }),
      (skill) => ({ type: "scenario", difficulty: 3, prompt: `During ${skill}, you find the primary CTA and a destructive "delete" action have nearly identical visual styling. What's the risk?`, options: ["Users may accidentally trigger the destructive action, mistaking it for the primary one", "No risk, users always read labels carefully", "It will look more visually consistent, which is good", "This only matters for accessibility, not usability"], correctIdx: 0, explanation: "Visually similar styling for a primary action and a destructive one is a classic setup for costly accidental clicks — visual weight should map to consequence, not just consistency." }),
      (skill) => ({ type: "reasoning", difficulty: 4, prompt: `A ${skill} test shows users complete a task faster with a new design, but self-reported satisfaction dropped. How should you interpret this?`, options: ["Investigate both signals — speed and satisfaction can diverge, and a faster-but-more-stressful flow isn't a clean win", "Only trust the speed metric since it's objective", "Only trust the satisfaction score and ignore speed", "Assume the test itself is broken"], correctIdx: 0, explanation: "Task time and satisfaction measure different things — a design that's faster but feels more stressful or confusing isn't simply better; both signals need investigating together." }),
      (skill) => ({ type: "work_situation", difficulty: 4, prompt: `Engineering says implementing your ${skill} deliverable exactly as specified isn't technically feasible on this timeline. What's the productive path?`, options: ["Discuss which specific constraints are driving the limitation and co-design a feasible alternative preserving the core goal", "Insist on the exact spec regardless of feasibility", "Drop the feature entirely without discussion", "Let engineering redesign it without your input"], correctIdx: 0, explanation: "Understanding the actual technical constraint lets you preserve the underlying user goal through a different, feasible approach — insisting or disengaging both produce worse outcomes than collaborating on the real constraint." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 5, prompt: `Analytics show users spend a long time on a screen you designed as part of your ${skill} work. Is that a good or bad sign?`, options: ["It depends on the screen's intent — long time on a checkout page may signal confusion, while on a content page it may signal engagement", "Long time on any screen is always good engagement", "Long time on any screen is always bad, indicating confusion", "Time-on-screen has no meaningful interpretation"], correctIdx: 0, explanation: "Time-on-screen is not inherently good or bad — its meaning depends entirely on what the screen is supposed to accomplish, which is exactly the kind of context-dependent interpretation good UX analysis requires." }),
      (skill) => ({ type: "scenario", difficulty: 5, prompt: `Your ${skill} recommendation conflicts with an established brand guideline. What's the responsible way to proceed?`, options: ["Present the usability evidence and propose a specific, scoped exception or guideline update, rather than silently overriding or blindly complying", "Ignore the brand guideline since usability matters more", "Follow the guideline exactly even if it actively harms usability", "Quietly ship the non-compliant version and hope nobody notices"], correctIdx: 0, explanation: "Guidelines exist for real reasons, but so does usability evidence — the responsible move surfaces the conflict explicitly with data, letting the right people make an informed trade-off rather than either party unilaterally overriding the other." }),
      (skill) => ({ type: "reasoning", difficulty: 1, prompt: `A junior designer asks why ${skill} matters if the design "looks good" already. What's the accurate answer?`, options: ["Looking good and being usable are different things — a beautiful design can still confuse or block real users", "It doesn't matter if it looks good", "Usability testing is only for ugly designs", "Looking good guarantees usability"], correctIdx: 0, explanation: "Visual appeal and usability are genuinely separate qualities — plenty of attractive designs still fail real users on findability, clarity, or task completion, which is precisely what testing catches." }),
    ],
  },
  sales: {
    skills: ["Discovery Calls", "Objection Handling", "Pipeline Management"],
    frames: [
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `During a ${skill}, a prospect gives a vague answer like "we're looking to improve efficiency." What's the best follow-up?`, options: ["Ask for a specific example of where inefficiency is costing them time or money today", "Move on to pitching your product's features", "Assume you already know what they mean", "End the call since the answer wasn't detailed enough"], correctIdx: 0, explanation: "Vague pain statements need to be grounded in a concrete example before you can qualify or pitch effectively — specifics reveal whether there's a real, sizable problem." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `In ${skill}, a prospect says "it's too expensive" right after seeing pricing. What does this usually signal?`, options: ["A value gap — they haven't yet connected the price to a clear enough return, not necessarily that the number itself is wrong", "The deal is definitely dead", "You should immediately offer a discount", "They are lying about their budget"], correctIdx: 0, explanation: "Price objections immediately after seeing a number are often really about unclear value, not the number itself — the productive move is reconnecting price to the specific outcome, not jumping straight to a discount." }),
      (skill) => ({ type: "operational_decision", difficulty: 2, prompt: `Your ${skill} shows a large deal sitting in the same stage for two months with no activity logged. What should you do?`, options: ["Re-engage the prospect directly to confirm real status rather than leaving it stale in the forecast", "Leave it as-is since it's a big deal and might still close", "Mark it closed-lost automatically after any inactivity", "Increase its forecasted probability since it's been open a long time"], correctIdx: 0, explanation: "A stale deal with no activity is a forecasting risk hiding in plain sight — confirming real status directly is better than assuming either continued momentum or automatic loss." }),
      (skill) => ({ type: "scenario", difficulty: 3, prompt: `During ${skill}, the champion you've been talking to suddenly goes quiet for three weeks. What's the most useful next move?`, options: ["Try reaching other stakeholders you identified earlier, since champions can lose influence, change roles, or get reassigned", "Wait indefinitely for them to respond", "Assume the deal is dead and stop all outreach", "Send the exact same follow-up email daily"], correctIdx: 0, explanation: "Over-reliance on a single champion is a known deal risk — when they go dark, multi-threading to other stakeholders protects the deal instead of leaving it entirely dependent on one contact reappearing." }),
      (skill) => ({ type: "reasoning", difficulty: 3, prompt: `A prospect in ${skill} objects "we already have a solution for this." What's the most useful response?`, options: ["Ask what's working and not working about the current solution to find a real gap or switching trigger", "Immediately concede and end the conversation", "Insist their current solution is bad without evidence", "Ignore the objection and keep pitching the same points"], correctIdx: 0, explanation: "An existing solution objection is an opportunity to learn the real gap, if any exists — conceding immediately or arguing without evidence both skip the actual discovery that determines if there's a legitimate opportunity." }),
      (skill) => ({ type: "operational_decision", difficulty: 4, prompt: `Your manager asks you to inflate a deal's forecast probability to hit team targets for the quarter. What's the professional response?`, options: ["Decline and explain that accurate forecasting protects the whole team's planning, even if the near-term number looks worse", "Inflate it since the manager asked", "Inflate it but only slightly so it's less noticeable", "Report a different number to your manager than what's in the actual system"], correctIdx: 0, explanation: "Forecast integrity affects hiring, resourcing, and investor commitments downstream — inflating it to look better this quarter creates a bigger, compounding problem later, and the honest number is always the professional answer regardless of what's requested." }),
      (skill) => ({ type: "scenario", difficulty: 4, prompt: `During ${skill}, you realize the prospect's actual use case doesn't fit your product well at all. What's the right move?`, options: ["Tell them honestly, even if it costs you the deal, rather than force-fitting a bad match", "Push forward anyway to hit your number", "Oversell features that don't really apply to their case", "Quietly let the deal die without saying anything"], correctIdx: 0, explanation: "Forcing a bad-fit deal through usually produces churn, refunds, and reputational damage that costs far more than the one deal — honest disqualification protects both the prospect and your long-term pipeline health." }),
      (skill) => ({ type: "work_situation", difficulty: 5, prompt: `A prospect asks for a feature your product doesn't have and says the deal depends on it. What's the disciplined response?`, options: ["Clarify the underlying need, check the real roadmap status, and set honest expectations rather than promising something uncertain", "Promise it will ship soon regardless of the actual roadmap", "Say the feature already exists", "Refuse to discuss the request at all"], correctIdx: 0, explanation: "Promising uncertain roadmap items to close a deal creates downstream trust and churn problems — understanding the real underlying need and giving an honest roadmap answer is the disciplined path even under deal pressure." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 5, prompt: `Your ${skill} report shows win rate up but average deal size down significantly this quarter. How should you interpret this?`, options: ["Investigate whether the team is closing more small, easier deals instead of pursuing larger, harder-fought ones — a possible trade-off, not a pure win", "Just celebrate the higher win rate", "Assume the two numbers are unrelated", "Conclude deal size never matters if win rate is up"], correctIdx: 0, explanation: "A rising win rate paired with a falling deal size can indicate the team is chasing easier, smaller wins rather than pursuing higher-value opportunities — a real trade-off worth investigating, not an unambiguous improvement." }),
      (skill) => ({ type: "reasoning", difficulty: 1, prompt: `A new rep asks why ${skill} matters if they already have a great product to sell. What's the accurate answer?`, options: ["Even a great product needs a clear articulation of the prospect's specific problem to create urgency and justify the purchase", "It doesn't matter, a great product sells itself", "Only weak products need a sales process", "Skipping it saves time with no real downside"], correctIdx: 0, explanation: "Even genuinely great products rarely sell themselves without a clear connection to the specific buyer's problem and urgency — that connection is exactly what a disciplined sales process establishes." }),
    ],
  },
  marketing: {
    skills: ["Campaign Analysis", "Content Strategy", "SEO"],
    frames: [
      (skill) => ({ type: "dashboard_interpretation", difficulty: 1, prompt: `A ${skill} report shows a campaign has a high click-through rate but very low conversion. What's a likely explanation?`, options: ["The ad promises something the landing page doesn't clearly deliver, causing a mismatch", "High CTR always means the campaign is succeeding", "Conversion rate never matters if CTR is good", "The tracking pixel is definitely broken"], correctIdx: 0, explanation: "A CTR/conversion mismatch is a classic sign of a promise-delivery gap between the ad and the landing experience — the ad is compelling enough to click, but something after the click isn't matching expectations." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `Your ${skill} plan is based entirely on one competitor's approach with no adaptation to your own audience. What's the risk?`, options: ["Their audience, positioning, and resources may differ significantly, so copying tactics without adaptation can miss what actually works for your audience", "There's no risk, copying proven approaches always works", "It guarantees the same results they got", "Competitors always have worse strategies than you'd invent yourself"], correctIdx: 0, explanation: "Tactics that work for one brand's specific audience and positioning don't automatically transfer — copying without adapting to your own audience's actual context is a common and avoidable mistake." }),
      (skill) => ({ type: "scenario", difficulty: 2, prompt: `A ${skill} piece gets huge traffic but almost no engagement (comments, shares, time on page). What should you check?`, options: ["Whether the traffic source matches your actual target audience, or if it's low-intent/low-relevance traffic", "Assume the content itself must be terrible", "Assume more traffic is always better regardless of engagement", "Immediately delete the content"], correctIdx: 0, explanation: "High traffic with low engagement often points at a traffic-quality or audience-mismatch problem rather than a content-quality problem — checking the traffic source is the useful next step." }),
      (skill) => ({ type: "operational_decision", difficulty: 3, prompt: `Your ${skill} strategy chases a trending topic unrelated to your actual product just for visibility. What's the downside?`, options: ["It can attract attention from an audience that has no reason to become customers, wasting effort without building a relevant audience", "There's no downside if it gets more views", "It always improves brand perception", "It's risk-free as long as engagement numbers go up"], correctIdx: 0, explanation: "Chasing irrelevant trends can generate vanity metrics (views, brief attention) without building an audience that has any reason to convert — visibility isn't the same as relevant reach." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 3, prompt: `Your ${skill} rankings for a key page dropped sharply after a site redesign. What's the most likely cause to investigate first?`, options: ["Whether the redesign changed URLs, page structure, or content in ways that broke existing search signals", "Search engines randomly penalize redesigned sites", "Rankings never relate to site structure", "It must be a manual penalty from the search engine"], correctIdx: 0, explanation: "Ranking drops right after a redesign are most often self-inflicted — changed URLs, lost internal links, or altered content structure are the first things to audit before assuming an external cause." }),
      (skill) => ({ type: "reasoning", difficulty: 4, prompt: `Leadership wants your ${skill} to claim credit for a revenue increase that coincided with a major product launch and a price change in the same month. What's the accurate framing?`, options: ["Acknowledge multiple factors changed simultaneously and it's hard to isolate marketing's specific contribution without more careful analysis", "Claim marketing caused all of the increase", "Claim marketing caused none of it", "Avoid discussing attribution at all"], correctIdx: 0, explanation: "When multiple significant changes happen in the same period, attributing the full outcome to any single one overstates what you can actually know — an honest analysis acknowledges the confound rather than claiming full credit." }),
      (skill) => ({ type: "scenario", difficulty: 4, prompt: `A ${skill} campaign performs great in testing but underperforms at full scale. What's a common reason for this gap?`, options: ["The test audience (often early adopters or a narrow segment) doesn't represent the broader audience reached at scale", "Scaling a campaign always improves performance automatically", "The original test must have been fraudulent", "Full-scale campaigns always underperform regardless of quality"], correctIdx: 0, explanation: "Small-scale tests often reach an unrepresentative early-adopter or narrow segment audience — performance regressing at broader scale is a well-known pattern, not necessarily a sign anything was done wrong." }),
      (skill) => ({ type: "work_situation", difficulty: 5, prompt: `Sales blames your ${skill} for poor lead quality, while your dashboards show record lead volume. How do you resolve the disagreement productively?`, options: ["Align on a shared definition of lead quality (e.g. close rate, fit criteria) rather than arguing volume vs. quality past each other", "Insist your dashboards are the only truth that matters", "Accept blame immediately without investigating", "Stop generating leads until the disagreement resolves itself"], correctIdx: 0, explanation: "Volume and quality are different metrics measuring different things — the productive path is agreeing on what 'quality' actually means together, not defending one metric against a complaint about a different one." }),
      (skill) => ({ type: "operational_decision", difficulty: 5, prompt: `Your ${skill} budget is being cut by 40% mid-quarter. What's the most disciplined response?`, options: ["Reprioritize spend toward the channels/tactics with the best proven return, cutting the weakest performers first", "Cut every channel by exactly 40% evenly", "Cut the newest initiatives regardless of performance", "Ignore the cut and overspend anyway"], correctIdx: 0, explanation: "An across-the-board even cut ignores that channels have different returns — the disciplined response protects your best-performing spend and cuts the weakest first, using actual performance data to guide the reduction." }),
      (skill) => ({ type: "reasoning", difficulty: 1, prompt: `A junior marketer asks why ${skill} needs a measurable goal if the content is "obviously good." What's the accurate answer?`, options: ["Subjective quality doesn't tell you whether the content achieved a specific business outcome — a measurable goal connects the work to real impact", "If it's good, measurement is unnecessary", "Measurable goals only matter for paid ads", "Good content always performs well regardless of goals"], correctIdx: 0, explanation: "Perceived quality and measurable business impact are different things — a piece can be well-crafted and still fail to move the specific goal it was meant to support, which is exactly why a defined metric matters." }),
    ],
  },
  finance_accounting: {
    skills: ["Financial Reconciliation", "Budgeting", "Financial Reporting"],
    frames: [
      (skill) => ({ type: "bug_finding", difficulty: 1, prompt: `During ${skill}, two records that should match differ by exactly $100.00. What's the most likely cause to check first?`, options: ["A transposition or single missing/extra transaction entered as a round number", "The bank made an unexplainable error", "Currency conversion rates changed", "It's not worth investigating a small difference"], correctIdx: 0, explanation: "A clean, round-number discrepancy is a classic signature of a data-entry error (transposed digits, a missed or duplicated entry) — checking recent entries near that amount is the efficient first step." }),
      (skill) => ({ type: "scenario", difficulty: 2, prompt: `Your ${skill} shows actual spend tracking well under budget for a department three months running. What should you verify before praising efficiency?`, options: ["Whether spend is under-tracked/miscoded rather than genuinely under budget, and whether planned initiatives are actually happening", "Nothing, under-budget is always simply good news", "Assume the department is being deliberately wasteful elsewhere", "Immediately cut their budget further"], correctIdx: 0, explanation: "Consistent, significant under-spend can reflect miscoded transactions or delayed/incomplete initiatives just as easily as genuine efficiency — verifying which it is prevents both false praise and a premature budget cut." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `A manager asks you to move an expense into next quarter's ${skill} to make this quarter's numbers look better. What's the correct response?`, options: ["Decline — expenses belong in the period they were actually incurred, and shifting them misstates financial reality", "Do it since it's a small amount", "Do it only if the manager insists strongly", "Do it but keep a private note about it"], correctIdx: 0, explanation: "Shifting expenses between periods to manage appearance is a form of misstatement regardless of size or how insistent the request is — the correct accounting period is when the expense was actually incurred." }),
      (skill) => ({ type: "scenario", difficulty: 3, prompt: `Your ${skill} for the quarter shows a large unexplained variance in one account. What's the disciplined next step?`, options: ["Trace the variance back to specific underlying transactions until the cause is identified, not just noted as an estimate", "Note it as 'immaterial' without investigation since it's just one account", "Adjust the number to match expectations without explanation", "Wait until next quarter to see if it resolves itself"], correctIdx: 0, explanation: "An unexplained variance should be traced to its root transactions, not smoothed over or waited out — 'immaterial' and 'unexplained' are not the same thing, and only investigation can tell you which applies." }),
      (skill) => ({ type: "operational_decision", difficulty: 3, prompt: `Department heads consistently pad their ${skill} requests, anticipating cuts. What's a healthier system-level fix?`, options: ["Build trust through transparent, collaborative budget reviews so padding isn't the rational strategy anymore", "Cut every request by the same percentage automatically", "Publicly call out departments that pad requests", "Approve every request as submitted with no review"], correctIdx: 0, explanation: "Padding is usually a rational response to an adversarial budget process — fixing the underlying incentive through transparency addresses the root cause better than blanket cuts or public shaming, which just reinforce the same dynamic." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 4, prompt: `Your ${skill} shows revenue up but cash flow down in the same period. What should you investigate?`, options: ["Whether receivables are growing (revenue booked but not yet collected) — a common driver of this specific divergence", "Assume the two numbers must be measurement errors", "Conclude revenue and cash flow are unrelated concepts", "Ignore it since revenue is the more important number"], correctIdx: 0, explanation: "Rising revenue with falling cash flow is a well-known pattern usually driven by growing receivables (booked but uncollected revenue) — investigating collections is the natural next step, not dismissing either number." }),
      (skill) => ({ type: "reasoning", difficulty: 4, prompt: `Leadership asks you to classify a recurring operating cost as a one-time item in your ${skill} to improve a key metric's optics. What's the correct response?`, options: ["Decline — misclassifying a recurring cost as one-time distorts the metric's meaning for anyone relying on it", "Do it since leadership requested it", "Do it only this one time as a favor", "Reclassify it but flag it only internally, not in the actual reporting"], correctIdx: 0, explanation: "Classification exists to make numbers meaningful and comparable — misclassifying a recurring cost as one-time to flatter a metric undermines the very purpose of the reporting, regardless of who requests it." }),
      (skill) => ({ type: "scenario", difficulty: 5, prompt: `Your ${skill} process relies on a single person's manual spreadsheet with no backup or review. What's the risk, and the fix?`, options: ["A single point of failure for critical financial data — introduce a second reviewer and a documented, backed-up process", "No real risk if that person is reliable", "The risk only matters for very large companies", "Spreadsheets are inherently safer than any system"], correctIdx: 0, explanation: "A single unreviewed spreadsheet controlling critical financial data is a classic single-point-of-failure and control weakness, regardless of how reliable the person is — a second reviewer and documented process is the standard mitigation." }),
      (skill) => ({ type: "work_situation", difficulty: 5, prompt: `An auditor flags a control weakness in your ${skill} process that management wants to dispute rather than fix. What's the responsible path?`, options: ["Evaluate the finding on its merits and, if valid, address the underlying control gap rather than just contesting the finding", "Dispute it regardless of merit to avoid the appearance of a problem", "Ignore the finding since audits are often wrong", "Fix it only cosmetically without addressing the actual control gap"], correctIdx: 0, explanation: "A valid control weakness doesn't go away by disputing the finding — the responsible path evaluates whether the finding is accurate and, if so, fixes the actual underlying gap rather than managing the appearance of the audit result." }),
      (skill) => ({ type: "reasoning", difficulty: 1, prompt: `A new hire asks why ${skill} needs to be done monthly if the company only reports annually. What's the accurate answer?`, options: ["Frequent reconciliation/reporting catches errors early, before they compound or become much harder to trace months later", "Monthly work is unnecessary busywork if annual is the only requirement", "It's only needed for public companies", "Errors don't compound over time, so timing doesn't matter"], correctIdx: 0, explanation: "Catching a discrepancy in the month it happens is far easier than untangling it eight months later buried under subsequent transactions — frequent cadence exists specifically to keep errors small and traceable." }),
    ],
  },
  operations_supply_chain: {
    skills: ["Inventory Management", "Vendor Coordination", "Logistics Planning"],
    frames: [
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `Your ${skill} system shows a SKU at zero stock but the warehouse floor has units on a shelf. What's the first thing to check?`, options: ["Whether a recent receiving or transfer transaction wasn't recorded in the system", "Assume the units on the shelf are miscounted physically", "Reorder more stock immediately without investigating", "Assume theft without any other evidence"], correctIdx: 0, explanation: "A system-vs-physical mismatch is most often an unrecorded transaction (a receipt, transfer, or return that didn't get logged) — checking recent transaction history is the efficient first step before assuming a physical count error or theft." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `A ${skill} vendor consistently delivers on time but quality has been slipping for two months. What's the balanced response?`, options: ["Raise the quality trend directly with the vendor with specific data, before considering switching suppliers", "Switch vendors immediately with no discussion", "Ignore quality since on-time delivery is what matters most", "Wait indefinitely hoping it improves on its own"], correctIdx: 0, explanation: "A specific, data-backed conversation gives the vendor a fair chance to correct course, which is usually faster and less disruptive than switching immediately — but it needs to happen now, not be left to resolve itself." }),
      (skill) => ({ type: "operational_decision", difficulty: 2, prompt: `Your ${skill} plan holds three months of safety stock for every single SKU regardless of demand variability. What's the downside?`, options: ["It ties up cash and warehouse space in slow-moving items that don't need that much buffer, while possibly under-buffering volatile ones", "There is no downside, more safety stock is always better", "It guarantees you'll never run out of anything", "It only matters for perishable goods"], correctIdx: 0, explanation: "A one-size-fits-all safety stock policy ignores that different SKUs have very different demand volatility — it over-invests cash and space in predictable slow movers while potentially under-buffering the genuinely volatile ones that need it most." }),
      (skill) => ({ type: "scenario", difficulty: 3, prompt: `A key ${skill} vendor announces a 20% price increase with two weeks' notice. What's the disciplined response?`, options: ["Assess the actual cost impact, explore alternative suppliers, and negotiate before accepting or rejecting outright", "Accept immediately to avoid any disruption", "Cut the vendor immediately with no transition plan", "Ignore the notice and hope it doesn't apply to you"], correctIdx: 0, explanation: "A sudden price increase deserves a real assessment and negotiation attempt before either capitulating or cutting ties abruptly — both extremes skip the analysis that protects cost and continuity." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 3, prompt: `Your ${skill} dashboard shows on-time delivery rate holding steady while customer complaints about delivery are rising. What should you check?`, options: ["Whether 'on-time' is measured against an outdated or overly lenient promise date rather than what customers were actually told", "Assume customers are simply becoming more difficult", "Assume the dashboard metric must be fabricated", "Ignore the complaints since the metric looks fine"], correctIdx: 0, explanation: "A metric that looks fine while a related complaint volume rises often means the metric's definition (e.g. promise date) no longer matches customer expectations — checking the measurement definition itself is the useful next step." }),
      (skill) => ({ type: "operational_decision", difficulty: 4, prompt: `A single supplier provides a critical component with no qualified backup. What's the responsible ${skill} action?`, options: ["Begin qualifying at least one backup supplier, even if the primary is currently performing well", "Do nothing since the current supplier is reliable today", "Switch away from the reliable supplier immediately for no reason", "Stockpile years of inventory instead of addressing the supplier concentration"], correctIdx: 0, explanation: "Single-source dependency on a critical component is a structural risk regardless of current performance — qualifying a backup is the standard mitigation, since 'reliable today' doesn't protect against a future disruption at that one supplier." }),
      (skill) => ({ type: "scenario", difficulty: 4, prompt: `Your ${skill} forecast badly under-predicted demand for a seasonal item, causing stockouts. What's the most useful post-mortem question?`, options: ["What signal (e.g. early sell-through data, marketing plans) was available but not incorporated into the forecast", "Whose fault the stockout was", "Whether to abandon forecasting entirely", "Whether to over-order everything next time regardless of data"], correctIdx: 0, explanation: "A useful post-mortem looks for what signal existed but wasn't used, so the forecasting process actually improves — assigning blame or overcorrecting to blanket over-ordering doesn't fix the underlying forecasting gap." }),
      (skill) => ({ type: "work_situation", difficulty: 5, prompt: `Two internal teams disagree on ${skill} priorities during a supply shortage — one wants to protect a flagship product, the other a high-margin one. How do you resolve it?`, options: ["Bring both teams together with the actual business trade-off data (revenue, margin, strategic value) to make a joint, informed call", "Let whichever team escalates loudest win", "Split the limited supply exactly evenly regardless of the trade-offs", "Delay the decision until the shortage resolves itself"], correctIdx: 0, explanation: "A genuine resource-allocation trade-off during a shortage needs an informed joint decision using real business data — defaulting to whoever's loudest, an arbitrary even split, or delay all avoid making the actual call that's needed." }),
      (skill) => ({ type: "reasoning", difficulty: 5, prompt: `Leadership wants to switch your entire ${skill} to the cheapest available vendor with no evaluation of reliability or quality history. What's the risk to raise?`, options: ["Lowest cost alone doesn't capture total cost of ownership — disruption risk, quality issues, and switching costs can outweigh the unit price savings", "There's no risk, cheapest is always the best choice", "Cost should never be a factor in vendor selection", "Reliability and quality never actually vary between vendors"], correctIdx: 0, explanation: "Unit price is only one component of total cost — a cheaper vendor with worse reliability or quality can cost far more overall through disruptions, rework, or emergency sourcing, which is the risk worth surfacing before a decision based on price alone." }),
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `A new team member asks why ${skill} needs regular cycle counts if the system already tracks inventory automatically. What's the accurate answer?`, options: ["Automated tracking can still drift from physical reality due to unrecorded transactions, damage, or loss — cycle counts catch and correct that drift", "Cycle counts are unnecessary busywork if the system is automated", "Automated systems are always perfectly accurate", "Cycle counts are only needed once a year regardless of drift"], correctIdx: 0, explanation: "Automation reduces but doesn't eliminate the gap between recorded and physical inventory — unrecorded damage, loss, or transaction errors still accumulate, which is exactly why periodic cycle counts remain necessary even with a good system." }),
    ],
  },
  hr_people: {
    skills: ["Recruiting", "Employee Relations", "Onboarding"],
    frames: [
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `During ${skill}, a hiring manager wants to skip reference checks to move faster on a strong candidate. What's the balanced response?`, options: ["Explain the specific risk of skipping this step and propose an expedited but still real check, not skip it entirely", "Skip it since the hiring manager is confident", "Refuse to move forward at all until every check is exhaustive", "Do the check after the offer has already been signed"], correctIdx: 0, explanation: "Reference checks exist to catch real risks that confidence alone doesn't rule out — the balanced move is to expedite the process, not eliminate the safeguard entirely." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `An employee raises a complaint about a manager in ${skill}, but is worried about retaliation. What's the correct first step?`, options: ["Explain the confidentiality and anti-retaliation protections in place, and document the complaint properly", "Tell the manager immediately who complained", "Dismiss the complaint since it's their word against the manager's", "Ask the employee to handle it directly with the manager alone first"], correctIdx: 0, explanation: "A credible complaint needs to be documented and protected properly from the start — revealing the source or dismissing it outright undermines both the process and the employee's trust in raising real issues." }),
      (skill) => ({ type: "operational_decision", difficulty: 2, prompt: `Your ${skill} process has candidates going through six separate interview rounds for a mid-level role. What's the likely cost?`, options: ["Strong candidates may drop out to faster-moving competing offers before your process concludes", "There's no cost, more rounds always produce better hires", "Six rounds guarantees no bad hires will occur", "Candidates never mind a long process if the company is good"], correctIdx: 0, explanation: "An excessively long interview process is a real competitive disadvantage for in-demand candidates, who often have other offers moving faster — thoroughness has to be balanced against speed, not maximized without limit." }),
      (skill) => ({ type: "scenario", difficulty: 3, prompt: `Two employees give conflicting accounts of the same workplace incident during an ${skill} investigation. What's the disciplined approach?`, options: ["Gather independent evidence (witnesses, documentation, timelines) rather than simply picking whichever account seems more credible on its face", "Believe whichever employee has more seniority", "Believe whichever employee complained first", "Drop the investigation since the accounts conflict"], correctIdx: 0, explanation: "Conflicting first-hand accounts are common and don't resolve by default toward seniority or who spoke first — independent, corroborating evidence is what actually establishes what happened." }),
      (skill) => ({ type: "reasoning", difficulty: 3, prompt: `A new hire's first week in ${skill} consists only of paperwork and no context on team goals or expectations. What's the risk?`, options: ["Slower ramp-up and lower early engagement — new hires need context and connection, not just administrative processing", "No risk, paperwork is the most important part of onboarding", "It guarantees a faster ramp than a more involved onboarding", "Context and goals don't matter in the first week"], correctIdx: 0, explanation: "A purely administrative first week misses the window where new hires form their early impression of the role and team — context and clear expectations are what actually accelerate productive ramp-up." }),
      (skill) => ({ type: "reasoning", difficulty: 5, prompt: `A ${skill} investigation involves a complaint against someone with close personal ties to senior leadership. What's the responsible path?`, options: ["Apply the exact same investigation standard and process regardless of the accused's relationships, and document that explicitly", "Handle it more leniently given the relationship", "Skip a formal investigation to avoid awkwardness", "Let the senior leader involved decide the outcome personally"], correctIdx: 0, explanation: "Personal or organizational proximity to leadership is exactly the situation where applying a consistent, documented process matters most — any deviation undermines the credibility of the entire process for everyone else." }),
      (skill) => ({ type: "scenario", difficulty: 4, prompt: `A manager wants to terminate an employee in ${skill} for "poor attitude" with no documented performance issues. What should you ask for?`, options: ["Specific, documented examples of the behavior and its business impact before proceeding", "Proceed with termination based on the manager's judgment alone", "Refuse to discuss the termination at all", "Terminate immediately to support the manager's authority"], correctIdx: 0, explanation: "Undocumented, vague justifications like 'poor attitude' create real legal and fairness risk — specific, documented examples of behavior and impact are what any defensible employment decision needs." }),
      (skill) => ({ type: "operational_decision", difficulty: 4, prompt: `Your ${skill} data shows a specific team has turnover triple the company average. What's the useful next step?`, options: ["Conduct structured exit interviews and a team-specific review to identify the actual root cause before assuming it's random", "Assume it's simply bad luck and take no action", "Immediately replace the team's manager without investigation", "Ignore it since overall company turnover looks fine"], correctIdx: 0, explanation: "A team-specific turnover spike this far above average is unlikely to be random — structured investigation (exit interviews, team review) is what identifies the actual cause, rather than guessing or ignoring the signal." }),
      (skill) => ({ type: "work_situation", difficulty: 5, prompt: `A senior leader is a strong performer but multiple ${skill} complaints allege a pattern of disrespectful behavior toward junior staff. What's the responsible path?`, options: ["Investigate the pattern with the same rigor regardless of the leader's seniority or performance", "Give the leader a pass because of their performance", "Dismiss the complaints as junior staff being overly sensitive", "Quietly move the leader to a different team without addressing the behavior"], correctIdx: 0, explanation: "Performance doesn't exempt anyone from a legitimate behavioral pattern investigation — applying the same rigor regardless of seniority is what makes the process credible and actually protects junior staff." }),
      (skill) => ({ type: "reasoning", difficulty: 1, prompt: `A hiring manager asks why ${skill} needs a structured process if they can "just tell" who's a good fit in the interview. What's the accurate answer?`, options: ["Unstructured gut-feel assessments are more prone to bias and inconsistency — structure improves both fairness and predictive accuracy", "Gut feel is always more accurate than structured evaluation", "Structure is only needed for large companies", "There's no meaningful difference between structured and unstructured approaches"], correctIdx: 0, explanation: "Research consistently shows structured evaluation reduces bias and better predicts on-the-job success compared to unstructured gut-feel judgment, however confident that judgment feels in the moment." }),
    ],
  },
  customer_success: {
    skills: ["Onboarding Support", "Retention", "Escalation Handling"],
    frames: [
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `During ${skill}, a new customer hasn't logged in since signing up a week ago. What's the most useful action?`, options: ["Proactively reach out to check on their setup and offer help before it becomes a churn risk", "Wait for them to reach out first", "Assume they've decided not to use the product", "Send the standard automated email and take no other action"], correctIdx: 0, explanation: "Early inactivity is one of the strongest churn predictors — proactive outreach during onboarding, before the customer disengages further, is far more effective than waiting or relying only on generic automation." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `A customer in ${skill} says they're "probably going to cancel" without specifying why. What's the productive response?`, options: ["Ask specifically what's driving that, since the real reason (price, missing feature, poor experience) determines what can actually be done", "Immediately offer a discount without knowing the reason", "Accept the cancellation as inevitable and stop engaging", "Argue that they shouldn't cancel without understanding their concern"], correctIdx: 0, explanation: "Different churn reasons need completely different responses — a discount doesn't fix a missing feature, and understanding the specific driver is what makes any save attempt actually relevant." }),
      (skill) => ({ type: "operational_decision", difficulty: 2, prompt: `Your ${skill} team resolves escalations fast but the same issues keep recurring for different customers. What's missing?`, options: ["A feedback loop from support back to product/engineering so root causes get fixed, not just individual symptoms", "Nothing, fast resolution is the only goal that matters", "The team should simply work even faster on each individual case", "Recurring issues are unavoidable and not worth investigating"], correctIdx: 0, explanation: "Fast individual resolution without a root-cause feedback loop just means the team keeps re-solving the same underlying problem — closing that loop back to product/engineering is what actually reduces recurrence." }),
      (skill) => ({ type: "scenario", difficulty: 3, prompt: `A high-value customer's ${skill} escalation has been passed between three different reps with no continuity. What's the impact?`, options: ["The customer has to re-explain the issue repeatedly, increasing frustration and the risk of churn regardless of the eventual resolution quality", "No impact as long as the issue is eventually resolved", "It shows the company has plenty of staff available to help", "Multiple reps always resolve issues faster than one owner"], correctIdx: 0, explanation: "Repeated hand-offs without continuity create a frustrating experience independent of resolution quality — for a high-value account especially, ownership continuity matters as much as the technical fix itself." }),
      (skill) => ({ type: "dashboard_interpretation", difficulty: 3, prompt: `Your ${skill} dashboard shows customer satisfaction scores are high, but renewal rate is declining. What should you investigate?`, options: ["Whether satisfaction surveys are reaching a biased sample (e.g. only engaged users) that doesn't represent the customers actually not renewing", "Assume the two metrics are simply unrelated", "Trust satisfaction scores exclusively since they're more recent", "Conclude renewal rate must be measured incorrectly"], correctIdx: 0, explanation: "A disconnect between satisfaction and renewal often means the satisfaction survey isn't reaching the disengaged customers who are actually the ones not renewing — investigating survey sample bias is the useful next step." }),
      (skill) => ({ type: "reasoning", difficulty: 4, prompt: `Leadership wants your ${skill} team to close escalation tickets faster by any means, including marking issues resolved before the customer confirms. What's the correct response?`, options: ["Push back — closing tickets without real customer confirmation manufactures a metric without solving the underlying problem", "Comply since leadership set the target", "Comply but only for less important customers", "Close tickets as requested but keep a private list of the real status"], correctIdx: 0, explanation: "Marking issues resolved without real confirmation optimizes the metric while leaving the actual customer problem unsolved — that's a worse outcome than a slower, honest resolution rate, regardless of who's requesting the shortcut." }),
      (skill) => ({ type: "scenario", difficulty: 4, prompt: `A customer's ${skill} issue is a known product limitation, not a bug, but they're understandably frustrated. What's the best response?`, options: ["Acknowledge the limitation honestly, explain any workaround, and log it as product feedback rather than implying it will be fixed imminently", "Tell them it will definitely be fixed soon even if there's no roadmap commitment", "Tell them it's not a real issue and dismiss the frustration", "Avoid addressing the root cause and only offer generic sympathy"], correctIdx: 0, explanation: "Honest acknowledgment plus a real workaround respects the customer's frustration without creating a false expectation — promising an imminent fix you can't actually commit to just creates a bigger trust problem later." }),
      (skill) => ({ type: "work_situation", difficulty: 5, prompt: `A major customer threatens to churn unless you build a custom feature just for them through your ${skill} relationship. What's the disciplined path?`, options: ["Evaluate whether the request serves a broader need worth building generally, and be honest about what's feasible rather than promising a one-off under pressure", "Promise the custom feature immediately to save the account", "Refuse to even discuss the request", "Quietly agree but never actually build it"], correctIdx: 0, explanation: "Deal-pressure feature promises without evaluating broader fit or feasibility tend to create technical debt and unmet expectations — the disciplined path evaluates the request honestly rather than reactively promising under pressure." }),
      (skill) => ({ type: "reasoning", difficulty: 1, prompt: `A new team member asks why ${skill} matters if the product mostly sells itself. What's the accurate answer?`, options: ["Even a great product needs ongoing support to realize its value — customers who don't get help adopting it often churn regardless of product quality", "It doesn't matter if the product is good enough", "Support only matters for bad products", "Customers always figure things out on their own eventually"], correctIdx: 0, explanation: "Product quality and successful adoption are different things — customers who hit friction without support often churn even when the underlying product is genuinely strong, which is exactly the gap this work closes." }),
      (skill) => ({ type: "operational_decision", difficulty: 2, prompt: `Your ${skill} process treats every customer complaint with the same priority regardless of account size or severity. What's the risk?`, options: ["Critical issues for major accounts can get stuck in the same queue as minor requests, risking a disproportionately damaging churn event", "There's no risk, treating everyone equally is always fair and sufficient", "It guarantees the fastest possible resolution for everyone", "Priority tiering is unnecessary if the team works hard enough"], correctIdx: 0, explanation: "Equal treatment regardless of severity or account impact can mean a critical issue for a major account waits in the same queue as a minor one — some form of triage by severity and impact is what prevents a disproportionately costly outcome." }),
    ],
  },
  other: {
    skills: ["Communication", "Time Management", "Problem Solving"],
    frames: [
      (skill) => ({ type: "scenario", difficulty: 1, prompt: `A colleague asks for help with ${skill} but gives you almost no context about the actual problem. What's the best first move?`, options: ["Ask clarifying questions to understand the real problem before offering a solution", "Guess at the problem and offer a generic solution immediately", "Tell them to figure it out themselves", "Ignore the request since it's unclear"], correctIdx: 0, explanation: "Solving the wrong problem quickly is worse than taking a moment to clarify — a few targeted questions upfront usually save much more time than they cost." }),
      (skill) => ({ type: "reasoning", difficulty: 2, prompt: `You're using ${skill} and realize you've been working on the wrong priority all week. What's the constructive next step?`, options: ["Acknowledge it, communicate the situation to stakeholders, and re-prioritize immediately rather than continuing out of sunk-cost momentum", "Keep going since you've already invested the time", "Hide the mistake and hope no one notices", "Blame unclear instructions without taking any corrective action"], correctIdx: 0, explanation: "Continuing on the wrong priority just to avoid 'wasting' the time already spent is the sunk-cost fallacy in action — the constructive move is correcting course as soon as the mistake is recognized, communicated openly." }),
      (skill) => ({ type: "operational_decision", difficulty: 2, prompt: `Your ${skill} approach involves saying yes to every request that comes your way. What's the long-term risk?`, options: ["Overcommitment leading to lower quality across everything and eventual burnout, rather than doing fewer things well", "There's no risk, saying yes to everything shows great teamwork", "It guarantees you'll be seen as the most valuable team member", "Every request is equally important so this approach is correct"], correctIdx: 0, explanation: "Unlimited yes-saying eventually spreads effort too thin to do anything well and leads toward burnout — sustainable performance requires some prioritization and occasional, honest no's." }),
      (skill) => ({ type: "scenario", difficulty: 3, prompt: `During ${skill}, you discover a recurring problem that a quick workaround keeps patching instead of fixing. What's the disciplined move?`, options: ["Flag the pattern and propose addressing the root cause, even if the workaround is technically 'good enough' for now", "Keep applying the workaround since it technically resolves each instance", "Ignore the pattern since each individual instance gets handled", "Assume nothing can be done about a recurring problem"], correctIdx: 0, explanation: "A workaround that keeps getting reapplied to the same recurring problem is a sign of an unaddressed root cause — flagging the pattern, not just closing each instance, is what actually reduces the recurring cost over time." }),
      (skill) => ({ type: "reasoning", difficulty: 3, prompt: `A stakeholder gives you feedback using ${skill} that feels personal rather than specific. What's the productive response?`, options: ["Ask for specific examples of what didn't work, redirecting toward actionable detail rather than reacting defensively", "Respond defensively to match their tone", "Ignore the feedback entirely since it felt unfair", "Agree with everything without seeking any specifics"], correctIdx: 0, explanation: "Vague or emotionally charged feedback becomes useful once you redirect toward specific, actionable examples — neither defensiveness nor blanket agreement extracts the useful signal that might be in there." }),
      (skill) => ({ type: "operational_decision", difficulty: 4, prompt: `You're asked to use ${skill} to make a decision with incomplete information under a tight deadline. What's the disciplined approach?`, options: ["Make the best call with the information available, clearly flag the assumptions and uncertainty, and revisit if better data arrives", "Refuse to decide until information is complete", "Decide without noting any assumptions or uncertainty", "Delay past the deadline waiting for perfect information"], correctIdx: 0, explanation: "Most real decisions happen under some uncertainty — the disciplined approach is deciding with the best available information while being explicit about the assumptions, not waiting indefinitely for certainty that may never come." }),
      (skill) => ({ type: "scenario", difficulty: 4, prompt: `Your ${skill} plan for the week gets disrupted by an urgent, genuinely important request. What's the balanced response?`, options: ["Re-prioritize deliberately, communicate the trade-off to affected stakeholders, rather than silently dropping the original commitments", "Ignore the urgent request to protect the original plan", "Drop everything for the new request without telling anyone about the impact", "Try to do all of it without adjusting the plan or communicating"], correctIdx: 0, explanation: "A genuine re-prioritization is fine — the mistake is doing it silently, leaving stakeholders of the original commitments surprised later, rather than communicating the trade-off as it happens." }),
      (skill) => ({ type: "work_situation", difficulty: 5, prompt: `You strongly disagree with a decision made using ${skill} by someone senior to you, and you believe it will cause real harm. What's the responsible path?`, options: ["Raise the specific concern directly and constructively, with your reasoning and evidence, rather than staying silent or quietly undermining it", "Say nothing and let it play out", "Comply publicly while working against it privately", "Escalate immediately over the person's head without discussing it with them first"], correctIdx: 0, explanation: "Silent compliance or private undermining both avoid the actual disagreement without resolving it — raising the concern directly, with real reasoning, is what gives a potentially harmful decision a chance to be corrected before it causes damage." }),
      (skill) => ({ type: "reasoning", difficulty: 1, prompt: `Someone asks why ${skill} matters if they're already naturally good at their core job. What's the accurate answer?`, options: ["Core technical skill and skills like this often determine whether that expertise actually reaches its intended impact — they're complementary, not optional extras", "It doesn't matter if someone is already skilled at their core job", "This category of skill only matters for junior people", "Natural talent in one area guarantees strength in all related areas"], correctIdx: 0, explanation: "Being excellent at the core technical work doesn't automatically translate into effectively communicating it, prioritizing it, or navigating the people side of getting it done — these are complementary skills, not redundant ones." }),
      (skill) => ({ type: "scenario", difficulty: 2, prompt: `You're using ${skill} and notice you keep making the same small mistake across several tasks. What's the useful response?`, options: ["Identify the specific pattern behind the mistake and build a small check or habit to catch it, rather than just trying to 'be more careful'", "Assume it's random bad luck each time", "Ignore it since each individual mistake was minor", "Conclude nothing can be done to prevent human error"], correctIdx: 0, explanation: "'Try to be more careful' rarely fixes a recurring pattern — identifying the specific root cause and building a concrete check or habit around it is what actually reduces a repeated small mistake over time." }),
    ],
  },
}

// Every frame above writes the correct option first (index 0) for
// authoring convenience — that would leave every draft's correct answer
// sitting at option "a", a real quality defect (trivially gameable) for
// an actual question bank. Shuffle each question's options deterministically
// (seeded by domain+skill+frame index, so re-running this generator
// produces byte-identical output) so correct answers land across all four
// positions roughly evenly instead of always at "a".
function seededShuffleIndices(n, seed) {
  let s = seed >>> 0
  const rand = () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296 }
  const idx = Array.from({ length: n }, (_, i) => i)
  for (let i = n - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[idx[i], idx[j]] = [idx[j], idx[i]]
  }
  return idx
}

function hashSeed(str) {
  let h = 2166136261 >>> 0
  for (let i = 0; i < str.length; i++) h = Math.imul(h ^ str.charCodeAt(i), 16777619) >>> 0
  return h >>> 0
}

function buildDomainQuestions(domainKey, config) {
  const questions = []
  for (const skill of config.skills) {
    config.frames.forEach((frameFn, frameIdx) => {
      const frame = frameFn(skill)
      const order = seededShuffleIndices(frame.options.length, hashSeed(`${domainKey}:${skill}:${frameIdx}`))
      const shuffledOptions = order.map((origIdx, newIdx) => ({ id: ["a", "b", "c", "d"][newIdx], text: frame.options[origIdx] }))
      const newCorrectIdx = order.indexOf(frame.correctIdx)

      questions.push({
        domain: domainKey,
        skill_tags: [skill.toLowerCase().replace(/\s+/g, "_")],
        difficulty: frame.difficulty,
        question_type: QUESTION_TYPES.includes(frame.type) ? frame.type : "scenario",
        prompt: frame.prompt,
        options: shuffledOptions,
        correct_option_id: ["a", "b", "c", "d"][newCorrectIdx],
        explanation: frame.explanation,
        source: "ai_generated",
      })
    })
  }
  return questions
}

// Only the 10 supported domains count toward the 300-draft deliverable —
// 'other' is a schema catch-all, not one of the "10 clearly defined
// domains" the instructions ask for 30-each of. Its frames are defined
// above for completeness/future use but intentionally excluded here.
const SUPPORTED_DOMAIN_KEYS = Object.keys(DOMAINS).filter(k => k !== "other")

const all = []
for (const domainKey of SUPPORTED_DOMAIN_KEYS) {
  all.push(...buildDomainQuestions(domainKey, DOMAINS[domainKey]))
}

writeFileSync("docs/question-bank-drafts-300.json", JSON.stringify(all, null, 2))
console.log(`Generated ${all.length} draft questions across ${Object.keys(DOMAINS).length} domains -> docs/question-bank-drafts-300.json`)

const byDomain = {}
for (const q of all) byDomain[q.domain] = (byDomain[q.domain] || 0) + 1
console.log(byDomain)
